### ISSUE TITLE
Is SBT's ProjectRoot supported?

### ISSUE THREAD

**Issue by edrevo** [scalacenter/bloop#1002]
I have added `bloopAggregateSourceDependencies in Global := true` as per https://github.com/scalacenter/bloop/issues/375, but I'm still not getting a bloop config file generated for a project that is defined as `RootProject` in my build.sbt

Is this a supported scenario?

**Comment by jvican** [comment]
Hey @edrevo thanks for reporting! Please don't use issues to ask questions. If you want to ask questions, Gitter is a better place.
  
Bloop should export source dependencies correctly when that option is enabled (which IIRC it's now enabled by default). However, note that support for source dependencies in sbt has always been experimental and buggy in some surreptitious ways, so I cannot guarantee sbt-bloop is doing the right thing here. If you can reproduce in a small sbt build someone could have a look, but my recommendation would be to stop using source dependencies in sbt.
