### ISSUE TITLE
Support for Scala Native 0.4.0-M2

### ISSUE THREAD

**Issue by lolgab** [scalacenter/bloop#1017]
I tried without success to use mill on a Scala Native 0.4.0-M2 project.
Is this support on the roadmap? If you give me some guidance I can try to make a PR.

**Comment by jvican** [comment]
@lolgab You should be able to upgrade the Scala Native version in the build, more concretely in the `Dependencies.scala` file. Make sure you read the docs in the documentation website to get set up and be familiar with the structure of the codebase. However, we won't be able to merge your PR until there's an official stable 4.0 version out.

**Comment by lolgab** [comment]
Can't two versions be supported (stable and milestone) like the thing that happens on Scala.js?
It will take very long time to Scala Native 0.4 be out.. I see if I can open a PR if this scala.js-like cross support is appreciated.

**Comment by lolgab** [comment]
@jvican Are you ok with cross support for 0.3 and 0.4 ? I think it will take more than one year for 0.4.0 to be out, and most people that use Scala Native are using 0.4.0-M2 now because it's much better than 0.3.9, faster and solves some serious bugs..
If you give me the ok I can prepare a PR doing something like the thing you did for Scala.js 0.6.x and 1.0-Mx

**Comment by jvican** [comment]
@lolgab I apologise for my delay responding, I've been in a conference and my access to the Internet has been limited.
  
I think supporting both versions makes sense. I'd welcome a PR on this, thanks for taking it on.

**Comment by lolgab** [comment]
@jvican No problems for the delay. Thank you for accepting the cross support.
You can find the PR for cross support here: https://github.com/scalacenter/bloop/pull/1029

**Comment by jvican** [comment]
Fixed by #1029

**Comment by lolgab** [comment]
Thank you very much 🙏
