### ISSUE TITLE
Allow compilation of files to tmpfs directories

### ISSUE THREAD

**Issue by arbitrary-dev** [scalacenter/bloop#1031]
Please add support for Tmpfs storage for compiled sources.

Currently compiled classes are stored in local `.bloop/` folder:
```
# cat .bloop/project.json

...
   "classesDir" : "/path/.bloop/project/scala-2.12/classes",
...
```

Would be nice to make this destination configurable, so that allow users to utilize Tmpfs for compilation purposes, for example:
```
// cat build.sbt

...
project.settings(
  bloopClassesDir := file(s"/tmp/bloop-project/${ normalizedName.value }"),  
)
...
```

**Comment by jvican** [comment]
With regards to #476: Are you scoping `bloopClassDirectory` to either `Compile` or `Test`? Otherwise it makes sense it doesn't work, you're actually not overriding the existing setting. BTW, you might also need to change `bloopTargetDir`. You can make sure the values are overridden by using `show` or `inspect` in the sbt shell.

**Comment by jvican** [comment]
(Marking as duplicate because I think we are indeed supporting this use case as described in #476, my last comment in that thread seems wrong)

**Comment by jvican** [comment]
Any update @arbitrary-dev ?

**Comment by arbitrary-dev** [comment]
Tried the following...
```
module.settings(
  bloopClassDirectory in Compile := file(s"/tmp/bloop-project/${ normalizedName.value }"),
  bloopTargetDir in Compile := file(s"/tmp/bloop-project/${ normalizedName.value }"),
)
```

Generated JSON configs are correct:
```
$ grep classesDir .bloop/*.json
.bloop/module-1.json:        "classesDir" : "/tmp/bloop-project/module-1",
.bloop/module-2.json:        "classesDir" : "/tmp/bloop-project/module-2",
```

Seems like all the classes are compiled in a couple of folders (though on Tmpfs) and module related ones just remain empty:
```
$ du -hd0 /tmp/bloop-project/*
50M     /tmp/bloop-project/bloop-bsp-clients-classes
50M     /tmp/bloop-project/bloop-internal-classes
0       /tmp/bloop-project/module-1
0       /tmp/bloop-project/module-2
```

Still there are some `*-analysis.bin` files created out of Tmpfs, but not sure if it worth moving them also:
```
$ find .bloop -type f -a -not -iname *.json -exec du -h {} +
16K	.bloop/module-1/module-1-analysis.bin
48K	.bloop/module-2/module-2-analysis.bin
```

**Comment by jvican** [comment]
`bloopAnalysisOut` can help you tweak that too https://github.com/scalacenter/bloop/blob/master/integrations/sbt-bloop/src/main/scala/bloop/integrations/sbt/SbtBloop.scala#L67
  
Happy to hear this works! I'm closing, adding some docs about this in the website would be highly appreciated 👍

**Comment by arbitrary-dev** [comment]
I'm trying to develop a plugin for Bloop SBT integration to compile files in Tmpfs, here's the link:  
https://github.com/arbitrary-dev/sbt-bloop-tmpfs/blob/master/src/main/scala/bloop/integrations/sbt/SbtBloopTmpfs.scala#L21

Here's the error I receive in another project when I try to use this plugin:

>[error] java.lang.NoSuchMethodError: 'sbt.SettingKey bloop.integrations.sbt.BloopKeys$.bloopAnalysisOut()'
>[error]     at bloop.integrations.sbt.BloopTmpfsPlugin$.projectSettings$lzycompute(SbtBloopTmpfs.scala:21)
>[error]     at bloop.integrations.sbt.BloopTmpfsPlugin$.projectSettings(SbtBloopTmpfs.scala:18)
>[error]     at sbt.internal.Load$.$anonfun$resolveProject$3(Load.scala:1033)

But as per v1.3.4 sources, the bloopAnalysisOut option is there:  
https://github.com/scalacenter/bloop/blob/v1.3.4/integrations/sbt-bloop/src/main/scala/bloop/integrations/sbt/SbtBloop.scala#L69

Any suggestions?

**Comment by arbitrary-dev** [comment]
I guess it's due to Metals use a different version of Bloop server…
>INFO Connected to Build server v1.4.0-RC1+33-dfd03f53

**Comment by arbitrary-dev** [comment]
But `bloopAnalysisOut` is stil there:  
https://github.com/scalacenter/bloop/blob/dfd03f5333c2fc292db78bfcd4205a0cdd828967/integrations/sbt-bloop/src/main/scala/bloop/integrations/sbt/SbtBloop.scala#L210

**Comment by arbitrary-dev** [comment]
Also `classesDir` isn't respected…
```
$ grep classesDir .bloop/*.json
.bloop/scala-playground-test.json:        "classesDir": "/tmp/man/.bloop/8bf0833d/scala-playground/test-classes",
.bloop/scala-playground.json:        "classesDir": "/tmp/man/.bloop/8bf0833d/scala-playground",
$ find .bloop -iname *.class | wc -l
20
$ du -hs /tmp/man/.bloop/8bf0833d
0	/tmp/man/.bloop/8bf0833d
```
