### ISSUE TITLE
Should bloop remove old projects when doing install?

### ISSUE THREAD

**Issue by Duhemm** [scalacenter/bloop#104]
Steps:
 - I run `installBloop`
 - I remove a project from my `build.sbt`
 - I re-run `installBloop`

Problem:
 - The configuration file for the old project is still there

Question:
 - Should bloop remove all the existing configuration files when doing `bloopInstall`?

**Comment by olafurpg** [comment]
I personally think for now it's best to delegate this to users with `rm -rf .bloop-config`. I like the fact that I can incrementally update the config for one project.

**Comment by jvican** [comment]
I think it should indeed be removed. Otherwise, users can still see how bloop is trying to compile their projects if the dependencies are maintained. That's bad.

**Comment by olafurpg** [comment]
Yeah you're probably right, `install` is fast anyways so it's probably best to clean up `.bloop-config` to avoid staleness issues

**Comment by jvican** [comment]
Note we can still accomplish the goal in this ticket while staying incremental :smile:.

**Comment by olafurpg** [comment]
> I like the fact that I can incrementally update the config for one project.

I take back my comment, I think `bloopInstall` should overwrite old configurations.

**Comment by jastice** [comment]
This has been causing confusion and errors for me. Especially when upgrading bloop, some of the old files still being there caused problems because they were incompatible.
