### ISSUE TITLE
Install link from main website is broken

### ISSUE THREAD

**Issue by KenCoder** [scalacenter/bloop#1054]
At 10/6/2019 10:10AM EST, running the [universal installer](https://scalacenter.github.io/bloop/setup#universal) gets a 404. 

The failing command is: 

curl -L https://github.com/scalacenter/bloop/releases/download/v1.3.3+16-a63edbcb/install.py | python

**Comment by jvican** [comment]
Thanks for reporting! There has been a change in the website infrastructure and the version is off. Could you please replace that version with `1.3.3`? The installation should then work.
