### ISSUE TITLE
Support debugging breakpoints in Bloop

### ISSUE THREAD

**Issue by jvican** [scalacenter/bloop#1057]
This ticket collects my thoughts on how we can implement breakpoint support in Bloop, what are the different implementation avenues, their pros/cons and specifies what is the relationship between Bloop as a DAP server and BSP clients.
  
### Constraints
  
1. Breakpoint support should not depend on information from the BSP/DAP frontends unless it's strictly necessary.
2. Bloop should handle breakpoints in user code as well as third-party dependencies for both Java and Scala source code.
3. This design document doesn't explore supporting fancy breakpoints that allow to evaluate expressions upon hits.
4. Exception breakpoints are outside the scope of this document (and they are already supported in the current implementation if the BSP/DAP frontend allows the user to set them).

### Implementation walkthrough
  
To implement *basic* breakpoint support in [`java-debug`](https://github.com/microsoft/java-debug), we must implement the `getFullyQualifiedName` method of the `ISourceLookupProvider`. This method maps a `(source uri, source position)` to a set of fully qualified names. These fully qualified names are then used by the java-debug implementation to look at all the loaded classes in the JDI `VirtualMachine` and set a breakpoint in them by resolving the source positions with the `LineNumberTable` and `SourceFile` information (documented [here](https://docs.oracle.com/javase/specs/jvms/se7/html/jvms-4.html#jvms-4.7.10)).
  
There are two important kind of URIs we need to support in `getFullyQualifiedName`:
  
1. Source file URIs located in the user workspace.
1. Source file URIs coming from a library dependency.
  
BSP clients such as Metals and IntelliJ might differ on how they present to us sources coming from binary dependencies. This might be an important detail to drive the implementation. For example, Metals will give us an actual file URI living under `$WORKSPACE/.metals/readonly` while IntelliJ might give us another kind of URI format.
  
### Finding FQNs for workspace sources
  
Implementing FQNs for workspace sources can be done through some of the information we host in the Zinc analysis file. The Zinc analysis file contains a mapping between source files and a list of the class files names generated from that source.
  
We have this information because Zinc has compiled the projects before debugging. This information is reliable and thus we can use it to power `getFullyQualifiedName`.

### Finding FQNs for third-party dependency sources
  
Mapping sources from third-party dependency sources to FQNs is more complicated. Given that we don't compile these projects, we don't have the Zinc mapping between sources and class file names. Heuristics such as relying on the source file path can only be used for Java source files, not Scala source files.
  
My first idea to support this feature was to map the source file URI to one of the jars that bloop has in the resolution information, open the jar, traverse all classes, read the `SourceFile` class file attribute and match it with a subpath of the target source URI. Performance considerations aside, the big impediment to support third-party sources this way is that frontends such as Metals uncompress the third-party source in the `.metals/readonly` directory and we don't have a way to trace it back to the sources jar that Bloop handed in to Metals.
  
If we zoom out for a bit, we realise that supporting breakpoint sources of third-party dependencies only makes sense in the context of a frontend such as IntelliJ or Metals. These frontends are the ones that allow users to navigate these sources in the first place and therefore are responsible of how they're handled. After some thinking, it makes sense that Bloop doesn't support this feature without "some help" from the frontends.
  
#### Communicating with the DAP/BSP frontend
  
The best way the frontend could simplify our job would be if it would find the FQN mapped to a source file uri and source position on its own. Then, the frontend can send the resolved URI as a source target URI with a specific format that we could teach `getFullyQualifiedName` to understand and thus extract the candidate class file names.
  
This format could look something like this: `metals://dap?fqn=$FQN_NAME`. We could even have Metals pass us this same URI to avoid using the information from the zinc analysis file assuming this information is easy to compute on the Metals side.
  
Bloop would fallback on the zinc analysis-based implementation in case this information is not provided. This information could not be provided if there was a bug in Metals or if the target source URI was a java file instead of a Scala file. Given that Metals doesn't have a presentation compiler for Java files, Bloop could instead figure out the mapping between the source and the FQN on its own by deriving the FQN from its source target URI path (in Java, the directory structure matches the package structure an the file name matches the defined Java symbol).
  
### Wrap-up
  
I believe the approach proposed in this document is the most appropriate given the design constraints and has a low implementation overhead. I have a prototype making breakpoint support work in Bloop but we will need to implement the communication mentioned above to have it work in all scenarios.
  
/cc @marek1840 @olafurpg

**Comment by olafurpg** [comment]
Thank you for the detailed write-up! Metals is able to provide the mapping between source file + position to a fully qualified name. Do I understand correctly that Metals DAP proxy would update the `setBreakpoints` parameters before passing it onto Bloop?

**Comment by jvican** [comment]
Yes, Metals would update the `path` field in the `Source` field of the `SetBreakpointArguments`. `java-debug` considers that to be a URI that we then will parse.
  
We should use an URI format that is not Metals specific but instead can also be used by other frontends such as IntelliJ. I propose `bloop://dap?fqn=$FQN_NAME` as this format is for now only supported in bloop.
  
/cc @marek1840

**Comment by jvican** [comment]
Fixed by #1087.
