### ISSUE TITLE
Use linker version set in Bloop configuration

### ISSUE THREAD

**Issue by tindzk** [scalacenter/bloop#1062]
When a library was compiled with a newer Scala.js version than the [one](https://github.com/scalacenter/bloop/blob/master/project/Dependencies.scala#L43) used by Bloop, the module cannot be linked.

For example, https://github.com/sparsetech/toml-scala/pull/16 fails as it updates ScalaCheck from 1.14.0 to 1.14.2 which was compiled for Scala.js 0.6.29, however the linker version used by Bloop is 0.6.28. From the [CI log](http://ci.sparse.tech/sparsetech/toml-scala/67/1/2):

> [E] JavaScript linking failed with 'Failed to deserialize info of file compiled with Scala.js 0.6.29 (supported: 0.6.0, 0.6.13, 0.6.3, 0.6.17, 0.6.4, 0.6.6, 0.6.14, 0.6.8, 0.6.5, 0.6.15): /drone/src/build/bloop/toml-js-test/toml/CodecSpec$$anonfun$75$Root$101.sjsir' 

In any case, the linker version set in the Bloop configuration should be honoured as this would allow users to downgrade in case of regressions.

**Comment by jvican** [comment]
Hi @tindzk, how do you expect this to work? An actionable thing out of this ticket is to upgrade to the latest Scala.js version, however I'm not sure how you envision Bloop would behave here.

**Comment by tindzk** [comment]
It should be possible to resolve the linker during runtime. [This](https://github.com/lihaoyi/mill/blob/master/scalajslib/src/ScalaJSModule.scala#L38) is how Mill does it.

**Comment by jvican** [comment]
Could you look into how we can use a similar trick in bloop?

**Comment by tindzk** [comment]
Yes, I will try to come up with something in the next few days.

**Comment by jvican** [comment]
Great! Let me know how you want to implement this, I'm curious to know how you're thinking about this and would like to provide some early feedback.

**Comment by tindzk** [comment]
Unfortunately, I did not manage to run the test cases yet. I checked out the latest `master` and ran these commands as per the [documentation](https://scalacenter.github.io/bloop/docs/contributing-guide#learn-the-developer-workflow):

```shell
sbt bloopInstall
bloop test frontend -o bloop.JsTestSpec
```

The [output](https://gist.github.com/tindzk/17e5c610420d92650a43acad922b67e4) indicates that the bridge is missing.

Here are the changes I would like to make:
- Use the `provided` scope for linker artefacts in `Dependencies.scala`
- In `fromConfig` (`Project.scala`), the `resolveToolchain()` calls should include the platform version
- Change `resolveJars()` in `ToolchainCompanion.scala` to resolve additional artefacts

**Comment by jvican** [comment]
You need to publish the js bridges manually every time you make a change in them or the version of the build changes (which happens roughly every time you reload the sbt shell or quit it).
