### ISSUE TITLE
The nailgun script is only compatible with Python 2

### ISSUE THREAD

**Issue by strobe** [scalacenter/bloop#107]
got following error when tried to use bloop cli
```
% bloop projects
  File "/Users/evgeniy/.bloop/bloop-ng.py", line 245
    self.sockpath = ur'\\.\pipe\{0}'.format(sockpath)
                                   ^
SyntaxError: invalid syntax
```
seems reason for that 3x python installed on system as default python version  
```
% python --version
Python 3.6.3 :: Anaconda, Inc.
```
It works well after downgrade to 2.7 by `conda install python=2.7`

**Comment by jvican** [comment]
You can only use it with Python 2. The nailgun team at Facebook wants it this way, and we borrow the script from them.

**Comment by jvican** [comment]
By the way, note that you can execute it with `python2 ${PATH_TO_SCRIPT}`, :wink:.

**Comment by jvican** [comment]
It's been fixed upstream, we'll be upgrading our nailgun integration soon https://github.com/facebook/nailgun/pull/128/files. WIP PR https://github.com/scalacenter/bloop/pull/293.
