### ISSUE TITLE
Make forker aware of JDI hardcoded '\n' message

### ISSUE THREAD

**Issue by marek1840** [scalacenter/bloop#1072]
Currently, the output from the JVM is being split into lines using the `System.lineSeparator` as a separator. 

Unfortunately, this stopped being a correct approach with the [introduction of a Debug Adapter Protocol](https://github.com/scalacenter/bloop/pull/944) where we depend on a first line from the JVM - a JDI notification telling us when we can attach to the debuggee. 

Regrettably, the JVM itself uses [hardcoded unix-style newline](https://hg.openjdk.java.net/jdk8/jdk8/jdk/file/687fd7c7986d/src/share/back/error_messages.c#l119) when [sending the desired notification](https://hg.openjdk.java.net/jdk8/jdk8/jdk/file/687fd7c7986d/src/share/back/transport.c#l508). It makes the debugging [not working on Windows](https://github.com/scalameta/metals/issues/1021) because of a deadlock:
1. we are waiting for `\r\n` to break the first line and attach to the debuggee
2. the debuggee cannot produce more output, since it is suspended until we attach to it

**Comment by jvican** [comment]
Fixed with #1073
