### ISSUE TITLE
Compiler bridge resolution blocks CLI

### ISSUE THREAD

**Issue by tindzk** [scalacenter/bloop#1077]
After [updating Bloop](https://github.com/tindzk/seed/pull/64) from v1.3.2 to v1.3.4, Seed's integration tests stopped working.

The two failed CI runs ([1](http://ci.sparse.tech/tindzk/seed/444/1/3), [2](http://ci.sparse.tech/tindzk/seed/445/1/3)) both block on the first `bloop compile <module>` command during the compiler bridge resolution:

```shell
[D] Read-only classes directory /tmp/seed3630563884690033698/meta-module/build/bloop/classes-empty-example-js
[D] New rw classes directory /tmp/seed3630563884690033698/meta-module/build/bloop/bloop-internal-classes/example-js-BgYTCnGgTUiUlzKIq0Qvcg==
[D] No previous setup found, invalidating everything.
[D] No previous setup found, invalidating everything.
[D] Full compilation, no sources in previous analysis.
[D] Full compilation, no sources in previous analysis.
[D] All sources are invalidated.
[D] Initial set of included nodes:
[D] All sources are invalidated.
[D] Initial set of included nodes:
[D] Recompiling all sources: number of invalidated sources > 50.0% of all sources
[D] Recompiling all sources: number of invalidated sources > 50.0% of all sources
[D] Resolving ch.epfl.scala:compiler-bridge_2.12:1.3.0-M4+26-045d2c8c 
```

In case it helps, [here](https://github.com/tindzk/seed-meta-module-test) is the generated Bloop project from a local test suite run.

This issue might be related to: https://github.com/scalacenter/bloop/issues/799

**Comment by jvican** [comment]
Thanks for opening the ticket! This issue was fixed in v1.3.5 (which hasn't yet been officially released but which can be resolved from the CI) and it's also fixed in master. Next official release will advertise that we fixed this bug.

**Comment by tindzk** [comment]
Great to hear.

Where are the latest builds published? I have checked [Bintray](https://bintray.com/scalacenter/releases/bloop), but there have not been any artefacts since v1.3.3.

**Comment by jvican** [comment]
Stable releases go to https://search.maven.org/artifact/ch.epfl.scala/bloop-frontend_2.12/1.3.5/jar. Binary has been dormant since we've done some changes in our build, I plan to add on-merge releases back soon.
