### ISSUE TITLE
Bloop doesn't build on Windows + PowerShell

### ISSUE THREAD

**Issue by jackkoenig** [scalacenter/bloop#1080]
I never develop on Windows so apologies if I'm missing something obvious.

I tried following the developer instructions (https://scalacenter.github.io/bloop/docs/contributing-guide) on Windows 10 and got the following error when running `sbt` in PowerShell. I got the same error when trying to import `bloop` into IntelliJ using `sbt`.

```
[success] Generated .bloop\bloop-build.json
[success] Total time: 48 s, completed Nov 5, 2019, 10:07:30 PM
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[info] Loading settings for project bloop from build.sbt ...
[info] Loading settings for project benchmark-bridge-build from plugins.sbt ...
[info] Loading project definition from C:\Users\Jack\bloop\benchmark-bridge\project
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[info] Loading settings for project benchmark-bridge from build.sbt ...
[info] Resolving key references (32351 settings) ...
[info]       _____            __         ______           __
[info]      / ___/_________ _/ /___ _   / ____/__  ____  / /____  _____
[info]      \__ \/ ___/ __ `/ / __ `/  / /   / _ \/ __ \/ __/ _ \/ ___/
[info]     ___/ / /__/ /_/ / / /_/ /  / /___/ /__/ / / / /_/ /__/ /
[info]    /____/\___/\__,_/_/\__,_/   \____/\___/_/ /_/\__/\___/_/
[info]
[info]    ***********************************************************
[info]    ***       Welcome to the build of `loooooooooop`        ***
[info]    ***        An effort funded by the Scala Center         ***
[info]    ***********************************************************
[info]
[info] Generating bloop configuration files for C:\Users\Jack\bloop\frontend\src\test\resources\compiler-plugin-whitelist

C:\Users\Jack\bloop\frontend\src\test\resources\compiler-plugin-whitelist>#!/bin/sh
'#!' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Jack\bloop\frontend\src\test\resources\compiler-plugin-whitelist>MSYS2_ARG_CONV_EXCL=/C cmd.exe /C "C:\Users\Jack\scoop\apps\sbt\current\bin\sbt.bat"  "$@"
'MSYS2_ARG_CONV_EXCL' is not recognized as an internal or external command,
operable program or batch file.
[error] Failed to generate bloop config for C:\Users\Jack\bloop\frontend\src\test\resources\compiler-plugin-whitelist.
```

I installed `sbt` using `scoop` per the SBT instructions: https://www.scala-sbt.org/1.x/docs/Installing-sbt-on-Windows.html. It looks like bloop is trying to use a shebang and standard Unix shell command which Windows just doesn't understand.

**Comment by jvican** [comment]
Thanks for reporting @jackkoenig! It looks like the offending line is https://github.com/scalacenter/bloop/blob/master/project/BuildPlugin.scala#L447
  
I'm not sure why it's not using the Windows command, I wonder if this is related to PowerShell even though I used it a few weeks ago and worked fine.

**Comment by jvican** [comment]
Any update here? @jackkoenig

**Comment by jackkoenig** [comment]
Thanks for the response! No update yet, hoping to take a deeper look soon. I appreciate the pointer, that is almost certainly the offending line so debugging shouldn't be too bad.

For posterity, since master has already moved, here's a permalink: https://github.com/scalacenter/bloop/blob/f8402c3d47cd6ec6215ad39e554598a6b9caef4a/project/BuildPlugin.scala#L460

**Comment by jackkoenig** [comment]
It appears the issue I originally reported comes from installing `sbt` via `scoop`. I noticed that I got a very similar error trying to run `sbt` from `cmd.exe` (rather than PowerShell):
```
C:\Users\Jack\bloop>sbt
C:\Users\Jack\bloop>#!/bin/sh
'#!' is not recognized as an internal or external command,
operable program or batch file.
C:\Users\Jack\bloop>MSYS2_ARG_CONV_EXCL=/C cmd.exe /C "C:\Users\Jack\scoop\apps\sbt\current\bin\sbt.bat"  "$@"
'MSYS2_ARG_CONV_EXCL' is not recognized as an internal or external command,
operable program or batch file.
```
So I uninstalled `sbt` from `scoop` and reinstalled it with the `.msi` and was able to get passed that error.

**Comment by jvican** [comment]
Sounds good! Let's close this then.
