### ISSUE TITLE
Passing JVM options to test throws unrecognised option

### ISSUE THREAD

**Issue by pkolaczk** [scalacenter/bloop#1082]
```
bloop test dse-db -- -J-Xmx1024M
[E] Unrecognized option: -J-Xmx1024M
[E] Error: Could not create the Java Virtual Machine.
[E] Error: A fatal exception has occurred. Program will exit.
===============================================
Total duration: 0ms
No test suites were run.
===============================================
```

`-J` prefix is not stripped?

**Comment by jvican** [comment]
Thanks for reporting! This kind of ticket needs more information to be actionable. What's the Bloop version you're using? How did you build bloop?

**Comment by pkolaczk** [comment]
Bloop v1.3.4 + a few minor remaining patches not merged yet; but not related to code running tests. I also remember someone reporting the same problem in scalacenter gitter.

**Comment by jvican** [comment]
Thanks for the info, I'll look into this shortly.
