### ISSUE TITLE
Add an option to control downloading javadocs / sources 

### ISSUE THREAD

**Issue by pkolaczk** [scalacenter/bloop#1092]
It looks like currently `bloopInstall` gradle task downloads sources and javadocs for all resolved jars. This takes a significant amount of time, particularly when everything is proxied through another maven repo that doesn't have these jars cached.

Could we get an option to configure downloading of these additional jars? E.g make it similar to other plugins:
```
bloop {
   module {
     downloadSources = false
     downloadJavadoc = false
  }
}

**Comment by tgodzik** [comment]
This is being currently done here: https://github.com/scalacenter/bloop/blob/e8ec4d7ce6db36417e300ae114de823b4474d6f1/integrations/gradle-bloop/src/main/scala/bloop/integrations/gradle/model/BloopConverter.scala#L586

It might make sense to configure via project property. Something like `-PbloopIncludeSource=true`

**Comment by pkolaczk** [comment]
Right. How do you set custom project properties (that would not be overriden by `bloopInstall`) ?

**Comment by tgodzik** [comment]
> Right. How do you set custom project properties (that would not be overriden by `bloopInstall`) ?

Not sure I understand. Custom project properties can be provided when running `bloopInstall`

So we would run:
```
gradle bloopInstall -PbloopIncludeSource=true
```

and by default we would only download the regular jars.

**Comment by jvican** [comment]
Downloading sources is usually a must to get IDE support working nicely, I'm not sure if it makes a lot of sense to disable them. I agree downloading java docs is not very useful and I'm open to switching the default to avoid downloading them when `gradle bloopInstall` is run. Does that make sense?

**Comment by pkolaczk** [comment]
Makes sense, thank you.
Any way to provide the defaults in `build.gradle` though? 
The default on our gradle project is to *not* download the sources and javadocs. So I'd like this to be opt-in (by -P or gradle.properties) rather than opt-out.

**Comment by jvican** [comment]
We could definitely have an option for that, feel free to open a PR. I don’t mind having that option customizable via system properties or via gradle build files.

**Comment by jvican** [comment]
Fixed by @1137
