### ISSUE TITLE
IDEA bsp plugin doesn't seem to respect setting "Automatically show first error in editor"

### ISSUE THREAD

**Issue by andywhite37** [scalacenter/bloop#1096]
I'm not sure if this is the right place to ask about the IDEA plugin, so I can close/move this if needed.

The IDEA plugin for bsp doesn't seem to honor the IDEA setting "Automatically show first error in editor," when that option is **unchecked**.

I have this setting unchecked, yet when a build finishes, and there's an error, I'm taken to the file containing that error, and away from the file I'm working on.  Is there another setting that might control this behavior that I'm missing?

![image](https://user-images.githubusercontent.com/274734/68872996-24d86080-06bc-11ea-8bb3-5a10cd112afb.png)

**Comment by jvican** [comment]
Hi @andywhite37, thanks for reporting! This is not the right place to report this behavior since bloop doesn’t control this code, it's better to move this ticket to IntelliJ's issue tracker. See @jastice
