### ISSUE TITLE
Website is showing old "latest" release versions

### ISSUE THREAD

**Issue by propensive** [scalacenter/bloop#1104]
The website shows version 1.3.2 as the "latest" version throughout the site, and in particular here:
https://scalacenter.github.io/bloop/versions

**Comment by jvican** [comment]
Thanks for reporting! I'm aware of this bug. I'll fix it before the next release. You can select "latest master" to see the most up-to-date docs from the master branch.

**Comment by olafurpg** [comment]
The website shows the latest nightly release now, which is 1.3.4+251-1d81dfe5 from #1111 

https://scalacenter.github.io/bloop/setup
