### ISSUE TITLE
Bloop restarts automatically after having been killed by user

### ISSUE THREAD

**Issue by odisseus** [scalacenter/bloop#1107]
## Steps to reproduce

1. Install Bloop 1.3.5 using the [script](https://scalacenter.github.io/bloop/setup#universal).
2. Open a terminal and run `bloop server`.
3. Open another terminal and run `bloop about` to make sure the server is up and running.
4. Kill the process that belongs to the server.

**Expected behaviour:** the server stops working
**Actual behaviour:** the server stops, but another instance is immediately started

#### After start
```
Defaulting on nailgun port 8212
There is no server running at port 8212
Starting the bloop server... this may take a few seconds
Running ~/local/bloop/blp-server as a jar...
Shelling out with '['java', '-jar', '~/local/bloop/blp-server']' ...
Unable to load nailgun-version.properties.
NGServer [UNKNOWN] started on address localhost/127.0.0.1 port 8212.
```
#### After first kill
```
Running ~/local/bloop/blp-server as a script...
Shelling out in Unix system with ['sh', '~/local/bloop/blp-server']
Unable to load nailgun-version.properties.
NGServer [UNKNOWN] started on address localhost/127.0.0.1 port 8212.
```
#### After second kill
```
Bloop server in /home/virtuslab/local/bloop/blp-server failed to run.
First invocation attempt: ['java', '-jar', '~/local/bloop/blp-server']
-> Return code: 143
Second invocation attempt: ['sh', '~/local/bloop/blp-server']
-> Return code: 143
```

## My thoughts on the matter
From what I gather, the intent of the launcher is to try a different way of launching the server if the preferred way doesn't work. However, this intent does not apply if the server is killed by the user, and especially not if the server was successfully launched and has worked for some time.

I suggest that the launcher should have a way to tell whether the server failed to launch or terminated after a successful launch. In the latter case, the server should not be restarted automatically.

**Comment by jvican** [comment]
> Expected behaviour: the server stops working
Actual behaviour: the server stops, but another instance is immediately started

Yes, this is a side-effect of the current implementation -- it's an insidious bug. This will be fixed soon because the python script used by `bloop about` will be gone by our own bloopgun version.
  
I'll keep this ticket open until I've done the switch between the two.
