### ISSUE TITLE
Unexpected color when --no-color flag is used

### ISSUE THREAD

**Issue by chessman** [scalacenter/bloop#1119]
bloop 1.3.4
```
bloop compile root --no-color
Compiling root (8 Scala sources)
[W]  [E-1] there was one feature warning; re-run with -feature for details
[W]  [E-1] there was one deprecation warning (since 2.11.0); re-run with -deprecation for details
Compiled root (905ms)
Compiling root (5 Scala sources)
[E] [E1] root/src/main/scala/.../File.scala:23:99
...
[E]      L23: [some error]
[E]                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[W]  [E-1] there was one feature warning; re-run with -feature for details
[W]  [E-1] there was one deprecation warning (since 2.11.0); re-run with -deprecation for details
[E] root/src/main/scala/.../File.scala: L23 [E1]
```
E-1, E1 are blue
L23 is red

**Comment by jvican** [comment]
Thanks for opening the ticket! We don't actually check that we respect `--no-color` in our tests so this behavior might have regressed. I don't think I'll have time to work on this. Is this something you'd be interested in picking up?

**Comment by chessman** [comment]
Sure. I'll try to have a look.

**Comment by jsatk** [comment]
I'm still getting this error locally. I'm on `1.4.0-RC1-105-118a551b`.

**Comment by jsatk** [comment]
Ah. Looks like commit https://github.com/scalacenter/bloop/pull/1120 hasn't been released yet?

**Comment by jvican** [comment]
What version are you using? 1.4.0-RC1 should have that commit

**Comment by jsatk** [comment]
Version: `1.4.0-RC1-105-118a551b`
The command I'm running (with some sensitive information edited out):
```
$ bloop test project -o com.company.project.packageSpec --no-color
```

**Comment by Duhemm** [comment]
Indeed, the line numbers in the reporter are still colored, and so can be the output of the test frameworks. I'll take a look.
