### ISSUE TITLE
Reduce overhead from debug logging in BloopLookup 

### ISSUE THREAD

**Issue by olafurpg** [scalacenter/bloop#1126]
While testing out Bloop, I noticed that calls to `pprint.apply` were appearing in profiling logs

<img width="1214" alt="Screenshot 2019-12-17 at 10 23 05" src="https://user-images.githubusercontent.com/1408093/70987223-5a0b1080-20b7-11ea-8a61-59e62003a904.png">

These lines here could be guarded so that they only run when debugging is enabled.

https://github.com/scalacenter/bloop/blob/2c6ff97151390c7bde56a5e7d0c6a1e7d67f4414/backend/src/main/scala/sbt/internal/inc/bloop/internal/BloopLookup.scala#L28-L31

**Comment by jvican** [comment]
Good idea, please feel free to send a PR to fix this issue.
