### ISSUE TITLE
Unexpected `Nail raised unhandled exception` when using systemd

### ISSUE THREAD

**Issue by LLCampos** [scalacenter/bloop#1128]
I can run bloop ok when starting the server manually:

```sh
lcampos:~/Development$ bloop server
Defaulting on nailgun port 8212
There is no server running at port 8212
Starting the bloop server... this may take a few seconds
Running /home/lcampos/.bloop/blp-server as a jar...
Shelling out with '['java', '-jar', '/home/lcampos/.bloop/blp-server']' ...
Unable to load nailgun-version.properties.
NGServer [UNKNOWN] started on address localhost/127.0.0.1 port 8212.
```

```sh
lcampos:~$ bloop about
bloop v1.3.4

Using Scala v2.12.8 and Zinc v1.3.0-M4+26-045d2c8c
Running on Java JDK v1.8.0_222 (/usr/lib/jvm/java-8-openjdk-amd64/jre)
  -> Supports debugging user code, Java Debug Interface (JDI) is available.
Maintained by the Scala Center (Martin Duhem, Jorge Vicente Cantero)
```

But it fails when run through `systemd`:

I start bloop server:
```sh
lcampos:~/Development$ systemctl --user start bloop
lcampos:~/Development$ systemctl --user status bloop
● bloop.service - Bloop Scala build server
   Loaded: loaded (/home/lcampos/.bloop/systemd/bloop.service; enabled; vendor preset: enabled)
   Active: active (running) since Ter 2019-12-17 15:56:58 WET; 6s ago
 Main PID: 28973 (python)
   CGroup: /user.slice/user-1000.slice/user@1000.service/bloop.service
           ├─28973 python /home/lcampos/.bloop/bloop server
           └─28976 java -jar /home/lcampos/.bloop/blp-server

Dez 17 15:56:58 lcampos-GL552VX systemd[4124]: Started Bloop Scala build server.
Dez 17 15:56:58 lcampos-GL552VX bloop[28973]: Unable to load nailgun-version.properties.
Dez 17 15:56:58 lcampos-GL552VX bloop[28973]: NGServer [UNKNOWN] started on address localhost/127.0.0.1 port 8212.
lcampos:~/Development$ journalctl --user-unit bloop
(...)
Dez 17 15:56:58 lcampos-GL552VX systemd[4124]: Started Bloop Scala build server.
Dez 17 15:56:58 lcampos-GL552VX bloop[28973]: Unable to load nailgun-version.properties.
Dez 17 15:56:58 lcampos-GL552VX bloop[28973]: NGServer [UNKNOWN] started on address localhost/127.0.0.1 port 8212.
```

Nothing happens when I try to run a bloop command:

```sh
lcampos:~/Development$ bloop about
lcampos:~/Development$ 
```

And this shows up in the logs:

```sh
lcampos:~/Development$ journalctl --user-unit bloop
(...)
Dez 17 15:56:58 lcampos-GL552VX systemd[4124]: Started Bloop Scala build server.
Dez 17 15:56:58 lcampos-GL552VX bloop[28973]: Unable to load nailgun-version.properties.
Dez 17 15:56:58 lcampos-GL552VX bloop[28973]: NGServer [UNKNOWN] started on address localhost/127.0.0.1 port 8212.
Dez 17 15:58:32 lcampos-GL552VX bloop[28973]: Nail raised unhandled exception
```

The service config:

```sh
lcampos:~$ cat ~/.bloop/systemd/bloop.service 
[Unit]
Description=Bloop Scala build server

[Service]
ExecStart=/home/lcampos/.bloop/bloop server
StandardOutput=journal
StandardError=journal
SyslogIdentifier=bloop

[Install]
WantedBy=default.target
```

**Comment by jvican** [comment]
Thanks for reporting @LLCampos, first time I see that exception. What java version are you running? Make sure you do `java -version` in the running Systemd service. It's often the case that the Java version used in your terminal doesn't match the one used in Systemd, because the latter has no access to any customizations you might have done in `.bashrc` or `.zshrc` et al.

**Comment by LLCampos** [comment]
```bash
lcampos:~/Desktop$ java -version
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-8u222-b10-1ubuntu1~16.04.1-b10)
OpenJDK 64-Bit Server VM (build 25.222-b10, mixed mode)
```

From running  `java -version` before `/home/lcampos/.bloop/bloop server`, it seems that `systemd` it's running the same Java version as the terminal.

**Comment by jvican** [comment]
> it seems that systemd it's running the same Java version as the terminal.

Please do double check that the java version used by systemd is the same. This is a weird error and  if Nailgun is complaining there should be something fundamentally broken. Another way to investigate what's happening is to double check if there are permission issues connecting to a port started by another user or something like that (throwing out ideas, i really have no idea what we're looking for).

**Comment by LLCampos** [comment]
Thanks for the help, @jvican. :)

Problem persists even if I have the following in `service` file:

```service
[Unit]
Description=Bloop Scala build server

[Service]
ExecStart=/usr/bin/java -jar /home/lcampos/.bloop/blp-server
StandardOutput=journal
StandardError=journal
SyslogIdentifier=bloop

[Install]
WantedBy=default.target
```

It works ok if I run `/usr/bin/java -jar /home/lcampos/.bloop/blp-server` manually on the terminal. 

Using `ps`, I can see that in both situations the process is being run by the same user.

> Another way to investigate what's happening is to double check if there are permission issues connecting to a port started by another user or something like that (...)

Not sure how to do this?

Anyway, since this is not working, might just use other method to start `bloop server` on start up.

**Comment by jvican** [comment]
Unfortunately not, I'd need to check StackOverflow or something. However, I think we should get some more information from Nailgun to figure out what it's really going on here. Can you follow these steps?
  
1. Set up bloop by following the contributing guide
1. Clone scalacenter/nailgun
1. Grep for that exception name in the nailgun repo and instrument the call-site to give us more information about what's happening on the nailgun server
1. Publish locally `nailgun-server` with the nailgun sbt build 
1. Update the nailgun version (not the commit) that bloop uses in `project/Dependencies.scala`
1. Publish bloop locally by running `sbt install` in the bloop repo. After it runs, an AUR formula will be generated if you use Arch otherwise you can use `frontend/target/install.py` manually

**Comment by LLCampos** [comment]
Ok, so, followed the above. Here goes the stack trace of the "unhandled exception" being raised by nailgun:

```
java.lang.NullPointerException
	at java.util.Hashtable.put(Hashtable.java:460)
	at java.util.Properties.setProperty(Properties.java:166)
	at java.lang.System.setProperty(System.java:796)
	at bloop.util.ProxySetup$.$anonfun$updateProxySettings$2(ProxySetup.scala:120)
	at bloop.util.ProxySetup$.$anonfun$updateProxySettings$2$adapted(ProxySetup.scala:114)
	at scala.Option.foreach(Option.scala:274)
	at bloop.util.ProxySetup$.$anonfun$updateProxySettings$1(ProxySetup.scala:114)
	at bloop.util.ProxySetup$.$anonfun$updateProxySettings$1$adapted(ProxySetup.scala:111)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at bloop.util.ProxySetup$.updateProxySettings(ProxySetup.scala:111)
	at bloop.Cli$.run(Cli.scala:284)
	at bloop.Cli$.run(Cli.scala:242)
	at bloop.Cli$.nailMain(Cli.scala:89)
	at bloop.Cli.nailMain(Cli.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.martiansoftware.nailgun.NGSession.run(NGSession.java:281)
```

**Comment by LLCampos** [comment]
Been investigating what's difference between running manually on terminal vs. using systemd.

When running manually, `settingsMap` is non-empty [this case applies](https://github.com/scalacenter/bloop/blob/master/frontend/src/main/scala/bloop/util/ProxySetup.scala#L118). When using systemd, `settingsMap` is empty and this is [run](https://github.com/scalacenter/bloop/blob/master/frontend/src/main/scala/bloop/util/ProxySetup.scala#L120). It's also from this call that the exception is raised. When commenting [this line](https://github.com/scalacenter/bloop/blob/master/frontend/src/main/scala/bloop/Cli.scala#L287), running from systemd works as expected. 

`settingsMap` comes from [here](https://github.com/scalacenter/bloop/blob/master/frontend/src/main/scala/bloop/util/ProxySetup.scala#L16). So, my guess is that there is some difference in the JVM envs when running on terminal vs. systemd. Still, things shouldn't fail when `settingsMap` is empty? My understanding is that if `settingsMap` is empty *and* environment variables [don't contain proxy settings](https://github.com/scalacenter/bloop/blob/master/frontend/src/main/scala/bloop/util/ProxySetup.scala#L138), the exception will be raised.

**Comment by jvican** [comment]
Thanks for all of the digging @LLCampos 

> Still, things shouldn't fail when settingsMap is empty? 

Yes, things shouldn't fail if that's the case. Mind sending a PR to fix this?

**Comment by LLCampos** [comment]
Yeah, I'll prepare something when I have the time. :)
