### ISSUE TITLE
Be able to compile scala code with different jvms

### ISSUE THREAD

**Issue by countfloyd** [scalacenter/bloop#1130]
When compiling java code, the platform jvm is used to fork a java compiler of the correct version. I think it would be great to have a similar mechanism for compiling scala code. 
My use case is that I have scala projects that need to be compiled against the java 11 standard library and some projects that are compiled against the java 8 standard library. Compiling all scala files with the java 8 jvm results in errors when methods in the java 11 standard library are not found.
Maybe we could use the platform jvm for compiling scala code or come up with a different setting for that?

**Comment by countfloyd** [comment]
Attaching bloop output of compiling a java 13 scala project with bloop. Errors indicate java methods not found in the java 8 standard library.

[output.txt](https://github.com/scalacenter/bloop/files/3979826/output.txt)

**Comment by jvican** [comment]
Hi @countfloyd thanks for opening this feature request. The reality is that implementing this is not trivial, would require large changes in pretty much all the project, and I believe most of the times one can find ways to rearchitect their builds to avoid having dependencies to different JVMs. For those reasons, i'm going to mark this ticket as wontfix for now at least.
