### ISSUE TITLE
Debug messages are shown

### ISSUE THREAD

**Issue by tindzk** [scalacenter/bloop#1132]
After upgrading to v1.4.0-RC1, Bsp debug messages started being sent to stderr even without the `--verbose` parameter.

I added some [logic](https://github.com/tindzk/seed/pull/64/commits/660051bc1784285fb72ebdb990f5387483d32fff) to detect the log level of messages. This does not always work since there are lines that do not have the `[D]` or `[E]` prefix.

See also the [CI log](http://ci.sparse.tech/tindzk/seed/480/1/3).

**Comment by jvican** [comment]
Err... this is not expected. It might be a regression. Or it might be that the launcher of this version surreptitiously enables --verbose on the server. Will have a look.

**Comment by jvican** [comment]
Are you by any chance running `--verbose` in the launcher? What are the specific arguments you pass to the launcher?

**Comment by tindzk** [comment]
No, I am not including `--verbose`. The CLI parameters are `bsp --socket <path>` ([code](
https://github.com/tindzk/seed/blob/55124732ba48da1e9225703fceee4eccb124bf3d/src/main/scala/seed/build/Bloop.scala#L448-L450)).

**Comment by jvican** [comment]
I can reproduce. Will fix
