### ISSUE TITLE
Use Scala compiler 2.11 ?

### ISSUE THREAD

**Issue by Dnomyar** [scalacenter/bloop#1139]
Hey folks,

I have a project that contains multiple multiple modules all configured to use scala `2.11.8` (`.project.scala.version`).

However, when I compile modules using `--verbose`, I can see that the version which is actually used is the `2.12.8`
```
[D] [zinc] Running cached compiler 467f2213 for Scala compiler version 2.12.8
```

I believe that is what is causing the `java.lang.NoClassDefFoundError: scala/Product$class` when I compile the code.

How can I configure bloop to use Scala compiler 2.11?

Cheers

**Comment by jvican** [comment]
Hey there, thanks for reporting!

What build tool are you using? The build tool should be exporting the appropriate scala version for your projects. Bloop supports a wide range of Scala versions. You can check whether your project has been correctly exported from your build tool by looking at the content of the `scala` property in its JSON configuration file. The `scala` object contains the version number and the jars of that resolved Scala version that should be used to compile.

**Comment by Dnomyar** [comment]
Thank for the answer. 

I am using SBT and `bloopInstall`

I was able to check that scala versions are all the same in every file (`2.11.8`).
```
.bloop $ cat *.json | jq '.project.scala.version' -c
// returns only `2.11.8`
```

I had to remove the jars because they were throwing NPEs. What is strange is that each file exists. Could it be permission problem causing NPE? Currently their permission are `-rw-r--r--`. 
```
"/Users/name/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/jline/jline/2.12.1/jline-2.12.1.jar",
"/Users/name/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/modules/scala-parser-combinators_2.11/1.0.4/scala-parser-combinators_2.11-1.0.4.jar",
"/Users/name/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.11.8/scala-reflect-2.11.8.jar",
"/Users/name/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.11/1.0.4/scala-xml_2.11-1.0.4.jar"
```

Here is one example of the `scala` object :
```json
"scala": {
    "organization": "org.scala-lang",
    "name": "scala-compiler",
    "version": "2.11.8",
    "options": [
        "-Xlint",
        "-feature",
        "-language:postfixOps",
        "-Yno-adapted-args",
        "-Ywarn-dead-code",
        "-Ywarn-infer-any",
        "-Ywarn-unused-import"
    ],
    "jars": [],
    "analysis": "/path/module/target/streams/compile/bloopAnalysisOut/$global/streams/inc_compile_2.11.zip",
    "setup": {
        "order": "mixed",
        "addLibraryToBootClasspath": true,
        "addCompilerToClasspath": false,
        "addExtraJarsToClasspath": false,
        "manageBootClasspath": true,
        "filterLibraryFromClasspath": true
    }
}
```

**Comment by jvican** [comment]
> I had to remove the jars because they were throwing NPEs
  
Right, you can't do that. Scala jars must be there and they must be usable by the build tool. Can you reexport your project and copy paste traces of the exceptions you get?

**Comment by jvican** [comment]
If you find a bloop-related error when re-exporting, please feel free to open a new ticket. If it's a permission related error, then it's most likely this issue is caused by how you run bloop/sbt and it's not something we can fix in the codebase.
