### ISSUE TITLE
Deduplicating might hang resulting in a broken workspace

### ISSUE THREAD

**Issue by tgodzik** [scalacenter/bloop#1140]
It seems I am getting more issues recently with deduplicating hanging in my workspace.
```
INFO  tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at /home/tgodzik/.cache/metals/bsp.trace.json
INFO  Connected to Build server v1.4.0-RC1
INFO  time: indexed workspace in 0.61s
INFO  Deduplicating compilation of input-test from bsp client 'Metals 0.7.6+707-c2394b32-SNAPSHOT' (since 4h 57m 57.571s)
INFO  Deduplicating compilation of interfaces-test from bsp client 'Metals 0.7.6+707-c2394b32-SNAPSHOT' (since 4h 57m 57.575s)
INFO  Deduplicating compilation of metals from bsp client 'Metals 0.7.6+707-c2394b32-SNAPSHOT' (since 4h 57m 57.601s)
INFO  compiling mtest (12 scala sources)
INFO  time: compiled mtest in 0.16s
```

@jvican Any idea what is going on or where to look?

Killing the server usually works.

**Comment by jvican** [comment]
I've run into this only once during the past two weeks, I'd love to find what's happening here for a compile deduplication to hang -- it's unusual. Nex time it happens to you, can you run compile with `--verbose`? Those logs will be very helpful to track this issue down.

**Comment by tgodzik** [comment]
> I've run into this only once during the past two weeks, I'd love to find what's happening here for a compile deduplication to hang -- it's unusual. Nex time it happens to you, can you run compile with `--verbose`? Those logs will be very helpful to track this issue down.

Sure, I think it might have been also caused by me killing the server multiple times - testing automatic reconnect.

**Comment by tpolecat** [comment]
I don't know if this is the same issue or not. I'm getting this from time to time when running with metals:

```scala
itac-cli (email-templates *)$ bloop compile main
Deduplicating compilation of main from cli client 'bloop-cli' (since 2m 31.044s)
```

Verbose looks like 

```scala
itac-cli (email-templates *)$ bloop compile main --verbose
[D] Loading workspace settings from bloop.settings.json
[D] Computing sources and classpath hashes for engine
[D] Scheduling compilation for engine...
[D] Using successful result for engine associated with /Users/rnorris/Scala/itac-cli/.bloop/engine/bloop-internal-classes/classes-Metals-34Gv4p8FQlCgR9otzcX2Wg==-PhE6S84eRuONfWuTkTwyng==
[D] Increasing counter for /Users/rnorris/Scala/itac-cli/.bloop/engine/bloop-internal-classes/classes-Metals-34Gv4p8FQlCgR9otzcX2Wg==-PhE6S84eRuONfWuTkTwyng== to 11
[D] Disabled compiler plugin classloading, unsupported in 2.12.1
[D] External classes directory /Users/rnorris/Scala/itac-cli/.bloop/engine/bloop-bsp-clients-classes/bloop-cli
[D] Read-only classes directory /Users/rnorris/Scala/itac-cli/.bloop/engine/bloop-internal-classes/classes-Metals-34Gv4p8FQlCgR9otzcX2Wg==-PhE6S84eRuONfWuTkTwyng==
[D] New rw classes directory /Users/rnorris/Scala/itac-cli/.bloop/engine/bloop-internal-classes/bloop-cli-9ee8k3hLRtGUPyEbyP_3ag==
[D] No changes
[D] Recording new last successful request for engine associated with /Users/rnorris/Scala/itac-cli/.bloop/engine/bloop-internal-classes/classes-Metals-34Gv4p8FQlCgR9otzcX2Wg==-PhE6S84eRuONfWuTkTwyng==
[D] Computing sources and classpath hashes for main
Deduplicating compilation of main from cli client 'bloop-cli' (since 1m 59.923s)
[D] Computing sources and classpath hashes for main
[D] Scheduling compilation for main...
[D] Using successful result for main associated with /Users/rnorris/Scala/itac-cli/.bloop/main/bloop-internal-classes/classes-Metals-P1uMhyA2TVaBW07n1PNnGA==-CFm-ntMSTt-eDXl_RmNMMA==
[D] Disabled compiler plugin classloading, unsupported in 2.12.1
[D] Elapsed: 10.267004 ms
[T] java.lang.NullPointerException
[T]     xsbti.api.SafeLazy$Impl.get(SafeLazy.java:62)
[T]     xsbti.api.ClassLike.selfType(ClassLike.java:37)
[T]     sbt.internal.inc.binary.converters.ProtobufWriters.toClassLike(ProtobufWriters.scala:538)
[T]     sbt.internal.inc.binary.converters.ProtobufWriters.toCompanions$1(ProtobufWriters.scala:570)
[T]     sbt.internal.inc.binary.converters.ProtobufWriters.toAnalyzedClass(ProtobufWriters.scala:582)
[T]     sbt.internal.inc.binary.converters.ProtobufWriters.$anonfun$toApis$1(ProtobufWriters.scala:674)
[T]     sbt.internal.inc.binary.converters.ProtobufWriters.$anonfun$toApis$2(ProtobufWriters.scala:675)
[T]     scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
[T]     scala.collection.immutable.HashMap$HashMap1.foreach(HashMap.scala:234)
[T]     scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:468)
[T]     scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:468)
[T]     scala.collection.TraversableLike.map(TraversableLike.scala:238)
[T]     scala.collection.TraversableLike.map$(TraversableLike.scala:231)
[T]     scala.collection.AbstractTraversable.map(Traversable.scala:108)
[T]     sbt.internal.inc.binary.converters.ProtobufWriters.toApis(ProtobufWriters.scala:675)
[T]     sbt.internal.inc.binary.converters.ProtobufWriters.toApisFile(ProtobufWriters.scala:683)
[T]     sbt.internal.inc.binary.BinaryAnalysisFormat.writeAPIs(BinaryAnalysisFormat.scala:37)
[T]     sbt.internal.inc.FileAnalysisStore$BinaryFileStore.$anonfun$set$1(FileAnalysisStore.scala:95)
[T]     sbt.internal.inc.FileAnalysisStore$BinaryFileStore.$anonfun$set$1$adapted(FileAnalysisStore.scala:88)
[T]     sbt.io.Using.apply(Using.scala:22)
[T]     sbt.internal.inc.FileAnalysisStore$BinaryFileStore.set(FileAnalysisStore.scala:88)
[T]     bloop.Compiler$.$anonfun$persist$1(Compiler.scala:756)
[T]     bloop.Compiler$.$anonfun$persist$1$adapted(Compiler.scala:751)
[T]     bloop.tracing.BraveTracer.trace(BraveTracer.scala:31)
[T]     bloop.Compiler$.persist(Compiler.scala:751)
[T]     bloop.Compiler$.$anonfun$compile$13(Compiler.scala:432)
[T]     scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[T]     monix.eval.internal.TaskRunLoop$.monix$eval$internal$TaskRunLoop$$loop$1(TaskRunLoop.scala:187)
[T]     monix.eval.internal.TaskRunLoop$RestartCallback$1.onSuccess(TaskRunLoop.scala:119)
[T]     monix.eval.Task$.$anonfun$forkedUnit$2(Task.scala:1463)
[T]     java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[T]     java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[T]     java.lang.Thread.run(Thread.java:748)
```

Perhaps overly dramatic but `rm -f .bloop` and restarting bloop and re-importing the project fixes it.

**Comment by tgodzik** [comment]
@tpolecat 

Something looks really wrong here, are you indeed using Scala 2.12.1 ? :fearful: 
`[D] Disabled compiler plugin classloading, unsupported in 2.12.1`

Does the same happen in `2.12.10`?
From what we found, bumping xss should help in situations where there is a lot of `deduplicating` messages, but nothing is happening.

**Comment by jvican** [comment]
He's not using 2.12.1, the fact that we print the version like that is a bug in Bloop.
  
@tpolecat I'm aware of that issue and how to fix it, will try to send a PR soon and figure out why that exception doesn't cancel the compiled deduplication.

**Comment by olafurpg** [comment]
@tgodzik that 2.12.1 warning happens for all scala versions, even when you’re on 2.12.10

**Comment by tgodzik** [comment]
Ok, thanks! I was super confused by that warning.

**Comment by jvican** [comment]
FTR the 2.12.1 well-known issue has just been fixed in latest master. Will have a closer look at errors during deduplicated compilations soon.

**Comment by matthughes** [comment]
Also getting the same thing.  Running CLI concurrently with Metals has not been super reliable lately.  If I'm coding all day I say I hit this at least once a day:

```
bloop compile  server --verbose                                                                                                                                                                               [I]
[D] Loading workspace settings from bloop.settings.json
[D] Computing sources and classpath hashes for commonJVM
Deduplicating compilation of commonJVM from cli client 'bloop-cli' (since 2m 6.187s)
[D] Computing sources and classpath hashes for commonJVM
[D] Scheduling compilation for commonJVM...
[D] Using successful result for commonJVM associated with /Users/mhughe008/development/vise/project/.bloop/commonJVM/bloop-internal-classes/classes-bloop-cli-gHElfca4SKi1v44yZmrxVA==
[D] Increasing counter for /Users/mhughe008/development/vise/project/.bloop/commonJVM/bloop-internal-classes/classes-bloop-cli-gHElfca4SKi1v44yZmrxVA== to 3
[W] Disconnecting from deduplication of ongoing compilation for 'commonJVM'
[W] No progress update for 30 seconds caused bloop to cancel compilation and schedule a new compile.
[W]
[D] Computing sources and classpath hashes for commonJVM
[D] Scheduling compilation for commonJVM...
[D] Using successful result for commonJVM associated with /Users/mhughe008/development/vise/project/.bloop/commonJVM/bloop-internal-classes/classes-bloop-cli-gHElfca4SKi1v44yZmrxVA==
[D] Increasing counter for /Users/mhughe008/development/vise/project/.bloop/commonJVM/bloop-internal-classes/classes-bloop-cli-gHElfca4SKi1v44yZmrxVA== to 6
```

In my case I never get it to fail with NPE but it just hangs there forever.  Using ```bloop 1.4.0-RC1-190-ef7d8dba```

**Comment by tgodzik** [comment]
> Also getting the same thing. Running CLI concurrently with Metals has not been super reliable lately. If I'm coding all day I say I hit this at least once a day:
> 
> ```
> bloop compile  server --verbose                                                                                                                                                                               [I]
> [D] Loading workspace settings from bloop.settings.json
> [D] Computing sources and classpath hashes for commonJVM
> Deduplicating compilation of commonJVM from cli client 'bloop-cli' (since 2m 6.187s)
> [D] Computing sources and classpath hashes for commonJVM
> [D] Scheduling compilation for commonJVM...
> [D] Using successful result for commonJVM associated with /Users/mhughe008/development/vise/project/.bloop/commonJVM/bloop-internal-classes/classes-bloop-cli-gHElfca4SKi1v44yZmrxVA==
> [D] Increasing counter for /Users/mhughe008/development/vise/project/.bloop/commonJVM/bloop-internal-classes/classes-bloop-cli-gHElfca4SKi1v44yZmrxVA== to 3
> [W] Disconnecting from deduplication of ongoing compilation for 'commonJVM'
> [W] No progress update for 30 seconds caused bloop to cancel compilation and schedule a new compile.
> [W]
> [D] Computing sources and classpath hashes for commonJVM
> [D] Scheduling compilation for commonJVM...
> [D] Using successful result for commonJVM associated with /Users/mhughe008/development/vise/project/.bloop/commonJVM/bloop-internal-classes/classes-bloop-cli-gHElfca4SKi1v44yZmrxVA==
> [D] Increasing counter for /Users/mhughe008/development/vise/project/.bloop/commonJVM/bloop-internal-classes/classes-bloop-cli-gHElfca4SKi1v44yZmrxVA== to 6
> ```
> 
> In my case I never get it to fail with NPE but it just hangs there forever. Using `bloop 1.4.0-RC1-190-ef7d8dba`

@matthughes  Will you be willing to make take a stack trace next time this happens? We are trying to fix all possible issues connected to this.

**Comment by matthughes** [comment]
Sure I actually took one but of course didn't paste it.  I didn't see anything interesting but I'm sure you would know better than me.

**Comment by tpolecat** [comment]
This has happened to me once or twice recently but it seems that `brew services restart bloop` now unconfuses it, at least temporarily (I no longer need to wipe out the `.bloop` directory and re-import my project). So at least for me it's less severe and much less frequent than before, but hasn't disappeared entirely.

**Comment by jvican** [comment]
The issue reported by @tpolecat is now fixed by https://github.com/scalacenter/bloop/pull/1265. I need to add another fix to Bloop so that when there's an exception, the compilation that is tracked and deduplicated fails altogether. It should be working like that, I don't know why it doesn't.
  
@matthughes Regarding your issue, it seems different from the one reported here. If you see, you have at one point 6 different clients connected to bloop and asking for that compilation (that's what the `[D] Increasing counter for /Users/mhughe008/development/vise/project/.bloop/commonJVM/bloop-internal-classes/classes-bloop-cli-gHElfca4SKi1v44yZmrxVA== to 6` log tells you) and Bloop is cancelling the duplication correctly because there are no compile updates from the original compilation that your client is trying to deduplicate. This hints at the compilation of that project being stuck, because that only happens when there are no progress updates from the compiler itself. I would check stack sizes and memory limits, as those are the most common reason for stuck compilations.
