### ISSUE TITLE
Unexpected `NullPointerException` in `ScalaInstance.scala`

### ISSUE THREAD

**Issue by jypma** [scalacenter/bloop#1142]
When trying to run `bloop test` on an SBT-built mostly-java project ([ts-reaktive](https://github.com/Tradeshift/ts-reaktive/)):
- `git clone git@github.com:Tradeshift/ts-reaktive.git`
- `sbt bloopInstall`
```
$ bloop test ts-reaktive-actors
java.lang.NullPointerException
	at bloop.ScalaInstance.supportsHydra(ScalaInstance.scala:78)
	at bloop.data.Project$.$anonfun$fromBytesAndOrigin$1(Project.scala:137)
	at bloop.data.Project$.$anonfun$fromBytesAndOrigin$1$adapted(Project.scala:137)
	at scala.Option.map(Option.scala:230)
	at bloop.data.Project$.fromBytesAndOrigin(Project.scala:137)
	at bloop.engine.BuildLoader$.loadProject(BuildLoader.scala:237)
[...]
```
Apparently the [`compilerJar`](https://github.com/scalacenter/bloop/blob/master/backend/src/main/scala/bloop/ScalaInstance.scala#L24) field is null in `ScalaInstance`. The error message could potentially be improved ("couldn't find scala compiler?"), by replacing `.orNull` in the expression for that field.

However I'm unsure what's really going on, since I do recall having used bloop on Java/SBT projects with previous versions, even having ran JUnit tests...

This is with bloop 1.4.0-RC1.

**Comment by jvican** [comment]
This is a regression, I'll fix it. /cc @dotta 
  
> At the very least this could be a better message
  
This is not the most friendly way to put that your expectation as a user is a better error message.

**Comment by jypma** [comment]
Thanks a lot for jumping on this!

> This is not the most friendly way to put that your expectation as a user is a better error message.

I apologize if I've offended anyone, that was certainly not my intent. I was expressing expectations of the program, not of any of its creators or contributors. The anthropomorphism obviously was too subtle; again, my apologies for that.

I'll edit the description to the intent is more clear. Thanks for mentioning it.

**Comment by jvican** [comment]
No worries, no personal offense taken. As a user, I agree with your expectation that NPEs should not leak to the end user. This must be a regression from some of the low level compiler APIs that we use in Bloop.

Could you provide more info about the contents of the configuration file `ts-reactive-actors`, maybe copy paste it here?

**Comment by jypma** [comment]
It's open source (MIT license), here is its entire [build.sbt](https://github.com/Tradeshift/ts-reaktive/blob/master/build.sbt), but I can try and copy the relevant details here:
```
lazy val projectSettings = Seq(
  scalaVersion := "2.12.6",
  crossScalaVersions := Seq("2.12.6"),
  publishMavenStyle := true,
  javacOptions ++= Seq("-source", "1.8"),
  scalacOptions ++= Seq("-target:jvm-1.8"),
  [...]
)

lazy val javaSettings = Seq(
  // This forbids including Scala related libraries into the dependency
  autoScalaLibrary := false,

  // Make this a Java-only project in Eclipse
  EclipseKeys.projectFlavor := EclipseProjectFlavor.Java
)

lazy val `ts-reaktive-actors` = project
  .enablePlugins(ProtobufPlugin)
  .enablePlugins(GitVersioning)
  .settings(commonSettings: _*)
  .settings(javaSettings: _*)
  [...]
  .dependsOn(`ts-reaktive-java`, `ts-reaktive-akka`, `ts-reaktive-testkit` % "test")
```

I'm guessing the `autoScalaLibrary := false` may be to blame?

**Comment by jvican** [comment]
It's a good lead, I'll let you know what I find.

**Comment by dotta** [comment]
@jvican If this is a regression (as it seems to be), I guess a simple fix is to wrap usage of `compilerJar` in the `supportsHydra` impl with an Option. This is how it should have been done already. Happy to push a PR with the change if that helps.
