### ISSUE TITLE
Missing resources when missing class files?

### ISSUE THREAD

**Issue by Arthurm1** [scalacenter/bloop#1146]
When Project B depends on Project A, then Project A's resources are added to the classpath of Project B.
E.g. when compiling Project B using --verbose, the classpath contains...
```
E:\dev\src\A\src\main\resources;E:\dev\.bloop\A\build\bloop-internal-classes\bloop-cli-9S6VGcWuSWqcjKqO-lWtxg==
```

If Project A doesn't have any classes, i.e. it purely holds resources then these resources are missing from Project B's classpath.  The path instead contains...
```
E:\dev\.bloop\A\build\classes
```

Notice the reference to Project A's classes dir has changed as well. I'm guessing Bloop matches on these classes directories to decide whether to include resources in the classpath and is failing to match?
Project A's resources directory should still be included in B's classpath.

Here's a sample file for Project A...
```
{
    "version": "1.1.2",
    "project": {
        "name": "Config",
        "directory": "E:\\dev\\src\\A",
        "workspaceDir": "E:\\dev",
        "sources": [
        ],
        "dependencies": [
        ],
        "classpath": [
        ],
        "out": "E:\\dev\\.bloop\\A\\build",
        "classesDir": "E:\\dev\\.bloop\\A\\build\\classes",
        "resources": [
            "E:\\dev\\src\\A\\src\\main\\resources"
        ],
        "java": {
            "options": [
                "-source",
                "1.8",
                "-target",
                "1.8",
                "-g",
                "-sourcepath",
                "-proc:none",
                "-XDuseUnsharedTable=true",
                "-Xlint:unchecked",
                "-Xlint:deprecation"
            ]
        },
        "platform": {
            "name": "jvm",
            "config": {
                "home": "C:\\Program Files\\Java\\jdk1.8.0_191",
                "options": [
                    
                ]
            },
            "mainClass": [
                
            ]
        },
        "resolution": {
            "modules": [
                
            ]
        }
    }
}
```

**Comment by jvican** [comment]
Thanks for reporting @Arthurm1, this looks like an important problem, I'll have a look at this in my afternoon.

**Comment by Arthurm1** [comment]
I'm now wondering whether it is an error.

I was looking at "bloop compile Project --verbose" and was confused because there was a difference in the classpath between projects with classes & resources and projects with just resources.

Should resources be on the **compile** classpath at all - should they only feature on the **run/test** classpath?

On checking the runtime classpath it seems they are there after all so I don't think this is an issue.

**Comment by jvican** [comment]
They need to be on the compile classpath because of macros.

**Comment by agilesteel** [comment]
@jvican I'm not 100% sure if I reproduced "my" bug but I definitely reproduced "a" bug related to resource loading. Let me know if you manage to reproduce it https://github.com/agilesteel/bloop-resource-loading-bug I'm on the latest `1.4.0-RC1+9-e94b10c3` btw.

**Comment by agilesteel** [comment]
@jvican hey I just noticed that you renamed this issue after my post. I also added a class file to project `b` but that didn't help so I'm not sure if it is related.

**Comment by jvican** [comment]
I’ll have a look 👍
