### ISSUE TITLE
Unsupported configuration `compile-internal` in sbt

### ISSUE THREAD

**Issue by antonoal** [scalacenter/bloop#1147]
I'm using vscode with the latest metals which uses sbt-bloop plugin v1.4.0-RC1.
In my project I've got a module with a few macros and module that depends on the macros one with "compile-internal" settings. 
Just in case here's the information about compile-internal: https://www.scala-sbt.org/1.x/docs/Macro-Projects.html#Distribution
Here's a gist to a simple project to reproduce the issue:
https://gist.github.com/antonoal/1f88d0e95cb1026675d008694f966e97
The issue is that the module dependency is not compiled correctly by bloop whereas sbt compiles it without problems.

**Comment by jvican** [comment]
Hi @antonoal, thanks for reporting. Yes, `compile-internal` is not supported on purpose and there are no plans to support it. Please, use the regular `compile` scope if you want to distribute those class files together with your core code I suggest creating a task that copies them over and it's called before `package` or `packageBin`.

**Comment by tgodzik** [comment]
I think it might be difficult to model within Bloop currently. What is the use case it would be needed currently?

**Comment by azdrojowa123** [comment]
I was just asking out of curiosity, I have no particular case in mind
