### ISSUE TITLE
Missing classes in integration test sbt config

### ISSUE THREAD

**Issue by matheussbernardo** [scalacenter/bloop#1162]
Hello, I am trying to setup metals with bloop at vscode and my build.sbt looks like this
```
 lazy val root = (project in file("."))
  .configs(IntegrationTest)
  .settings(
    name := "retro-service",
    Defaults.itSettings,
    libraryDependencies ++= Dependencies.libraries,
    outputStrategy := Some(StdoutOutput),
    inThisBuild(List(organization := "com.mycompany", scalaVersion := "2.12.10"))
)

dependencyClasspath in IntegrationTest :=
  (dependencyClasspath in IntegrationTest).value ++ (exportedProducts in Test).value

onLoad in Global ~= (_ andThen ("loadEnv" :: _))

fork := true
run / fork := false
run / envVars  := loadEnv.value._2
Test / envVars  := loadEnv.value._2
IntegrationTest / parallelExecution := false
IntegrationTest / envVars:= loadEnv.value._2
IntegrationTest / dependencyClasspath :=
  (IntegrationTest / dependencyClasspath).value ++ (Test / exportedProducts).value
```

But VScode is saying that a Class from /test is not on scope of a class at /it

**Comment by maciejbak85** [comment]
the same issue with Intellij :(

**Comment by jvican** [comment]
@matheussbernardo Sorry for the late reply. The sbt build code that you've shared looks a little bit hacky in that you only express the dependency between the integration test project and the test project via `exportedProducts`. You should instead express the dependency at the project level so that bloop can pick it up. You can do that by writing this instead:
  
```
val DeepIntegrationTest = IntegrationTest.extend(Test)
lazy val root = (project in file("."))
  .configs(DeepIntegrationTest)
...
```
You need to make sure you replace any reference to `IntegrationTest` by `DeepIntegrationTest`. With that, bloop should correctly infer that your it sources depend on your test sources.

**Comment by maciejbak85** [comment]
> @matheussbernardo Sorry for the late reply. The sbt build code that you've shared looks a little bit hacky in that you only express the dependency between the integration test project and the test project via `exportedProducts`. You should instead express the dependency at the project level so that bloop can pick it up. You can do that by writing this instead:
> 
> ```
> val DeepIntegrationTest = IntegrationTest.extend(Test)
> lazy val root = (project in file("."))
>   .configs(DeepIntegrationTest)
> ...
> ```
> 
> You need to make sure you replace any reference to `IntegrationTest` by `DeepIntegrationTest`. With that, bloop should correctly infer that your it sources depend on your test sources.

Ive added in my project:

```
lazy val DeepIntegrationTest = IntegrationTest.extend(Test)
    def integrationTestSettings: Project =
      project
        .configs(DeepIntegrationTest)
        .settings(Defaults.itSettings)
        .settings(inConfig(DeepIntegrationTest)(scalafmtConfigSettings): _*)
        .settings(
          fork in (DeepIntegrationTest, run) := true,
          parallelExecution in DeepIntegrationTest := true,
          // Allows to use test scope code/deps in integration tests
          dependencyClasspath in DeepIntegrationTest := (dependencyClasspath in DeepIntegrationTest).value ++ (dependencyClasspath in Test).value
        )
```

and still does not work :(

**Comment by matheussbernardo** [comment]
@maciejbak85 Hello, Here it worked.

```
lazy val DeepIntegrationTest = IntegrationTest.extend(Test)
lazy val root = (project in file("."))
  .configs(DeepIntegrationTest)
  .settings(....

dependencyClasspath in DeepIntegrationTest :=
  (dependencyClasspath in DeepIntegrationTest).value ++ (exportedProducts in Test).value

onLoad in Global ~= (_ andThen ("loadEnv" :: _))

fork := true
run / fork := true
run / envVars := loadEnv.value._2
Test / envVars := loadEnv.value._2
DeepIntegrationTest / parallelExecution := false
DeepIntegrationTest / envVars := loadEnv.value._2
DeepIntegrationTest / dependencyClasspath :=
  (DeepIntegrationTest / dependencyClasspath).value ++ (Test / exportedProducts).value

```

**Comment by jvican** [comment]
@maciejbak85 You should remove the `exportedProducts in Test` hack and most likely scope `Defaults.itSettings` to the correct custom config you've just introduced.
  
```
lazy val DeepIntegrationTest = IntegrationTest.extend(Test)
    def integrationTestSettings: Project =
      project
        .configs(DeepIntegrationTest)
        .settings(Defaults.itSettings in DeepIntegrationTest)
        .settings(inConfig(DeepIntegrationTest)(scalafmtConfigSettings): _*)
        .settings(
          fork in (DeepIntegrationTest, run) := true,
          parallelExecution in DeepIntegrationTest := true
        )
```

The `extend(Test)` bit in the `DeepIntegration` config definition is the one already giving you access to the test classpath.

**Comment by jvican** [comment]
BTW, I've just remembered that we have a test covering this use case in https://github.com/scalacenter/bloop/blob/master/integrations/sbt-bloop/src/sbt-test/sbt-bloop/custom-configurations/build.sbt
  
I think this was a configuration issue and it's solved already. I'm closing, feel free to let me know if you're still having trouble with this but my general advice is that you avoid configurations such as Integration test and instead create a new project to define integration tests and then make a dependency to the tests of the other project.
