### ISSUE TITLE
Find other way to get to build tools docs in website

### ISSUE THREAD

**Issue by dangerousben** [scalacenter/bloop#1163]
The [Installation Guide](https://scalacenter.github.io/bloop/setup) is great for setting everything up when starting from scratch.  But if (for example) I'm already happily using bloop with sbt, and now want to use it with maven I find [this page](https://scalacenter.github.io/bloop/docs/build-tools/maven), which links to the install guide.  I then have to skip through a load of stuff that's no longer relevant to me, until I get down to section 4, where I finally learn how to export the build using maven.

It would be more useful if the maven page duplicated the maven-specific text of the install guide, prefixed with something like "If you already have bloop installed, then read on.  Otherwise follow the installation guide here.".

**Comment by jvican** [comment]
I agree with your analysis @dangerousben We should have independent pages for the build tool docs. This is even more important because we're going to remove independent installation methods and instead prefer installing bloop through coursier. Thanks for taking the time to writing your thoughts.
