### ISSUE TITLE
Unresolved compiler bridge with proxy config in jvm opts

### ISSUE THREAD

**Issue by mangosmoothie** [scalacenter/bloop#1169]
I can run bloop compile / test on a project with Scala 2.11 but not 2.12

I get the following error when running bloop compile root:

Unexpected error when compiling root: 'Couldn't retrieve module ch.epfl.scala:compiler-bridge_2.12:1.3.0-M4+32-b1accb96:compile'

**Comment by mangosmoothie** [comment]
so I'm behind a web proxy and I have $JAVA_OPTS setup to respect this. I can use coursier just fine from the command line - I guess my env is not getting passed to coursier when invoked from bloop.

I was able to get past my issue finally by running `coursier fetch --sources ch.epfl.scala:compiler-bridge_2.12:1.3.0-M4+32-b1accb96:compiler-bridge_2.12-1.3.0-M4+32-b1accb96`

**Comment by tgodzik** [comment]
@mangosmoothie I am not sure if JAVA_OPTS will work for Bloop. I wrote a troubleshooting guide recently on how to deal with Metals and Bloop proxy settings: https://scalameta.org/metals/docs/build-tools/proxy.html

There might something helpful there.

**Comment by jvican** [comment]
Depends where and how you're setting up `$JAVA_OPTS`, Bloop will pick it up. How are you launching the bloop server?
  
The preferred way of getting bloop to work with proxies is that you set up the PROXY environment variables. You can read https://github.com/scalacenter/bloop/blob/master/frontend/src/main/scala/bloop/util/ProxySetup.scala to understand the code handling proxies.
  
Another interesting read for you is https://github.com/scalacenter/bloop/issues/920 which explains a case where coursier can't pick up system options. Bloop could be picking up your jvm options but if coursier doesn't respect them there's nothing we can do. Maybe you can just change the way you set up the proxy to use environment variables?
  
I've realized we don't have docs for proxy and we probably should. If you have the time, I encourage you to contribute these docs after you figure this out.

**Comment by mangosmoothie** [comment]
Thanks @tgodzik and @jvican for taking a look at this.

I actually got bloop running by setting my proxy options in`~/.bloop/.jvmopts` that I got from the guide @tgodzik https://scalameta.org/metals/docs/build-tools/proxy.html sent.

Contents of `~/.bloop/.jvmopts`

I'm running squid locally with the authenticated web proxy as a parent proxy. I'll look into updating the docs with this solution.

```
-Dhttps.proxyHost=localhost
-Dhttp.proxyHost=localhost
-Dhttps.proxyPort=4444
-Dhttp.proxyPort=4444
```

**Comment by biboudis** [comment]
This didn't work for me when using VSCode behind a proxy. I get the same error. I tried setting `.jvmopts` both inside the home directory .bloop and on my projects `.bloop` directory.

I get the same error as @mangosmoothie's (version v1.4.0-RC1-229-b7c15aa9)

**Comment by jvican** [comment]
Great 👌 happy it’s fixed after the restart.
