### ISSUE TITLE
Add new "refreshProjectsCommand" workspace setting 

### ISSUE THREAD

**Issue by olafurpg** [scalacenter/bloop#1182]
Currently, `.bloop/bloop.settings.json` includes workspace settings like the SemanticDB version, which is only used by Metals to simplify the installation of SemanticDB.

This issue is a proposal to add a new `refreshProjectsCommand: Option[List[String]]` field with the goals to improve the IntelliJ BSP experience. The contract of the `refreshProjectCommand` field is that Bloop invokes this system command to re-export the build when users press the "Reimport All BSP Projects" button in IntelliJ.

<img width="221" alt="Screenshot 2020-02-25 at 18 02 59" src="https://user-images.githubusercontent.com/1408093/75273597-150f0300-57f9-11ea-83f8-557e2a42b7ca.png">

This allows for example the Pants/Bloop integration to export the Pants build when users press the "refresh BSP projects" button.

I have a WIP branch to Bloop (https://github.com/olafurpg/bloop/compare/refresh-project?expand=1) that implements this functionality. Demo:

![2020-02-25 18 26 26](https://user-images.githubusercontent.com/1408093/75276809-c49aa400-57fe-11ea-80c3-f2cd11b84ab3.gif)

To manually test out the changes with Pants, you will need the following change in Metals https://github.com/scalameta/metals/pull/1467. I recommend checking out that branch of Metals and run `sbt publishLocal` first.

Then create a file `bloop.settings.json`
```json
❯ cat bloop.settings.json
{
  "refreshProjectsCommand": [
    "/usr/local/bin/coursier", // EDIT THIS
    "launch",
    "org.scalameta:metals_2.12:0.8.1-SNAPSHOT",
    "--main",
    "scala.meta.internal.pantsbuild.BloopPants",
    "--",
    "refresh",
    "--workspace",
    "/Users/lgeirsson/dev/bsp-pants", // EDIT THIS
    "package-filename"
  ]
}
```

Next, open a Pants IntelliJ BSP project with the following instructions

```
git clone -b refresh-projects https://github.com/olafurpg/bsp-pants
cd intellij-bsp-pants
./setup-bsp.sh
```

Make sure to use the latest IntelliJ 2020.1 EAP, the version I've been using

```
IntelliJ IDEA 2020.1 EAP (Community Edition)
Build #IC-201.5616.10, built on February 19, 2020
Runtime version: 11.0.6+8-b722.15 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.6
GC: ParNew, ConcurrentMarkSweep
Memory: 7916M
Cores: 12
Registry: 
Non-Bundled Plugins: IdeaVIM, YourKit Java Profiler 2019.8-b137 Integration, org.intellij.scala
```

The `bloop.settings.json` file is not automatically created so you will need to copy it into `.bloop` with

```
cp bloop.settings.json .bloop/
```

Next, checkout the WIP branch of bloop and start the bloop server locally
```
bloop exit # stop currently running Bloop server
git clone -b refresh-projects https://github.com/olafurpg/bloop
cd bloop
sbt # may take a while to start the first time
> frontend/runMain bloop.Server 
```

If all is correctly setup, when you press the "refresh all BSP projects" button the `build targets` like this

<img width="1460" alt="Screenshot 2020-02-25 at 18 49 28" src="https://user-images.githubusercontent.com/1408093/75277402-daf52f80-57ff-11ea-8794-57c6385130a9.png">

**Comment by jvican** [comment]
Thanks for opening such a detailed feature request @olafurpg 
  
I agree this feature is desirable. I like that it only runs in the expensive scenario of "refreshing projects" which is already expected to be slow. The side effects run by the build tool when this command is executed might be useful for future use cases. Looking forward to reviewing the PR implementing it.

**Comment by jvican** [comment]
Fixed by https://github.com/scalacenter/bloop/pull/1195
