### ISSUE TITLE
Add post-compile hook for bloop command

### ISSUE THREAD

**Issue by aappddeevv** [scalacenter/bloop#1194]
It would be useful to have a post compile hook that is run after compilation, e.g, `bloop compile -w -p myproject --after cool_script_to_run.sh` so I can run some additional post compilation steps.

**Comment by jvican** [comment]
Hi @aappddeevv, thanks for the feature request. I have considered this in the past and I don't want to enable this kind of customization downstream.
  
If you want to run some additional code after compilation, there are two ways:

1. Fork the project and implement this logic yourself
2. Implement a [BSP](https://github.com/scalacenter/build-server-protocol) client that proxies requests to Bloop. Bloop will send you a response/notification when compilation happens, so you can run whichever code then. In this manner, you don't need to fork the project but have complete control over which commands are sent to Bloop.

**Comment by aappddeevv** [comment]
That's fine. Thanks for considering. You may want to mention this in the docs somewhere although I should have asked this on the chat first. You could also watch the outputs directly, but that's alot more latency.

**Comment by jvican** [comment]
That's a good suggestion, I'll update the docs to emphasize this use case.
