### ISSUE TITLE
Xss option override

### ISSUE THREAD

**Issue by voidcontext** [scalacenter/bloop#1205]
With the changes in #1174 it seems there is 2 Xss option passed to the `java` binary if there is one in `~/.bloop/.jvmopts`.

```
java -Xss4m -Xss1m -XX:MaxInlineLevel=20 -XX:+UseParallelGC -classpath ...
```
On my jvm the last setting is going to be used

```
 java -version; java -Xss4m -XX:+PrintFlagsFinal -Xss2m 2>/dev/null | grep \ ThreadStackSize


openjdk version "1.8.0_222"
OpenJDK Runtime Environment (Zulu 8.40.0.25-CA-macosx) (build 1.8.0_222-b10)
OpenJDK 64-Bit Server VM (Zulu 8.40.0.25-CA-macosx) (build 25.222-b10, mixed mode)
     intx ThreadStackSize                          := 2048                                {pd product}
```

This is causing the compilation to hang as described in https://github.com/scalameta/metals/issues/1483.

**Comment by olafurpg** [comment]
Thank you for reporting! There's an open PR that adds a new way to globally configure  JVM options along with Java home via `$HOME/.bloop/bloop.json`. The `$HOME/.bloop/.jvmopts` file will continue to be respected, I pushed a new commit changing the order so the default option appear first

**Comment by voidcontext** [comment]
That should do it, thank you for the quick response and fix!
