### ISSUE TITLE
Broken build tool sections in installation page

### ISSUE THREAD

**Issue by jsatk** [scalacenter/bloop#1220]
See this 7 second video. http://i.jsatk.us/pOLpng

**Comment by jvican** [comment]
Thanks for reporting @jsatk, it was an issue with the docs build, it's fixed now.

**Comment by jsatk** [comment]
@jvican thanks for the super fast response. 😄

**Comment by jvican** [comment]
For some reason this particular issue still happens. Will look deeper into why...
