### ISSUE TITLE
Runtime classpath and resources are swapped when saved

### ISSUE THREAD

**Issue by Arthurm1** [scalacenter/bloop#1247]
JVM Platform runtime classpath gets saved as resources in JSON file and vice versa

possibly resources and classpath are swapped [here](https://github.com/scalacenter/bloop/blob/b8c48e3fe089ceb198d113bee1a730d1c76358de/config/src/main/scala-2.11-13/bloop/config/ConfigCodecs.scala#L192)

**Comment by Duhemm** [comment]
Thanks for the report @Arthurm1 ! This should be fixed by #1248.
