### ISSUE TITLE
Update build logic to ignore loading builds from `$HOME/.bloop`

### ISSUE THREAD

**Issue by mihaisoloi** [scalacenter/bloop#1249]
When running from `$HOME`

`coursier launch ch.epfl.scala:bloopgun_2.12:latest.release -- about`

the server correctly starts with the config values from `$HOME/.bloop/bloop.json` but it also gives this error:

`[E] Failed to load project from $HOME/.bloop/bloop.json`

This happens because you run `bloop about` in your `$HOME`,  but the change that introduced `$HOME/.bloop/bloop.json` has the shape of a bloop build so bloop tries to load `bloop.json` from there.

**Comment by olafurpg** [comment]
Thank you for reporting! I'm able to reproduce, I'll send a PR to fix
