### ISSUE TITLE
Unexpected error when compiling dotty

### ISSUE THREAD

**Issue by kubukoz** [scalacenter/bloop#1272]
I'm getting this when compiling some Dotty code:

```scala
bloop compile mio                                                                                                                 ✔ | 03:09:36
Compiling mio (1 Scala source)
[E] [E-1] Found:    Seq[scala.annotation.Annotation]
[E]       Required: Array[String]
Compiled mio (809ms)
[E] Failed to compile 'mio'
```

`compile` in sbt works without errors.

The code:

```scala
import cats.syntax.functor._
import scala.language.implicitConversions

trait IO[A] {

  def bracketExit[B]: IO[B] =
    this.map(a => (???): B)
}

object IO {
  implicit def ioFunctor[A]: cats.Functor[IO] = ???
}
```

Important: I'm depending on `"org.typelevel" % "cats-core_2.13" % "2.1.1"`. `map` comes from an implicit conversion defined in the`cats.syntax.flatMap` object, which uses the `ioFunctor` instance.

Dotty versions checked: `0.24.0-RC1`, `0.25.0-bin-20200506-4da1f25-NIGHTLY`

Bloop about:

```
bloop v1.4.0-RC1-229-b7c15aa9

Using Scala v2.12.8 and Zinc v1.3.0-M4+42-5daa8ed7
Running on Java JDK v11.0.6 (/Users/kubukoz/.sdkman/candidates/java/20.0.0.r11-grl)
  -> Supports debugging user code, Java Debug Interface (JDI) is available.
Maintained by the Scala Center (Jorge Vicente Cantero, Martin Duhem)
```

Reproduction branch: https://github.com/kubukoz/MIO/tree/dotty-repro

**Comment by jvican** [comment]
Thanks for reporting @kubukoz! Any idea what could be going on here @smarter?

**Comment by smarter** [comment]
No idea.

**Comment by felixbr** [comment]
Hi, I just wanted to say that I'm also getting this error multiple times in a codebase using `monix`, `fs2`, and `cats-effect` (on jdk8). 

The application doesn't use any annotations or `Array[String]` anywhere.

Sadly there is no file name or line number in the output, so it is hard to shrink it to a repro case.

**Comment by bplommer** [comment]
I'm also getting this when trying to cross-build fs2-kafka with SBT - see linked issue above.

**Comment by jtjeferreira** [comment]
also facing this "error" but since there is no file name or line number in the output is hard to understand what might be the problem...

**Comment by rodrigogdea** [comment]
Same here... adding code inside quoted code (macro), getting:
```
scalac: Found:    Seq[scala.annotation.Annotation]
Required: Array[String]
```

**Comment by DoSOfRedRiver** [comment]
@kubukoz did you have a chance to find what was the problem?

**Comment by kubukoz** [comment]
@DoSOfRedRiver bloop 1.4.11 and scala 3.1.0 seem to work fine (using cats from 2.13 interop again). sbt is 1.6.1, but exporting to bloop with 1.5.6 also seems to work.

**Comment by kubukoz** [comment]
Sorry, forgot to mention, if you're still seeing similar issues it might deserve another ticket 😅
