### ISSUE TITLE
Unexpected resolution error when using Bloop on Gradle 6.1

### ISSUE THREAD

**Issue by TheDaemoness** [scalacenter/bloop#1286]
To produce this issue, I initialized an empty Gradle 6.1 project with an empty `settings.gradle`, then followed the instructions [here](https://scalacenter.github.io/bloop/docs/build-tools/gradle/), resulting in a `build.gradle` containing the following:

```gradle
buildscript {
  repositories {
    mavenCentral()
  }

  dependencies {
    classpath 'ch.epfl.scala:gradle-bloop_2.12:1.4.1'
  }
}

allprojects {
  apply plugin: 'bloop'
}
```
When attempting to run `./gradlew tasks`, what follows is an attempt to fetch `gradle-core:5.0`, which fails:
```
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not find org.gradle:gradle-core:5.0.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/org/gradle/gradle-core/5.0/gradle-core-5.0.pom
       - https://plugins.gradle.org/m2/org/gradle/gradle-core/5.0/gradle-core-5.0.pom
     Required by:
         project : > ch.epfl.scala:gradle-bloop_2.12:1.4.1
```
There is a fix which appears to be functional, which is to add the following to the `buildscript.repositories` block:
```gradle
maven {
  url "https://repo.gradle.org/gradle/libs-releases-local/"
}
```
Doing so appears to completely fix the issue; for minimal Scala projects, the generated `.bloop/*.json` files appear to be correct. However, I'm skeptical about how sane that fix is going forward, hence the bug report.

**Comment by jvican** [comment]
@TheDaemoness Thank you, this is a great ticket. Yes, it looks like that workaround you're using should not be needed 🤔 I'll look into this, I think the problem is that gradle-core should be a runtime dependency and it isn't.
