### ISSUE TITLE
How to pass --full-stacktrace to java?

### ISSUE THREAD

**Issue by davidmlw** [scalacenter/bloop#1294]
`bloop run -p project -m main args` is fast. But when there is an error, it only prints a short stacktrace and it saying to get a full stack trace, "rerun with --full-stacktrace if you wish to see..."

`--full-stacktrace` should be an option to java, and I refer the document "-J--full-stacktrace", it is rejected either by bloop, or (of course) by main.

I googled and didn't find the answer.

**Comment by jvican** [comment]
Hey @davidmlw, thanks for reporting. Just to clarify, does `bloop run -p project -m main args -- -J--full-stacktrace` not work? Note that it's specified after `--`.

**Comment by jvican** [comment]
Closing because I think that answers your question, feel free to reopen if it doesn't.

**Comment by davidmlw** [comment]
I tried:
`bloop run --projects progect --main main -- mainArg1 mainArg2 -J--full-stacktrace`
`bloop run --projects progect --main main -- mainArg1 mainArg2 -- -J--full-stacktrace`
`bloop run --projects progect  -J--full-stacktrace --main main -- mainArg1 mainArg2`
`bloop run --projects progect  --main main -- -J--full-stacktrace -- mainArg1 mainArg2`
`bloop run --projects progect --skip-jargs -J--full-stacktrace --main main -- mainArg1 mainArg2`

But they all returned:
```
Unrecognized option: --full-stacktrace
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

**Comment by davidmlw** [comment]
I have also tried to invoke main directly from java -cp ....., I still met same message, requiring rerun with "--full-stacktrace". And I still  have no idea where to put "--full-stacktrace" even directly from command line java.

**Comment by jvican** [comment]
Is that option for the java command or the javac compiler? If it is for the compiler you need to add it to the options field of the java object in the configuration file.

**Comment by davidmlw** [comment]
I compiled a jar and run the jar from Java directly. **So it is not a bloop issue, I think.** I googled and saw some similar questions, but it seems java does not have a simple solution for this.
