### ISSUE TITLE
Publish Bloop launcher for Scala 2.13

### ISSUE THREAD

**Issue by olafurpg** [scalacenter/bloop#1295]
Currently, the Bloop launcher is only available for Scala 2.12. It would be nice if the launcher was also available for 2.13 so that downstream applications like Metals can upgrade to 2.13 even if the Bloop server runs on 2.12.

**Comment by jvican** [comment]
Thanks for the feature request. How urgent is this?

**Comment by olafurpg** [comment]
It's not urgent at all. I just wanted to open an issue to track this since I saw there wasn't any related open ticket. Feel free to close if you prefer, I will work on this myself if it becomes urgent.

**Comment by jastice** [comment]
Now that we changed the IntelliJ Scala plugin to 2.13, this suddenly became relevant for us :D

**Comment by keynmol** [comment]
Can I help with this?

If I understand correctly all the module dependencies of `launcher` need to be made into cross-builds, and dependencies fixed (like with [snailgun](https://github.com/jvican/snailgun/pull/2)) or updated.

There's one bigger problem though - case-app from `frontend` is quite old and not published for 2.13, and newer versions have a dramatically different API (plus they're published under @alexarchambault's name - is this the same case-app?)

**Comment by jvican** [comment]
@keynmol Hey Anton, it'd be great if you can help cross-compiling the launcher to Scala 2.13. Given that upgrading the whole project to Scala 2.13 is going to be a difficult and performance-sensitive task, I prefer to do it myself since I'll likely need to run some performance checks. However, the launcher is not performance sensitive and any help there is appreciated.

**Comment by ckipp01** [comment]
Hey @keynmol! Were you still planning on tackling this?

**Comment by keynmol** [comment]
Hey @ckipp01!

I was waiting for snailgun to be published, but the case-app yak is much bigger and harder to shave (launcher needs frontend for tests, and frontend depended on a very old version of case-app not published for 2.13).

I've opened a draft PR where I've started the conversion: https://github.com/scalacenter/bloop/pull/1425 

So if you can provide advice on how to convert the rest of the old case-app models to newer version - it will help move things along :)

**Comment by ckipp01** [comment]
> So if you can provide advice on how to convert the rest of the old case-app models to newer version - it will help move things along :)

😬 sorry, I'm really not the person to ask for this as I'm also pretty unfamiliar with the Bloop code base. With that said, I also played around with seeing what was needed for the case app update and also hit on some pretty large roadblocks like you have. As you'd expect, it's changed a lot in the past 3 years, and I'm _assuming_ the version that is currently being used was a forked/published version. I don't see it listed anywhere under the Scala Center repos, so I have no idea what may have changed in that forking, or if that's even what happened.

I see that you've put the case app update on top of the other stuff, and again, totally not my call, but maybe consider doing that update as a standalone update. It may be easier to review that as a separate pr first to update case app, and then put everything else needed for the cross to 2.13 in another pr. My guess is that anything to help the current maintainers review this in chunks will be much appreciated.

**Comment by tgodzik** [comment]
The launcher is now published thanks to @kpodsiad !
