### ISSUE TITLE
Couldn't retrieve module ch.epfl.scala:compiler-bridge_2.13:1.3.0-M4+42-5daa8ed7:compile

### ISSUE THREAD

**Issue by user753** [scalacenter/bloop#1298]
about
```
bloop v1.4.1

Using Scala v2.12.8 and Zinc v1.3.0-M4+42-5daa8ed7
Running on Java JDK v11.0.6 (C:\Program Files\AdoptOpenJDK\jdk-11.0.6.10-hotspot)
  -> Supports debugging user code, Java Debug Interface (JDI) is available.
Maintained by the Scala Center (Jorge Vicente Cantero, Martin Duhem)
```
How to fix it?

**Comment by jvican** [comment]
Thanks for reporting. Are you behind a proxy (check [this](https://github.com/scalacenter/bloop/issues/1293) if you are)? Are you getting the error from the CLI or through another tools such as Metals?
  
It would be good you share some reproduction steps to make sense of your error.

**Comment by user753** [comment]
>Are you behind a proxy (check this if you are)?

Yes, I have added proxy settings to `.jvmopts` and I also have tried to run bloop with `-Dhttps.proxyHost` parameters. Is there any simple way to check if bloop has a correct proxy settings?

> It would be good you share some reproduction steps to make sense of your error.
```
sbt new scala/scala-seed.g
add plugins.sbt with addSbtPlugin("ch.epfl.scala" % "sbt-bloop" % "1.4.1")
sbt bloopInstall
bloop compile root
```

**Comment by jvican** [comment]
Have you exited the bloop server after those changes? Otherwise, the current server won't pick them up. Make sure that you do `bloop exit` and then `bloop about`. `bloop about` should log that a new server is being started.

**Comment by user753** [comment]
Thanks. AFter restart the first time I run `bloop compile` it shows full stack trace for the error instead of only 'Couldn't retrieve module ch.epfl.scala:compiler-bridge_2.13:1.3.0-M4+42-5daa8ed7:compile` so I was be able to figure out what is the problem (some error with proxy configuration) 

I think is would be helpful if bloop shows full stack trace for the errors every time.

**Comment by jvican** [comment]
> I think is would be helpful if bloop shows full stack trace for the errors every time.
  
I agree, this is some area where I'd like us to improve. Thanks.
