### ISSUE TITLE
Rework instructions to be cross-platform

### ISSUE THREAD

**Issue by jvican** [scalacenter/bloop#131]
There are lots of assumptions in our instructions that rely on the users owning a Linux or OSX machine. For example, paths:
  
> The script will create the executables ~/.bloop/bloop-server, ~/.bloop/bloop-shell and ~/.bloop/bloop-ng.py

It does not have a solid way to use bloop. I believe that in the next 0.2 release, we can do a much better job at solving these two issues.

**Comment by olafurpg** [comment]
I can recommend setting up appveyor, it's quite easy to do and I've found the appveyor CI quite fast to run

**Comment by jvican** [comment]
Oh, absolutely. There's a wip PR to add appveyor in Zinc https://github.com/sbt/zinc/pull/370 -- I also had a smooth experience with it.

**Comment by jvican** [comment]
This can be closed when #216 is merged.
