### ISSUE TITLE
Gradle plugin doesn't handle `scalaCompilerPlugins`

### ISSUE THREAD

**Issue by lloydmeta** [scalacenter/bloop#1312]
When you use `scalaCompilerPlugins` to add a scalac plugin as per [the docs](https://docs.gradle.org/current/userguide/scala_plugin.html#sec:scala_compiler_plugins), it doesn't appear to work or get picked up by the bloop definition from `bloopInstall`.

For instance, I have a project where I have `-Xfatal-warnings` enabled and added the [`silencer`](https://github.com/ghik/silencer) plugin to selectively silence deprecation errors. While it works in Gradle, the generated bloop project errors out despite adding `silent` annotations.

Example min repro project: https://github.com/lloydmeta/bloop-with-gradle-and-silencer

**Comment by olafurpg** [comment]
Thank you for reporting! The silencer issue may be related to https://github.com/scalameta/scalameta/pull/2065 instead of Bloop. If you open the `.bloop/*.json` fields, can you check if the silencer plugin is enabled via `-Xplugin:/path/to/silencer.jar` in the Scala compiler options field?

**Comment by Arthurm1** [comment]
I don't think we handle the `scalaCompilerPlugins` option.  I'll look to add it.

For now you can do something like...
```groovy
configurations {
    silencerPlugin
}

dependencies {
    silencerPlugin "com.github.ghik:silencer-plugin_$scalaVersion:1.7.0"
}

tasks.withType(ScalaCompile) {
    scalaCompileOptions.additionalParameters = [
      "-Xplugin:" + configurations.silencerPlugin.asPath
    ]
}
```

**Comment by lloydmeta** [comment]
@Arthurm1 indeed; just confirmed that this works.
