### ISSUE TITLE
Does not work with coursier managed Java

### ISSUE THREAD

**Issue by mushtaq** [scalacenter/bloop#1324]
Trying latest bloop 1.4.2, sbt 1.3.12, IntelliJ 2020.1.2 on MacOs catalina.

Loading in IntelliJ fails when it calls `bsp --protocol local --socket .....` because it can not find java executable.

I am using [coursier to manage Java](https://get-coursier.io/docs/cli-java). As described in the docs, JAVA_HOME is correctly set. So `java` command work as expected on Mac. 

I think problem is is related to [this issue](https://github.com/coursier/coursier/issues/1684). If a third party program is using `/usr/libexec/java_home` to determine JAVA_HOME instead of the provided env variable, it does not work on Mac where cs is managing the jvm.

It will be nice if bloop works with coursier managed jvms!

**Comment by jvican** [comment]
Thanks for reporting! I agree this would be nice. Is this something you could contribute to the project?

**Comment by mushtaq** [comment]
Maybe eventually, not right now.

**Comment by tgodzik** [comment]
Bloop now uses coursier to download it's own JVM if not found
