### ISSUE TITLE
Implement standalone runner+installer wrapper script

### ISSUE THREAD

**Issue by lloydmeta** [scalacenter/bloop#1333]
Just floating this idea out there; it might be nice to have a wrapper runner script like `gradlew` that auto downloads and installs Bloop and runs it.

**Comment by jvican** [comment]
Thanks for the question. You can achieve that with our launcher through coursier: `coursier launch ch.epfl.scala:bloopgun_2.12:latest.release -- projects` will launch bloop in the background, connect to it and run `projects`.
