### ISSUE TITLE
Missing test frameworks for integration test projects

### ISSUE THREAD

**Issue by lloydmeta** [scalacenter/bloop#1335]
### Problem

Gradle supports having integration-tests under a different source set with an accompanying task ([docs](https://docs.gradle.org/current/userguide/java_testing.html#sec:configuring_java_integration_tests)), but it seems like the [bloop Gradle plugin](https://scalacenter.github.io/bloop/setup#gradle) doesn't work with this, because the resulting bloop project definition lacks the `project.tests` stanza, causing attempts to run tests to do nothing and log a warning as follows:

```shell
[W] Missing configured test frameworks in bloop-on-gradle-with-its-it
===============================================
Total duration: 0ms
No test suites were run.
===============================================
```

### Probable cause

I think this is because all the decisions in [`BloopConverter`](https://github.com/scalacenter/bloop/blob/master/integrations/gradle-bloop/src/main/scala/bloop/integrations/gradle/model/BloopConverter.scala) to check whether a source set is test-related or not is driven by testing the source set name to see if it's `test`

https://github.com/scalacenter/bloop/blob/b96374d7c30684cbf8afd5dbac6cd4979fd60747/integrations/gradle-bloop/src/main/scala/bloop/integrations/gradle/model/BloopConverter.scala#L69

In particular, I think this is the bit that causes the bloop test config (with its frameworks) to not be defined when the source set name is not `test`:

https://github.com/scalacenter/bloop/blob/b96374d7c30684cbf8afd5dbac6cd4979fd60747/integrations/gradle-bloop/src/main/scala/bloop/integrations/gradle/model/BloopConverter.scala#L407-L414

### Possible fix

I think we can naively "fix" this by simply always returning `Some(Config.Test.defaultConfiguration)` from 

https://github.com/scalacenter/bloop/blob/b96374d7c30684cbf8afd5dbac6cd4979fd60747/integrations/gradle-bloop/src/main/scala/bloop/integrations/gradle/model/BloopConverter.scala#L407

but I'm not sure whether always having the test config defined for projects would break anything.

Alternatively, we'd need an improved way of detecting whether or not a source set is test related, one that looks at more than just the name (what though?)

### Min repo

I have a min repro [here](https://github.com/lloydmeta/bloop-on-gradle-with-its); the only differences between it and the official guide are:
* the integration-test-hook has been added as a plugin to keep things DRY in case we want to test with subprojects
* the integration tests are located in `src/it`, sbt-style

### Workaround

One can make this work by copying-and-pasting `project.tests` from `$projectname-test.json`, then:

```shell
❯ bloop test bloop-on-gradle-with-its-it
MehItSpec:
- should w/e
Execution took 16ms
1 tests, 1 passed
All tests in com.beachape.MehItSpec passed

===============================================
Total duration: 16ms
All 1 test suites passed.
===============================================
```

**Comment by Arthurm1** [comment]
Thanks for the extensive reproduction.

I'm not against adding test configs to all non-main projects as I think integration tests are an important use-case.

I'll have a look at whether we can make this more intelligent by maybe checking if Gradle `Test` tasks are associated with source sets and then setup test configs only for those projects - or something along these lines.

**Comment by jvican** [comment]
Great ticket, thanks for reporting!

> I'm not against adding test configs to all non-main projects as I think integration tests are an important use-case.

Me neither. I think this should be fine because it's just a configuration tweak. It would be a different story if this meant that we add test jars to the classpath, which we don't do, it's something only gradle does.
