### ISSUE TITLE
Missing required configuration entry: cookie.encryption.key

### ISSUE THREAD

**Issue by abhijeetardale** [scalacenter/bloop#134]
most of test failed with common error

[error] application - Missing required configuration entry: cookie.encryption.key
Exception encountered when attempting to run a suite with class name: TestSpec ABORTED 
java.lang.SecurityException: Missing required configuration entry: cookie.encryption.key

However all these tests are running smoothly with sbt test

**Comment by Duhemm** [comment]
Thanks for the report!

I strongly suspect that this happens because either resources are not copied over (see #102), or because these tests require forking and passing options to the JVM (see #111). Both these things will be supported in the future.

Can you confirm?

**Comment by abhijeetardale** [comment]
Hi, 
with recent changes, I am not getting the above error but couple of test got failed with "com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'akka'" which is already reported (#[102](https://github.com/scalacenter/bloop/issues/102)). I tried by copying the resources as suggested but doesn't worked.

Also after running the test with bloop-ng.py -- test -p my-project-test, its not showing the test execution summary like scalatest or junit(number of tests passed/failed). It will great to have such feature.

**Comment by Duhemm** [comment]
> Also after running the test with bloop-ng.py -- test -p my-project-test, its not showing the test execution summary like scalatest or junit(number of tests passed/failed). It would be great to have such feature.

That's fixed as part of #136.

Is it an open source project that we can try directly? Otherwise, can you tell us what kind of application this is (Play, Akka HTTP, etc.)?

Thanks again for the report.

**Comment by abhijeetardale** [comment]
Hi Duhemm, thanks for update. 
No its not open source project. Its play application.

**Comment by Duhemm** [comment]
@abhijeetardale Can you confirm that #149 fixes this issue?

**Comment by jvican** [comment]
@abhijeetardale Happy New Year! It would be awesome if you can tell us if latest master fixes your issue, so that we can finally close this issue and call it a day :smile:.
