### ISSUE TITLE
How to install latest version with coursier?

### ISSUE THREAD

**Issue by user753** [scalacenter/bloop#1350]
```
coursier --version
2.0.0-RC6-23
```
I tried
```
coursier uninstall bloop
coursier install bloop
```
But my version is still
```
bloop --version
bloop v1.4.0-RC1-94-a2be783d
```

**Comment by jvican** [comment]
Hey @user753, thanks for reporting. You need to exit bloop with `bloop exit` after you install it because the old server is still running in the background.
