### ISSUE TITLE
bloop .plist on os X

### ISSUE THREAD

**Issue by vito-c** [scalacenter/bloop#1353]
I installed bloop via homebrew but the plist was not there. So `brew services start` doesn't work.

```
> brew install bloop
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> New Formulae
osm
==> Updated Formulae
Updated 5 formulae.

Warning: scalacenter/bloop/bloop 1.4.3 is already installed and up-to-date
To reinstall 1.4.3, run `brew reinstall bloop`
[12:11] ~> bloop about
bloop v1.4.2

Using Scala v2.12.8 and Zinc v1.3.0-M4+44-1e74f1f1
Running on Java JDK v1.8.0_231 (/Library/Java/JavaVirtualMachines/jdk1.8.0_231.jdk/Contents/Home/jre)
  -> Supports debugging user code, Java Debug Interface (JDI) is available.
Maintained by the Scala Center (Jorge Vicente Cantero, Martin Duhem)
```
This was also really confusing. Is the version in correct  in brew?

**Comment by jvican** [comment]
Hey! Thanks for opening the ticket. Bloop no longer supports brew services, you can find that information in the release notes for 1.4.0.

**Comment by dpdearing** [comment]
I also had this same problem and was really confused about the conflicting documentation.  The current Bloop documentation for the Homebrew (macOS) package manager has a "Running the server in the background" section that says:

> ### Running the server in the background
> 
> The Homebrew formula installs a Mac OS property list (plist) to start up the Bloop server automatically when you log into your machine. The property list spares you from the cumbersome process of starting the build server before running any bloop CLI command.

This contradicts the information when running `brew services start bloop` that said:
```
Error: Formula `bloop` has not implemented #plist or installed a locatable .plist file
```

Finding this issue and the 1.4.0 release notes makes it appear that it's just the Homebrew documentation that is misleading.  I haven't resolved this locally yet, but perhaps that "Running the server in the background" section for all package managers should really match the coursier instructions?  If I had not dug into the closed issues I don't know that I would have figured this out.

**Comment by meldmy** [comment]
@jvican Can you help us? I have the same issue as @dpdearing

**Comment by tgodzik** [comment]
I think the current best way is to install via coursier. Once you run Bloop the first time it will start in the background, so there is no real reason to run it via services. We might need update the documentation to reflect the current recommendations better.
