### ISSUE TITLE
Support Scala.js v1.1.1

### ISSUE THREAD

**Issue by antekone** [scalacenter/bloop#1366]
Scala.js is currently at version 1.1.1, but Bloop doesn't seem to support it in `link` step:

```
$ bloop compile xxxx
$ bloop link xxxx
[E] Expected compatible Scala.js version [0.6, 1.0], 1.1.1 given
```

**Comment by jvican** [comment]
Thanks for the suggestion! @antekone You're right, this is long overdue.
