### ISSUE TITLE
Gradle applicationDefaultJvmArgs doesn't get exported

### ISSUE THREAD

**Issue by aishfenton** [scalacenter/bloop#1377]
I have Gradle project that I export to Bloop, which uses the Gradle [application plugin](https://docs.gradle.org/current/userguide/application_plugin.html). One of the config options for that plugin is `applicationDefaultJvmArgs`. This lets you specify Jvm arguments to use when running the app. 

These jvm args don't get exported to the .bloop config json files (the MainClass config does however)

Example:

```groovey
application {
    mainClass = 'com.myorg.MyAppMain'
    applicationDefaultJvmArgs = ['-Dgreeting.language=en, -Xmx16g']
}
```

Results in the following `.bloop/my_app.json` config

```json
        "platform": {
            "name": "jvm",
            "config": {
                "home": "/Library/Java/JavaVirtualMachines/jdk1.8.0_221.jdk/Contents/Home",
                "options": [
                    "-Xmx1024mb"
                ]
            },
            "mainClass": [
                "com.myorg.MyAppMain"
            ],
```

**Comment by tgodzik** [comment]
Thanks for reporting! I think this might be fixable around here:  https://github.com/scalacenter/bloop/blob/master/integrations/gradle-bloop/src/main/scala/bloop/integrations/gradle/model/BloopConverter.scala#L410

If the test task is empty we should try to get applicationDefaultJvmArgs - should not be too hard I think. Though I am not sure why we are only getting information from the test task there :thinking:

**Comment by Arthurm1** [comment]
>Though I am not sure why we are only getting information from the test task there 🤔

Probably because I didn't know `applicationDefaultJvmArgs` existed :smiley:

I'm just waiting on [this](https://github.com/gradle/gradle/issues/14662) to hopefully get some info on the recommended way to properly extract the `mainClass` and then I'll add `applicationDefaultJvmArgs` in too

**Comment by jvican** [comment]
Thanks for looking at this @Arthurm1! Looking forward to supporting default  jvm args, I've seen them be used often in OSS builds.
