### ISSUE TITLE
Issue with compiling `@main` annotation when there is extra lines

### ISSUE THREAD

**Issue by ckipp01** [scalacenter/bloop#1380]
Just to make sure it's tracked here, I figured I'd create this and link it to the [issue in Metals](https://github.com/scalameta/metals/issues/2117).

So I've been playing around with this a bit to see if I can consistently reproduce it, and I can. It's very odd because it's a certain combination of things based on empty lines. For example, if you create a new project with the [Dotty g8 template](https://github.com/lampepfl/dotty.g8) and change the main method to be as follows at the top level:

Just one blank line, no package declaration. Bloop has no issue with this.
```scala

@main def main(): Unit = {
  println("Hello world!")
  println(msg)
}

def msg = "I was compiled by dotty :)"
```
Add one more empty line on top and you'll get the following error:

This...
```scala
 
 
@main def main(): Unit = {
  println("Hello world!")
  println(msg)
}

def msg = "I was compiled by dotty :)"
```

Produces this:

```
❯ bloop run root
Compiling root (1 Scala source)
[E] [E1] src/main/scala/Main.scala:2:1
[E]      Found:    main
[E]      Required: scala.annotation.Annotation
[E]      L2: @main def main(): Unit = {
[E]          ^
[E] src/main/scala/Main.scala: L2 [E1]
Compiled root (224ms)
[E] Failed to compile 'root'
```

Add in a package declaration and make sure there is only one line between package declaration and main method, no issue.
```scala
package example

@main def main(): Unit = {
  println("Hello world!")
  println(msg)
}

def msg = "I was compiled by dotty :)"
```

If you add in another blank line, you'll get the issue. The same thing happens if you add a blank line in at the top of the method.
```scala
package example

@main def main(): Unit = {

  println("Hello world!")
  println(msg)
}

def msg = "I was compiled by dotty :)"
```

All of the cases produce the same error from bloop. Note that all of these can be compile and ran with sbt with no issue.

**Comment by tgodzik** [comment]
Thanks for the reproduction @ckipp01 ! I wonder how it's influenced by some missing features when it comes to Scala 3 and Zinc integration. @jvican You mentioned that there might be some issues when it comes to Scala 3, if you find the time could you mention what you think needs still to be done make Bloop and Scala 3 work 100% ?

**Comment by kpodsiad** [comment]
@tgodzik Does dropping the fork of Zinc help with that issue?

**Comment by tgodzik** [comment]
I haven't check that yet, would need to build my fork and test it there, but I haven't actually seen this reproduced recently.

**Comment by kpodsiad** [comment]
ok, I'll try to reproduce it with the current bloop and then with your version. Will it be safe to close this and related issues if there aren't any issues?

**Comment by kpodsiad** [comment]
I can't get compilation error, current bloop seems to work.

**Comment by ckipp01** [comment]
I'll go ahead and close then. I haven't looked back at this in a long time or noticed it so closing.
