### ISSUE TITLE
Consider migrating back to sbt/zinc

### ISSUE THREAD

**Issue by Duhemm** [scalacenter/bloop#1383]
Currently, Bloop is using a fork of Zinc (https://github.com/scalacenter/zinc) which is a bit outdated compared to sbt/zinc (https://github.com/sbt/zinc).

At the time, this fork was introduced to support features that weren't available in sbt/zinc, such as build pipelining for instance. In the meantime, sbt/zinc got support for build pipelining and received bug fixes and performance improvements. Porting these changes to our fork of Zinc would require a considerable effort.

Similarly, migrating to mainline Zinc is no small task and will most likely require a lot of changes to Bloop.

I don't think that Bloop benefits from using a fork of Zinc anymore. I'd be in favor of migrating Bloop back to sbt/zinc to get the recent improvements and avoid the cost of maintaining a fork of Zinc.

**Comment by tgodzik** [comment]
We are starting to work on this, based on @Duhemm feedback we plan to do the migration in two main step steps.

1. Remove custom build pipeling and migrate to newest zinc to benefit from all the recent improvements -> Bloop 1.5.0
This step would include:
 - run benchmarks on current state
 - simplify the tests removing any that touch pipelining, remove the custom build pipelining and migrate to the Zinc 1.3.8. 
 - run benchmarks again to see the change in performance

2. Use Zinc's pipelining while contributing any fixes to Zinc itself. -> Bloop 1.5.1
This step would also include running the benchmarks and most likely restating some tests for pipeling that were previously removed.

@jvican let me know if there is something that is totally off with this plan. I know that removing pipelining means a lot of the previous work goes to waste, but having two implementations of pipelining is not maintainable for us in the long run.

**Comment by Duhemm** [comment]
@tgodzik I think we can close this one? Congrats and thank you 😄

**Comment by tgodzik** [comment]
Sure! I added a new issue about pipelining.
