### ISSUE TITLE
bloop randomly starts burning CPU when idle

### ISSUE THREAD

**Issue by tpolecat** [scalacenter/bloop#1385]
I find that from time to time bloop consumes 25-30% of my CPU even when it's idle and no clients are connected. A thread dump indicated 2066 `AsyncReporter` threads, which seems suspicious (see [dump.txt](https://github.com/scalacenter/bloop/files/5411110/dump.txt)).

**Comment by Duhemm** [comment]
Reproduction in scalacenter/bloop with Bloop 1.4.4:

```sh
for in in $(seq 1 1000); do bloop compile socketes; done
```

![image](https://user-images.githubusercontent.com/1765926/96685007-cd874980-137c-11eb-9121-010685996959.png)

**Comment by ornicar** [comment]
Thank you for the fix. How can I go about using it?

I checked out https://scalacenter.github.io/bloop/docs/contributing-guide, didn't find artifacts in the github actions https://github.com/scalacenter/bloop/actions/runs/319367801, and tried building it myself without success:

```
[error] stack trace is suppressed; run last bloopgunShaded / Compile / packageBin for the full output
[error] stack trace is suppressed; run last sbtBloop10Shaded / Compile / packageBin for the full output
[error] stack trace is suppressed; run last sbtBloop013Shaded / Compile / packageBin for the full output
[error] stack trace is suppressed; run last launcherShaded / Compile / packageBin for the full output
[error] (bloopgunShaded / Compile / packageBin) java.lang.UnsupportedClassVersionError: org/pantsbuild/jarjar/util/CoursierJarProcessor
[error] (sbtBloop10Shaded / Compile / packageBin) java.lang.UnsupportedClassVersionError: org/pantsbuild/jarjar/util/CoursierJarProcessor
[error] (sbtBloop013Shaded / Compile / packageBin) java.lang.UnsupportedClassVersionError: org/pantsbuild/jarjar/util/CoursierJarProcessor
[error] (launcherShaded / Compile / packageBin) java.lang.UnsupportedClassVersionError: org/pantsbuild/jarjar/util/CoursierJarProcessor
```
Using java `openjdk version "1.8.0_265"`
