### ISSUE TITLE
Java errors/warnings have no column position info

### ISSUE THREAD

**Issue by Arthurm1** [scalacenter/bloop#1389]
When Bloop compiles a _Java_ source file that contains errors/warnings it will report the correct line number but the column is always zero.
This leads directly into Metals and highlighting in VSCode.

In [ZincInternals](https://github.com/scalacenter/bloop/blob/dbacf644f3a7f0e3e694c9c1a1e95e60376b5a2c/backend/src/main/scala/sbt/internal/inc/bloop/ZincInternals.scala#L18-L33) the `xsbti.Position` diagnostic class is transformed into something Bloop can handle but the column number always results in zero as `Position#startLine`, `Position#pointer`, `Position#startColumn` are all `null`.

`Position#line`, `Position#startOffset` and `Position#endOffset` all seem to contain the correct data to highlight the error but `Position#startOffset` and `Position#endOffset` contain offset positions from the start of the file, not the column offsets for the line.  I don't think Bloop can then deal with this as I think it expects the offsets to be the column indexes of `Position#startLine` and `Position#endLine`.

This `Position` data is generated by Zinc in [DiagnosticsReporter](https://github.com/sbt/zinc/blob/9cfd854e06fdcaa0a92536435ac209720520c94e/internal/zinc-compile-core/src/main/scala/sbt/internal/inc/javac/DiagnosticsReporter.scala#L124-L127).  Should the correct line and column offsets (`Position#startLine`, `Position#startColumn`, `Position#endLine`, `Position#endColumn`) be generated here as this class seems to already be interrogating the entire file to produce the line content?

I get this issue using Java 11 on WSL2.  Scala errors/warnings are highlighted correctly

**Comment by tgodzik** [comment]
Thanks for reporting! I think it would be best to have it tackled in zinc itself, as sbt seems to have the same problem:
`/home/tgodzik/Documents/workspaces/dotty-sample/src/main/java/example/Other.java:4:1:`

So best to fix it or at least report in zinc, but we would need to first migrate to the main zinc fork from our own.

**Comment by tgodzik** [comment]
Thanks for the work in zinc! We will need to now address https://github.com/scalacenter/bloop/issues/1383 in order to get all the zinc improvements, but I think we can close it now.
