### ISSUE TITLE
Installing on ArchLinux

### ISSUE THREAD

**Issue by vito-c** [scalacenter/bloop#1390]
Hi I went to install bloop on arch and was unable to run bloop.

I did the following
- `yay -Sy bloop`
- `$ systemctl --user enable bloop`

Which gave me the error:
```
Failed to enable unit: Unit file bloop.service does not exist.
```

When I try to run the console I get:
```
$ bloop
error: Missing CLI command for Bloop server!
```

Everything seems to be installed though because I can do `bloop compile <project>` which gives me:
```
Compiled myproject (14431ms)
[E] Failed to compile 'myproject'
```

**Comment by tgodzik** [comment]
Thanks for reporting! The arch build definition is defined here: https://github.com/scalacenter/bloop/blob/master/project/ReleaseUtils.scala#L255 

@TheElectronWill do you have any idea what is going on?

**Comment by TheElectronWill** [comment]
As explained on [AUR](https://aur.archlinux.org/packages/bloop/), the systemd service is no longer (for quite some time now) included in the `bloop` package. You need to install `bloop-systemd` too.

**Comment by vito-c** [comment]
@TheElectronWill will that fix the CLI error as well?
```
$ bloop
error: Missing CLI command for Bloop server!
```

**Comment by tgodzik** [comment]
> @TheElectronWill will that fix the CLI error as well?
> 
> ```
> $ bloop
> error: Missing CLI command for Bloop server!
> ```

I think that one is because you need to provide a command for Bloop to run. 

`error: Missing CLI command for Bloop server!` is valid here due to the fact that indeed no command is provided. Happens the same if it's installed via courier.

**Comment by vito-c** [comment]
I was going off the documentation outlined here: https://scalacenter.github.io/bloop/setup#aur which is why I didn't know the extra `bloop-systemd` package was needed :)
