### ISSUE TITLE
Automatic generation of bloop configuration files

### ISSUE THREAD

**Issue by jvican** [scalacenter/bloop#140]
The idea behind bloop is that it only understands its own configuration files, which have to be written from several mainstream build tools in order to be used. One small issue with this is that whenever users change the project definitions, they have to run `bloopInstall` or a similar task in other build tools to generate new configuration files.
  
This ticket proposes to change the status quo to perform such generation automatically. At least, Maven and sbt give us the hooks to do so (one via build lifecycle subscription and the other one via `Def.initialize`).
  
The idea is that this process has to be transparent to the user so that the cognitive overhead of using bloop is even smaller. In particular, it has to:
  
* Be blazingly fast (avoiding the project compilation as it does now).
* Be cached (in order to allow us to skip the process if nothing changed).
* Be incremental at the project level (if a project definition changed, we only have to generate the config file for it).

**Comment by nafg** [comment]
Not sure I understand this ticket -- when exactly would automatic generation run?

**Comment by jvican** [comment]
The automatic generation of configuration files a loaded builds and the execution of dependency resolution and source/resource generation are executed. Depending on the build tool, the automatic generation is done one way or another. On Maven, for example, the generation would need to happen in its build lifecycle. On sbt, `Def.initialize` allows us to run any task we want.

Not all build tools would be candidates for this automatic generation. The generation depends on data from the build, and sometimes that data has to be produced (like resolving the dependencies to find a project's classpath). In reality, only users of build tools like bazel, gradle and sbt (in that order) will benefit from the automatic generation because it will be faster than in other build tools.

**Comment by nafg** [comment]
What I mean is, from the user's perspective what actions would cause it to run

**Comment by jvican** [comment]
I already told you! Look into `Def.initialize` or read about Maven's lifecycle. It's done differently depending on the build tool, but the idea is that it will be done as soon as all the build is loaded, automatically.

**Comment by nafg** [comment]
I couldn't find anything about Def.initialize doing something like that.
But it sounds like in short, instead of doing `;reload;bloopInstall` one
would just do `reload`?

**Comment by jvican** [comment]
For sbt users, yeah. In fact, we already do that but for the configuration files of the build project, instead of the projects defined in the build.

**Comment by jvican** [comment]
This is an implicit ticket covered in https://github.com/scalacenter/bloop/issues/316
