### ISSUE TITLE
Attempting to install on macOS Big Sur (11.0.1) fails via Homebrew.

### ISSUE THREAD

**Issue by jsatk** [scalacenter/bloop#1401]
```
➜  .dotfiles git:(master) ✗ brew install scalacenter/bloop/bloop
Warning: You are using macOS 11.0.
We do not provide support for this released but not yet supported version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or any other official channels. You are responsible for
resolving any issues you experience while you are running this
released but not yet supported version.

==> Installing bloop from scalacenter/bloop
bloop: Java 1.8+ is required for this software.
Install AdoptOpenJDK with Homebrew Cask:
  brew cask install adoptopenjdk
coursier: Java 1.8+ is required for this software.
Install AdoptOpenJDK with Homebrew Cask:
  brew cask install adoptopenjdk
Error: Unsatisfied requirements failed this build.
➜  .dotfiles git:(master) ✗ brew cask list | grep jdk
Warning: Calling brew cask list is deprecated! Use brew list --cask instead.
adoptopenjdk
```

Oddly running `brew install coursier/formulas/coursier` and `brew install adoptopenjdk` works just fine.

**Comment by tgodzik** [comment]
Thanks for reporting! Did it break with `1.4.5`? I might have broke something there. Though it seems like the second 
`brew cask install adoptopenjdk`

fails due to the fact it's already installed? Anyone able to try to fix it on MacOS ? I do not have access to any machine with the system.

**Comment by jsatk** [comment]
> Thanks for reporting! Did it break with `1.4.5`? I might have broke something there. Though it seems like the second
> `brew cask install adoptopenjdk`
> 
> fails due to the fact it's already installed? Anyone able to try to fix it on MacOS ? I do not have access to any machine with the system.

It's definitely already installed on this machine. I use a `Brewfile`. So when I do `brew install` it just skips over the installed ones. The behavior of this is unique.

**Comment by sergei-grigorev** [comment]
I downloaded bloop.rb locally) where I replaced dependency on `openjdk@11` as recommended by brew in its output. Then brew build it from file  (`--build-from-source ./bloop.rb`), it downloaded coursier, openjdk@15 instead of openjdk@11 and then bloop was also installed and it works fine now.

**Comment by tgodzik** [comment]
@sergei-grigorev That sounds cool! Would you be able to create a PR with those changes for https://github.com/scalacenter/homebrew-bloop ?

**Comment by dbingham** [comment]
@tgodzik I just submitted [a PR](https://github.com/scalacenter/homebrew-bloop/pull/11) along the lines of what @sergei-grigorev described.

**Comment by jsatk** [comment]
Nice!
