### ISSUE TITLE
bloop constantly maxes out a CPU

### ISSUE THREAD

**Issue by ornicar** [scalacenter/bloop#1402]
Unfortunately this problem is not fixed yet, or there exists another one with the same symptoms.

Previous issues: #1385, #1362, #1386.

The problem still occurs on my lila project with same frequency (i.e. every 10 minutes).

- bloop-frontend_2.12:1.4.5
- Metals version 0.9.5
- java version "11.0.8.0.2" 2020-07-09 LTS
Java(TM) SE Runtime Environment GraalVM EE 20.2.0 (build 11.0.8.0.2+1-LTS-jvmci-20.2-b03)
Java HotSpot(TM) 64-Bit Server VM GraalVM EE 20.2.0 (build 11.0.8.0.2+1-LTS-jvmci-20.2-b03, mixed mode, sharing)
- Linux

After some editing in neovim with coc.nvim, and running the lila program a couple times, bloop will start maxing out a CPU indefinitely. It still works, just sets my laptop on fire.
Restarting bloop will resolve it for a couple minutes.

`rm -rf .metals && rm -rf .bloop` will resolve it for a bit longer, but the problem always comes back.

Bloop is that close to being the dev tool I always wished for, but this problem really kills it for me. Please let me know if there is anything I can do to help solve it.

**Comment by tgodzik** [comment]
Thanks for reporting! We will need to investigate it further to see what's going on.

**Comment by ornicar** [comment]
Actually I have not seen it for the last few days. The bug might be gone for good.

I will reopen if it happens again.

Thank you so much.
