### ISSUE TITLE
Changing 'resources' sourceSet in Gradle results in empty 'sources' in Bloop JSON

### ISSUE THREAD

**Issue by mdbergmann** [scalacenter/bloop#1441]
Relates to #992

I'm working on a Apache Wicket project where html, css and other resource files exist as part of the scala source folder.

In Gradle I can expand the resources sourceSet via:

```
sourceSets {
    main {
        java {
            srcDirs = []
        }
        scala {
            srcDirs = ['src/main/java', 'src/main/scala']
        }
        resources {
            srcDirs += ['src/main/java', 'src/main/scala']
        }
    }
}
```

This make Gradle copy any resource file into the build output folder.
However, `bloopInstall` will create a Bloop JSON project that is missing the 'sources' folders:

```
        "sources": [
        ],
...
        "resources": [
            "/mypath/dev/WicketUI/src/main/java",
            "/mypath/dev/WicketUI/src/main/scala",
            "/mypath/dev/WicketUI/src/main/resources"
        ],
```

When I remove the 'resources' definition from the sourceSets it does look like this:

```
        "sources": [
            "/mypath/dev/WicketUI/src/main/java",
            "/mypath/dev/WicketUI/src/main/scala",
        ],
...
        "resources": [
            "/mypath/dev/WicketUI/src/main/resources"
        ],
```

As an additional issue:

I did copy manually the source folder to 'sources' in the JSON file while maintaining the three resources folders,
the html, css and other non-compilable resources are not copied to the build output folder.

**Comment by Arthurm1** [comment]
Looks like a bug - the gradle export doesn't cope with resource and source dirs being the same.  I'll look into fixing it.

As far as I remember, resources deliberately aren't copied to the build output folder.  As Bloop is not intended for archive/deploy there's no reason to copy the resources dir - it's just used directly.

**Comment by mdbergmann** [comment]
> it's just used directly

That's fine as long as it's in the classpath.

Thanks for looking into it.

**Comment by mdbergmann** [comment]
If you can direct me where to look I can have a try fixing it.

**Comment by mdbergmann** [comment]
I would guess the issue might be this:

Line 66.
```
    val resources = getResources(sourceSet)
    val sources = getSources(sourceSet).filterNot(resources.contains)
```

Unfortunately I can't get the project to build with sbt.

**Comment by Arthurm1** [comment]
Yes that's the place.  I should be able to put a fix in this weekend

In terms of getting the project to build - have you looked at [this guide](https://scalacenter.github.io/bloop/docs/contributing-guide)?

**Comment by mdbergmann** [comment]
I didn't look at this guide but kind of assumed something similar.
Started from scratch though with the guide, but still facing this problem with resoilving the dependency:

```
[error] sbt.librarymanagement.ResolveException: Error downloading com.dwijnand:sbt-compat;sbtVersion=1.0;scalaVersion=2.12:1.0.0
[error]   Not found
[error]   Not found
[error]   not found: https://repo1.maven.org/maven2/com/dwijnand/sbt-compat_2.12_1.0/1.0.0/sbt-compat-1.0.0.pom
```

I've checked maven central, it seems this dependency is not there. Seems to not be a direct dependency.

**Comment by Arthurm1** [comment]
Sorry - beyond my ken - I'm not that familiar with the codebase.  You could ask on the gitter channel.
