### ISSUE TITLE
bloop console fails when invoked from path containing spaces

### ISSUE THREAD

**Issue by jypma** [scalacenter/bloop#1448]
The parent directory of my project has a space in it, which yields in the following mysterious error message:
```
$ bloop console myproject
Compiling myproject (51 Scala sources)
Compiled myproject (9291ms)
Error: only at most one app can be passed as dependency
```
After a lot of back-and-forth, it turned out that having a space in a parent directory caused that problem. Probably the space has something turned into two "apps" internally.

Renaming the parent directory got it to work fine.

I actually couldn't trace that exact error message to anything in particular; google only yielded one hit, perhaps related to `metals`.

**Comment by tgodzik** [comment]
Thanks for reporting! This looks like an issue in coursier:

https://github.com/coursier/coursier/blob/7bba8ce7881a90fdc386c6533f08a114ae964944/modules/cli/src/main/scala/coursier/cli/resolve/Resolve.scala#L316

However I am unable to reproduce it, what is your Bloop version and what system are you running under?

You can use `bloop about` to check:
```
$ bloop about
bloop v1.4.6-21-464e4ec4

Using Scala v2.12.8 and Zinc v1.3.0-M4+46-edbe573e
Running on Java JDK v1.8.0_275 (/usr/lib/jvm/java-8-openjdk-amd64/jre)
  -> Supports debugging user code, Java Debug Interface (JDI) is available.
Maintained by the Scala Center (Jorge Vicente Cantero, Martin Duhem)
```

**Comment by jypma** [comment]
Running on arch linux (fairly up-to-date), installed through [aur](https://aur.archlinux.org/packages/bloop/). Looks similar to yours:
```
bloop v1.4.6

Using Scala v2.12.8 and Zinc v1.3.0-M4+46-edbe573e
Running on Java JDK v1.8.0_275 (/usr/lib/jvm/java-8-openjdk/jre)
  -> Supports debugging user code, Java Debug Interface (JDI) is available.
Maintained by the Scala Center (Jorge Vicente Cantero, Martin Duhem)
```
The directory also sits inside a LUKS-encrypted loopback volume (in case that makes any difference), so I'm invoking bloop from `/run/media/{user}/{volumeId}/path/With Spaces/morepath`.

**Comment by jypma** [comment]
So dependencies are called "Apps" in coursier? I wonder if there's some escaping to be done when calling the Coursier API, or whether there's no real way to add space-containing args that way at all. [Looks like](https://github.com/coursier/coursier/blob/7bba8ce7881a90fdc386c6533f08a114ae964944/modules/cli/src/main/scala/coursier/cli/resolve/Resolve.scala#L312) it expects some `app:{args...}` stuff, and can't make up its mind when an `arg` contains a space... or something like that :-)

**Comment by tgodzik** [comment]
Somehow I didn't see that you are invoking `console` instead of `compile` :sweat_smile: 
I managed to reproduce it, but I get a different exception:
```
Cannot find app space/hello-world/.bloop/hello-world/bloop-bsp-clients-classes/classes-bloop-cli in channels io.get-coursier:apps
```

which probably is due to the classpath not being escaped here:
https://github.com/scalacenter/bloop/blob/f81585d437a44e76b4c2c2919f94067396130f3b/frontend/src/main/scala/bloop/engine/Interpreter.scala#L286

We should be able to just add `"` there to fix the issue, but I have no idea why the `apps` warning pops up for you :thinking:

**Comment by tgodzik** [comment]
After https://github.com/scalacenter/bloop/actions/runs/531315279 finishes (if it finishes successfuly) we should be able to test it out in your case.
