### ISSUE TITLE
Sbt-bloop - no `source` artifacts in meta-builds

### ISSUE THREAD

**Issue by dos65** [scalacenter/bloop#1450]
Bloop has `bloop.export-jar.classifiers` java option that allows Metals additionally specify `source` classifier.
It seems that this setting isn't used for meta-build and  `goto definition` doesn't work for symbols that come from Sbt plugins.

**Comment by tgodzik** [comment]
Thanks for reporting! I think I've seen it and haven't actually wondered why it's not working.

We should take a look at it at some point.
