### ISSUE TITLE
gradle integration doesn't work with multi-module project

### ISSUE THREAD

**Issue by tribbloid** [scalacenter/bloop#1452]
Tested with gradle 6.4.1, with latest bloop plugin.

For a project with multiple submodules defined in settings. running `gradlew bloopinstall` only generates bloop metadata for the top level project

**Comment by Arthurm1** [comment]
Hi @tribbloid 

Did you apply the plugin to the sub-projects as seen [here](https://scalacenter.github.io/bloop/setup#gradle)

Alternatively - if you're using Metals/VSCode you don't need to specify the plugin in the gradle build - Metals will do that for you when you run Import Build

**Comment by mdbergmann** [comment]
When the plugin is applied in the `all-projects` closure it works fine here.

**Comment by tribbloid** [comment]
@mdbergmann  do you have an example project?

It doesn't work for me in https://github.com/tribbloid/shapesafe/blob/7e29090e67f50415d7b92e677eaa22cc8949d758/build.gradle.kts#L37-L37:

```
buildscript {
    repositories {
        // Add here whatever repositories you're already using
        mavenCentral()
    }

    dependencies {
        classpath("ch.epfl.scala:gradle-bloop_2.12:1.4.6") // no support for multi-module
    }
}

plugins {
//    base
    java
    `java-test-fixtures`

    scala
    kotlin("jvm") version "1.4.30" // TODO: remove?

    idea

    `maven-publish`

    id("com.github.ben-manes.versions" ) version "0.36.0"
}

allprojects {

    apply(plugin = "java")
    apply(plugin = "java-library")
    apply(plugin = "java-test-fixtures")

    apply(plugin = "bloop")

...
```

**Comment by tribbloid** [comment]
BTW, I use the commandline tool to try to generate the .bloop dir:

```
$ ./gradlew clean bloopInstall

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.8.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 5s
21 actionable tasks: 20 executed, 1 up-to-date

```

But it is only generated under root directory

**Comment by tribbloid** [comment]
sorry, just realized that the .bloop dir already contains definition files for all the submodule.

Case closed, should have read more carefully
