### ISSUE TITLE
`bloop run` sometimes exits with code 64

### ISSUE THREAD

**Issue by kubukoz** [scalacenter/bloop#1453]
Hi!

I've noticed that `bloop run` will sometimes exit without giving any output. The exit code it'll produce is 64 (as seen in `$?`).

I was able to reproduce it in a simple project, but unreliably:

```scala
//build.sbt
scalaVersion := "2.12.13"
```

```scala
//src/main/scala
object Main extends App { println("hello world") }
```

In my work project, it seems like I'm more likely to get that behavior after canceling (ctrl+c) a previous run - but it's still not happening every time.

**Comment by tgodzik** [comment]
Thanks for reporting! This is probably something around bloopgun and I remember similar issues being reported at some point.

**Comment by kubukoz** [comment]
haven't seen this for years, but also haven't used `bloop run` _that_ often.

**Comment by ckipp01** [comment]
I think I'll go ahead and close then as I use `bloop run` a fair amount and have never seen this. If you hit on this again, please do report back.
