### ISSUE TITLE
Error on scalacOptipons translation from sbt to bloop 

### ISSUE THREAD

**Issue by flomebul** [scalacenter/bloop#1470]
I use `bloop` via `VSCode + Metals` on top of sbt (`sbt-bloop 1.4.8`).
I just discover an issue with the following `build.sbt` extact:
```scala
ThisBuild / scalacOptions ++= Seq(
  "-deprecation",
  "-encoding", "UTF-8",
  "-feature",
  "-indent",
  "-new-syntax",
  "-source", "future",
)
...
lazy val asuivre = (project in file("asuivre"))
  .settings(
    name := "asuivre",
    scalacOptions in Compile -= "-Ycheck-init",
    scalacOptions in Compile --= Seq("-source", "future"),
    scalacOptions in Compile ++= Seq("-source", "3.0"),
    scalacOptions in Test --= Seq("-source", "future"),
    scalacOptions in Test ++= Seq("-source", "3.0")
  )
```

Under sbt, all is fine. But with bloop the  `test scalacOptions` is wrong: it look like that the two last lines for `Test` where applied after the three first lines destinated only for `Compile` where applied.
The result is an an error:
```
2021.03.01 14:36:59 INFO  compiling asuivre-test (1 scala source)
2021.03.01 14:36:59 ERROR not found: 3.0
2021.03.01 14:36:59 INFO  time: compiled asuivre-test in 14ms
```

**Comment by tgodzik** [comment]
Thanks for reporting! Not sure exactly what is happening since we do get the information from sbt itself. Is the order correct in `.bloop/asuivre-test.json` ? We might be mixing the scalac options ordering if that is the case.

**Comment by flomebul** [comment]
Extract from `.bloop/asuivre-test.json`:
```
        "scala": {
            "organization": "org.scala-lang",
            "name": "scala-compiler",
            "version": "3.0.0-RC1",
            "options": [
                "-deprecation",
                "-encoding",
                "UTF-8",
                "-feature",
                "-indent",
                "-new-syntax",
                "-unchecked",
                "-Xfatal-warnings",
                "-Xmigration",
                "-Yerased-terms",
                "-Yexplicit-nulls",
                "-Yindent-colons",
                "3.0",
                "-source",
                "3.0"
            ],
```
We can see that `3.0` is before and after `-source` and that there is no `-Ycheck-init`.

My understanding is that the first three lines for `Compile` where apply, resulting to removal of `-Ycheck-init` and replacement of `-source future` by `-source 3.0`. Then the two line for `Test` are apply that try to remove `-source future`, but remove only `-source`and leave `3.0`, then `-source 3.0` is added...

**Comment by flomebul** [comment]
After investigation (and discovering how to debug with `sbt`), you're right... Same options in `sbt`.
Th difference is that `bloop` report the error while `sbt` does not.
I propose to close the issue.

**Comment by tgodzik** [comment]
Glad that you found the issue!
