### ISSUE TITLE
Migrate back to `alexarchambault/case-app`

### ISSUE THREAD

**Issue by ckipp01** [scalacenter/bloop#1487]
Taking a quick peek again at #1295 , I think a necessary first step is to actually migrate away from the `ch.epfl.scala:case-app` that Bloop uses. This is a fairly large task in itself that can be done apart from migrating to 2.13, which already seems to be quite a large task.

I have no idea why this was forked and used, I don't see it under the scalacenter org at all, and I'm unsure if there is a specific issue with just using the upstream case-app, but this needs to be done before the move to 2.13.

Creating an issue for this to maybe break #1295 into smaller chunks to be tackled.

**Comment by alexarchambault** [comment]
I started to have a look at this, as I'd need bloop-launcher in 2.13 in a project I'm working on.
