### ISSUE TITLE
Import code action makes the wrong code change

### ISSUE THREAD

**Issue by EveryonePrint-dev** [scalacenter/bloop#1494]
(I see this mostly since either 0.10.1, or 0.10.2)

The code actions show the right completions (imports).
But choosing a completion makes the wrong code change.

I.e.:

This class which not yet has an import: 
```
Address("http", "Test", TestNodeHostName, 1234)
```
shows the right code action as "import" -> "akka.actor.Address".

But when executed the code action the code is changed inline as:

```
Command.akka.actor.Address("http", "Test", TestNodeHostName, 1234)
```
And no import is being made at all.

In other cases a code completion makes an import of a parent package and and replaces the unknown class with a package prefix like:

```
Foo(1, 2, 3)
```
->

```
import some.parent

subparent.Foo(1, 2, 3)
```

Although there is no reason to not just import `import some.parent.subparent.Foo` and be done.

**Comment by EveryonePrint-dev** [comment]
The JSON code for the replacement looks like this:

```
(:range
 (:start
 (:line 49 :character 64)
  :end
 (:line 49 :character 71))
 :newText "Command.akka.actor.Address")
```

**Comment by tgodzik** [comment]
Thanks for reporting! This issue is actually connected to Metals, so I will transfer it there.

**Comment by tgodzik** [comment]
Ok, I need to close it and reopen actually.

**Comment by tgodzik** [comment]
Opened https://github.com/scalameta/metals/issues/2736
