### ISSUE TITLE
Bloop generates .bloop/.json file for root project with empty project.name

### ISSUE THREAD

**Issue by stefanrybacki** [scalacenter/bloop#1505]
In VSCode using metals:

What can be the reason that bloop generates a json without a name with empty project.name within the json for a gradle project.

It leads to error: `WARN  no build target for:` or any scala file within the project.

Manually changing the json name and project.name fixes the error.

**Comment by Arthurm1** [comment]
We do play with the project names to create the simplest version of each project while making sure project names don't clash.  I imagine it's to do with that but can't think how it would produce empty project names.

Could you create a minimised reproduction of your build file(s) and post it here please.

**Comment by stefanrybacki** [comment]
Will try to create a minimalistic example. However, it is weird, using the same repository on machine, different folder, it works as expected.

**Comment by Arthurm1** [comment]
Could you post the result of `./gradlew projects`

**Comment by stefanrybacki** [comment]
Here it the projects output (had to change some project names for legal reasons though):

```
Root project 'mmvs'
+--- Project ':project1'
+--- Project ':project1-api'
+--- Project ':project1-mgmt'
+--- Project ':doc'
|    \--- Project ':doc:sub1'
|         +--- Project ':doc:sub1:mmvs'
|         \--- Project ':doc:sub1:subsub1'
+--- Project ':lib'
+--- Project ':util'
+--- Project ':project2'
+--- Project ':project3'
+--- Project ':project3-api'
\--- Project ':project3-mgmt'
```

I have jsons for all projects and sub projects including -test.json in my .bloop folder but for mmvs, which is the .json file with an empty project name. (maybe it has to do with :doc:sub1:mmvs?)

**Comment by Arthurm1** [comment]
Ah - it looks like `rootProject#getPath` returns ":".  We only use that on name clashes.  I'll see about a fix.

I guess you have source code at the root project level?  I've not seen that in multi-project builds before.

**Comment by stefanrybacki** [comment]
We don't have source at the root level, we have buildSrc though.

**Comment by Arthurm1** [comment]
OK - but you must be applying the Scala or Java plugin to your root project - otherwise Bloop wouldn't try to export that project.

**Comment by stefanrybacki** [comment]
We do have this:

```
plugins {
  id 'java'
}

subprojects {
  apply plugin: 'java'
}
```
I would assume `plugins` will auto apply the java plugin also for root.

**Comment by Arthurm1** [comment]
AFAIK the following code will declare _and apply_ the java plugin...
```
plugins {
  id 'java'
}
```

To declare a plugin for use but not apply it you'd usually write...
```
plugins {
  id 'java' apply false
}
```
but Gradle won't let you do this because `java` is a built in plugin so there's no need to declare it at all.

Just remove `java` from your `plugins` section and apply it as you do here...
```
subprojects {
  apply plugin: 'java'
}
```

The same is true with the `scala` plugin
