### ISSUE TITLE
Warnings not cleared or not shown for Scala 3

### ISSUE THREAD

**Issue by ckipp01** [scalacenter/bloop#1509]
This relates to this issue created in Metals: https://github.com/scalameta/metals/issues/1683

Using Bloop via Metals
Bloop version:  1.4.8
Scala version: 3.x

Given the following code:

```scala
def hello(): Unit = {
  ""
  val a = 123
  val b = 3
}
```

You see the about the pure expression doing nothing. If you then remove the `""` the warning is not cleared. The task finishes and does say that there was no errors or warnings:

```
[Trace - 10:33:03 AM] Received notification 'build/taskFinish'
Params: {
  "taskId": {
    "id": "6"
  },
  "eventTime": 1623659583764,
  "message": "Compiled \u0027root\u0027",
  "status": 1,
  "dataKind": "compile-report",
  "data": {
    "target": {
      "uri": "file:/Users/ckipp/Documents/scala-workspace/scala3-test/?id\u003droot"
    },
    "errors": 0,
    "warnings": 0,
    "isNoOp": false,
    "isLastCycle": true,
    "clientDir": "file:///Users/ckipp/Documents/scala-workspace/scala3-test/.bloop/root/bloop-bsp-clients-classes/classes-Metals-0ajB1JSqT6WzXNACAIZD6w\u003d\u003d/",
    "analysisOut": "file:///Users/ckipp/Documents/scala-workspace/scala3-test/target/streams/compile/bloopAnalysisOut/_global/streams/inc_compile_3.zip"
  }
}
```

However, there is no `publishDiagnostics` that happens to reset them.

The behavior actually changes in the newest version of Bloop, `v1.4.8-19-4d9f966b`, it won't emit a warning for the same code.

**Comment by tgodzik** [comment]
This should now be fixed as far as I checked.
