### ISSUE TITLE
Update Monix to 3.x.x

### ISSUE THREAD

**Issue by ckipp01** [scalacenter/bloop#1510]
Started to again take a look at https://github.com/scalacenter/bloop/issues/1295 in hopes to get launcher published for 2.13. Another large task that can be separated out is an update to Monix 3.x.x. Due to the build graph publishing launcher forces updates in other modules, which forces Monix to be updated to a version that supports Scala 2.13. This happens to only be the Monix 3.x.x series. Looking through it, this probably isn't a small task as Monix is quite intertwined throughout Bloop. However, this will need to happen before Launcher can be published for 2.13.

**Comment by kpodsiad** [comment]
Seems like a lot of fun 😅. I'll give it a try!

**Comment by ckipp01** [comment]
> Seems like a lot of fun 😅. I'll give it a try!

That would be incredible @kpodsiad! I'll go ahead and assign you on here just to ensure someone else doesn't grab it while you're working on it. If you end up not finding the time, no worries, just let me know and I can remove you from it.

**Comment by ckipp01** [comment]
Completed in https://github.com/scalacenter/bloop/pull/1759.
