### ISSUE TITLE
Java 11 Apis highlighted red using JDK 17 EA build

### ISSUE THREAD

**Issue by AugustNagro** [scalacenter/bloop#1519]
Hi, with my JAVA_HOME set to `/home/me/jdks/loom-jdk-17ea`, Java 11+ apis such as `Path.of(...)` are highlighted red.

All setting are default, and using the latest Metals/Bloop version (using Linux).

**Comment by tgodzik** [comment]
Thanks for reporting! JDK 17 is not yet supported and not tested. I would suggest downgrading to JDK 11 if possible. We will most likely need to support 17, as it's going to be an LTS version, but I will msot likely take a look at it around the release.
