### ISSUE TITLE
Bloop: unable to start the launcher due to `java.lang.NoClassDefFoundError: scala/collection/immutable/List`

### ISSUE THREAD

**Issue by hmemcpy** [scalacenter/bloop#1526]
Disclaimer: I'm not sure if the problem is with bloop or IntelliJ, or both.

I'm using BSP via bloop with IntelliJ (selecting "import existing sources", and choose `sbt via bloop` during import).
For some reason, it just started failing to import giving this error:

```
/Users/hmemcpy/.sdkman/candidates/java/21.0.0.r11-grl/bin/java -Dfile.encoding=UTF-8 -classpath /Users/hmemcpy/.ivy2/cache/ch.epfl.scala/bloop-launcher_2.12/jars/bloop-launcher_2.12-1.4.8-26-cbddb8ba.jar:/Users/hmemcpy/.ivy2/cache/net.java.dev.jna/jna/jars/jna-4.5.0.jar:/Users/hmemcpy/.ivy2/cache/net.java.dev.jna/jna-platform/jars/jna-platform-4.5.0.jar:/Users/hmemcpy/.ivy2/cache/org.scala-lang.modules/scala-xml_2.12/bundles/scala-xml_2.12-1.2.0.jar:/Users/hmemcpy/.ivy2/cache/org.scala-lang.modules/scala-collection-compat_2.12/jars/scala-collection-compat_2.12-2.4.2.jar bloop.launcher.Launcher 1.4.8-26-cbddb8ba
Error: Unable to initialize main class bloop.launcher.Launcher

Caused by: java.lang.NoClassDefFoundError: scala/collection/immutable/List
```

This worked just last week, so I'm not sure what could have happened.

AFAIK, bloop is compiled with Scala 2.12, and seemingly launched using the 2.12 libraries in the classpath...

Additional information:
sbt: 1.5.4
IDEA 2021.2 EAP (Ultimate Edition)
Build #IU-212.4535.15, built on June 30, 2021
org.intellij.scala (2021.2.385)

```
> java --version
openjdk 16.0.1 2021-04-20
OpenJDK Runtime Environment GraalVM CE 21.1.0 (build 16.0.1+9-jvmci-21.1-b05)
OpenJDK 64-Bit Server VM GraalVM CE 21.1.0 (build 16.0.1+9-jvmci-21.1-b05, mixed mode, sharing)
```

Also pinging @jastice for possible additional input?

**Comment by tgodzik** [comment]
Thanks for reporting! It seems that the invocation is missing Scala library, could this be the issue?

**Comment by hmemcpy** [comment]
Oh! I think you're right - I just compared the command-line with the older IntelliJ version - and indeed the `scala-library` is missing from the classpath!

So this is definitely an IntelliJ bug, I'll report it to Justin :)

Thanks, closing for now!
