### ISSUE TITLE
`maven-bloop` no longer being published.

### ISSUE THREAD

**Issue by ckipp01** [scalacenter/bloop#1532]
The last version of `maven-bloop` that was published was `1.4.8-69-93b5aa87`, which corresponds with https://github.com/scalacenter/bloop/actions/runs/964000053. The next pr was https://github.com/scalacenter/bloop/pull/1512/files, which looking at it I can't tell why that would stop publishing. Although the pr has to do with Maven so it does likely seem like the culprit. I noticed this today when the pr was failing to update Bloop in Metals: https://github.com/scalameta/metals/pull/2962

You can see the error here: https://github.com/scalameta/metals/pull/2962/checks?check_run_id=3074460913#step:5:803

**Comment by tgodzik** [comment]
Thanks for reporting! I think this is due to the fact that we needed to bump the Scala version to 2.13, so the invocation also changed to:
`mvn ch.epfl.scala:maven-bloop_2.13:1.4.8-81-e170cd66:bloopInstall`

We need to update it together with the update PR.

**Comment by ckipp01** [comment]
Ahhhh I totally missed that, sorry!

**Comment by tgodzik** [comment]
Yeah, it's super not obvious. I haven't yet changed the docs since it refers to 1.4.8 https://scalacenter.github.io/bloop/docs/build-tools/maven#export-your-build

I will need to do a reelease, probably after dropping nuprocess to support M1s
