### ISSUE TITLE
Avoid "Required option --project / -p not specified"

### ISSUE THREAD

**Issue by olafurpg** [scalacenter/bloop#154]
I ran
```
$ bloop compile a
Required option --project / -p not specified
```

It would be nice if bloop inferred `-p` here.

**Comment by propensive** [comment]
Relatedly,
`bloop clean -p foo`
works where
`bloop clean --project foo`
does not.

This isn't a problem with the `compile` subcommand, though it may be for others.

**Comment by jvican** [comment]
@propensive I think that's a case-app bug :smile:. Would be great if you report it.

**Comment by jvican** [comment]
@propensive It's not, it was due to the fact that this field was called `projects` instead of `project`. Fixed that as well as the issue described in this ticket.
