### ISSUE TITLE
Bloop doesn't compile Scala 2.13.7

### ISSUE THREAD

**Issue by tgodzik** [scalacenter/bloop#1598]
The issue is because of the Zinc fork the compiler bridge doesn't compile anymore:
```
/tmp/sbt_f7b9f74f/xsbt/ZincSymbolLoaders.scala:17: error: value nameChars is not a member of scala.tools.nsc.util.ClassRepresentation
        val len = classRep.nameChars(nameCharBuffer0)
                           ^
```

taking a look at it but I have no estimates for when it will work.

**Comment by tgodzik** [comment]
I made a fix in https://github.com/scalacenter/zinc/tree/main based on changes in https://github.com/scala/scala/commit/f51e204fb53f4155320bb5f75271991417453d76

@Duhemm would you be able to publish the fork?

**Comment by Duhemm** [comment]
The updated Zinc fork is in Maven central with version `1.3.0-M4+47-d881fa2f`.

**Comment by SethTisue** [comment]
Is there something we could add to the Scala 2 community build so we'd know in advance?

**Comment by tgodzik** [comment]
> Is there something we could add to the Scala 2 community build so we'd know in advance?

Theoretically, the zinc fork compilation, but we want to get rid of it, so maybe it doesn't make sense. I plan to put aside all other work next week to work on it
