### ISSUE TITLE
Stale `match may not be exhaustive` diagnostic

### ISSUE THREAD

**Issue by kpodsiad** [scalacenter/bloop#1603]
I have the following scala file (scala-cli also uses bloop so the problem concerns bloop itself)
```scala
// using scala 3.0.0

private enum Kind:
  case A, B, C

object X {
  import Kind.*
  def foo(e: Kind) = {
    e match
      case A => ???
      case B => ???
      // case C => ???
  }
}
```
After saving there is a diagnostic which says:
```shell
match may not be exhaustive.

It would fail on pattern case: C
bloop [9,5]
```
but if I uncomment `// case C => ???` diagnostics aren't refreshed and warning remain. After manual reconnecting to the build server, the diagnostic is gone.

**Comment by dos65** [comment]
Could you check if the same thing happen on 3.1.0?
I remember issues about stale diagnostic but probably it's gone after some of 3.0.x version

**Comment by tgodzik** [comment]
If it's a warning then the issue is https://github.com/scalacenter/bloop/issues/1509 which needs a zinc bump

**Comment by kpodsiad** [comment]
Yup, it's a warning. 
Closing because it's contained in #1509.
