### ISSUE TITLE
Incompatibility with better-monadic-for

### ISSUE THREAD

**Issue by kovacshuni** [scalacenter/bloop#1608]
Compilation error comes up when using oleg-py's [better-monadic-for](https://github.com/oleg-py/better-monadic-for)

in places like
```
object Hello extends Greeting with App {
  val s = for {
    implicit0(a: Int) <- Option(1)
    b = implicitly[Int] + 2
  } yield b
  println(s"greeting $s")
}
```

`not found: value implicit0`

The issue comes up nondeterministically. I haven't been able to find the perfect re-producing project, but in larger projects it comes up definitely with a higher probability: 90%+. If you create a mini-project for the above example, it might not. If anyone else has a 100% way of reproducing it, please share. I'm sure it's not me only, because I know colleagues who had this in IDEA with bloop, and i'm using Metals with bloop. Same error, same circumstances with `implicit0`. Can't share NDA project code though.

For comparison, **with sbt server there is no issue** with implicit0.

This really impacts our bloop usability when one uses the final tagless model where components and dependencies are injected with implicits.

Has this come up for anyone else?

**Comment by tgodzik** [comment]
Thanks for reporting! I haven't seen an issue like this previously. I am currently working on updating Bloop's Zinc to the newest version, since a lot of problems might have been fixed already. Let's confirm if it help in this situation after that work is complete.

**Comment by kovacshuni** [comment]
Turns out it was the `wartremover` plugin that can break other compiler plugins.

Removing 
```
addSbtPlugin("org.wartremover" % "sbt-wartremover" % "2.4.5")
```

from `project/plugins.sbt` and making sure no other components pull this dependency fixed my build, or rather fixed my compilation errors shown in my editor.
Thanks
