### ISSUE TITLE
Allow users to fork tests

### ISSUE THREAD

**Issue by jvican** [scalacenter/bloop#162]
Bloop does not allow you to set whether test execution should be forked, even though we have the same for running projects. When this is implemented, it needs to be updated in the maven mojo so that it's configurable from Maven too.

**Comment by Duhemm** [comment]
We support forking in test, it was added in #136. See #111.

https://github.com/scalacenter/bloop/blob/c899f3ad31fadd22b9b498d5080c362ebbfd4b2d/sbt-bloop/src/main/scala/bloop/SbtBloop.scala#L194-L209

**Comment by jvican** [comment]
@Duhemm Merci, I know get it how it works. The reason why I thought it didn't exist is because we don't have an special option for fork in the configuration file, but I know get the semantics of what we have now: when we have a test project, our `fork` option mean s`fork in Test` while in a compile project it means `fork in run`. There's some conflation of the concept here, but I think it's unlikely someone will define main entrypoints in test and would like to fork them, so it's good as is.
