### ISSUE TITLE
Bloop export directory name clashes

### ISSUE THREAD

**Issue by pdziedzic-sumo** [scalacenter/bloop#1624]
Hi, I've got a large Gradle project with 'sql' and 'sql-test' sub-projects in it.

It seems that bloop export [generates](https://scalacenter.github.io/bloop/docs/build-tools/gradle) its own 'sql-test' config based on the 'sql' project and ignores/overwrites my original 'sql-test' project in .bloop/ - I see various errors about missing classes in my IDE (vscode).

This issue would affect projects already containing both '_name_' and '_name_-test' directories.
Perhaps using a random (or configurable) suffix in bloop-exported directory names could help here?

Thanks!

**Comment by dos65** [comment]
Thanks for reporting!
Probably it might be an issue in exporting from maven and sbt too.

**Comment by tgodzik** [comment]
This can probably be fixed in https://github.com/scalacenter/bloop/blob/24f0bbad9889b47b2106e54f481b2fea05ae23dd/integrations/gradle-bloop/src/main/scala/bloop/integrations/gradle/model/BloopConverter.scala#L738

For sbt and maven, I think the situation is a bit worse.

**Comment by Arthurm1** [comment]
I can take a look at it
