### ISSUE TITLE
Maven <classifier> is not correctly appended to artifact

### ISSUE THREAD

**Issue by avsaase** [scalacenter/bloop#1627]
I'm running into an issue exporting a Maven built to bloop using `mvn ch.epfl.scala:maven-bloop_2.13:1.4.11:bloopInstall`. Some of my dependencies have a `<classifier>` in the pom file and I believe it is not correctly appended to the package name when retrieving the artifact. 

I cannot share my code or the dependency but the problem can be reproduced with a seed project such as `sbt new scalameta/maven-scala-seed.g8` and adding 
```
<dependency>
    <groupId>commons-io</groupId>
    <artifactId>commons-io</artifactId>
    <version>2.1</version>
    <classifier>some-classifier-string</classifier>
</dependency>
```
to `pom.xml`. Running `mvn ch.epfl.scala:maven-bloop_2.13:1.4.11:bloopInstall` then shows the log entry
```
[INFO] SUCCESS commons-io:commons-io:jar:some-classifier-string:2.1:compile
```
According to the [Maven POM Reference](https://maven.apache.org/pom.html#POM_Relationships) the classifier should be after the version number, so shouldn't `some-classifier-string` and `2.1` be reversed here?

**Comment by avsaase** [comment]
I want to use VSCode and the Metals extension for my Maven project. Some dependencies are fetched from a private repository and this fails, probably because of this bug. The error I get is something like
```
[ERROR] FAILURE com.example.artifactId:package:jar:classifier:1.2:compile org.eclipse.aether.resolution.ArtifactResolutionException: Could not find artifact com.example.artifactId:package:jar:1.2 in [private repository]
```

When I look in the repository the path is
```
com/example/artifactId/package/1.2/package-1.2-classifier.jar
```

From this I get the idea that the classifier is important and needs to be appended after the version number.

**Comment by avsaase** [comment]
Is there any way to manually specify the correct artifact?

**Comment by tgodzik** [comment]
> Is there any way to manually specify the correct artifact?

I am trying a solution where we will skip downloading of artifacts which are not the default classifier, since we don't need them for compilation. Would that be a correct assumption?

**Comment by avsaase** [comment]
To be honest I don't know as I'm quite new to Scala and Maven. From the example I posted [here](https://github.com/scalacenter/bloop/issues/1627#issuecomment-994031998) I think the classifier is important to get the correct artifact. That said, I am happy to test your PR right now and let you know if it works. How do I apply your fix in my project?

**Comment by tgodzik** [comment]
It's probably best to wait until this is merged, it should be easier to test out. What is the classifier that you need here?

I am aware of only 2 additional types such as `sources` and `javadoc`, which both are not needed for compilation.

**Comment by tgodzik** [comment]
The alternative would be to just set the classifier instead of empty if it's available. Maybe that is a better solution :thinking:

**Comment by avsaase** [comment]
It looks like we use the classifier to indicate a compatible version of the dependency 🤷🏻. For example, the classifier could be `dependencyname-1.1`.

**Comment by tgodzik** [comment]
Ok, so I changed the fix, it should work now. 

But to make sure it makes sense, you should be able to actually test it out via running:
```
sbt mavenBloop/publishM2
```

and then:
```
mvn ch.epfl.scala:maven-bloop_2.13:<<version>>:bloopInstall
```
just change the version to the one that was printed in the previous version such as `1.4.11-26-d87f872c-20211223-1308`

**Comment by avsaase** [comment]
Do I need to run these commands in the `bloop` folder or in the Maven project?

**Comment by avsaase** [comment]
It works! I ran the first command in the `bloop` folder and then
```
mvn ch.epfl.scala:maven-bloop_2.13:1.4.11-26-42024fe8:bloopInstall
```
in my Maven project. The build now seems to be imported in Metals as I can do go to definition and use the other features.  Awesome!

**Comment by tgodzik** [comment]
> It works! I ran the first command in the `bloop` folder and then
> 
> ```
> mvn ch.epfl.scala:maven-bloop_2.13:1.4.11-26-42024fe8:bloopInstall
> ```
> 
> in my Maven project. The build now seems to be imported in Metals as I can do go to definition and use the other features. Awesome!

Cool, thanks! Sorry I didn't respond earlier, I was finishing up some christmas preperations.

**Comment by avsaase** [comment]
Oh, that's really no problem. There are more important things in life. 

I'm super happy it is fixed. Thanks a lot! Happy holidays!

**Comment by avsaase** [comment]
One last thing. I noticed there is a `metals.bloopVersion` setting in VSCode. Can I use that to automatically use the fixed bloop version in all my projects? I tried setting it to `2.13:1.4.11-26-42024fe8` but that gave an error it couldn't find the build server.

**Comment by tgodzik** [comment]
You can set it to `1.4.11-26-42024fe8` , but you would need to run `sbt publishLocalAllModules` to have everything available locally.
