### ISSUE TITLE
Make the sbt-bloop plugin work for source dependencies

### ISSUE THREAD

**Issue by jvican** [scalacenter/bloop#166]
When `bloopGenerate` is run in the root project, it will not run it for all the projects in external source dependencies because they are not aggregated. This also happens with projects in the same build that are not aggregated in the root project either.
  
I propose that we make the `bloopGenerate` task to detect root projects (sbt's base directory matches the base directory of the project) and run `bloopGenerate` for any living project that it finds through the fancy sbt data structures. If we can use the all projects sbt filter, even better.
  
Currently, bloop doesn't do this and running `bloopGenerate` in our build requires post processing of the configuration files to remove unexisting dependencies.

**Comment by Duhemm** [comment]
You should use `installBloop` to do this instead, <3
