### ISSUE TITLE
Couldn't run bloopGenerate for project

### ISSUE THREAD

**Issue by ioleo** [scalacenter/bloop#1713]
Hi,

I'm using VSCode with Metals + Bloop. Until today everything worked perfectly. now I'm getting `[error] Couldn't run bloopGenerate for ...`:

```
2022.04.06 11:25:04 INFO  [success] Generated .bloop/root-test.json
2022.04.06 11:25:04 INFO  [success] Generated .bloop/externalProtos-test.json
2022.04.06 11:25:04 INFO  [success] Generated .bloop/esApi-test.json
2022.04.06 11:25:04 INFO  [success] Generated .bloop/root.json
2022.04.06 11:25:04 INFO  [success] Generated .bloop/externalProtos.json
2022.04.06 11:25:04 INFO  [success] Generated .bloop/esApi.json
2022.04.06 11:25:04 INFO  [error] Couldn't run bloopGenerate for app-test
2022.04.06 11:25:04 INFO  [error] Couldn't run bloopGenerate for app
2022.04.06 11:25:04 INFO  [success] Total time: 1 s, completed 6 Apr 2022, 11:25:05
```

Which results reduced IDE functionality.

I have tried cloning a fresh repo (just to make sure all the bloop stuff is generated from scratch), as well as manually removing `.metals`, `.bloop`, `.bsp`, `target`, `project/metals.sbt`. The result stays the same.

The only thing that changes since yesterday is I run software updates for my Fedora 35 system. SBT is installed globally (from repository) so it might have been updated. However my understanding is, it does use a local sbt version based on `project/build.properties` so it shouldn't matter.

I have no idea how to progress from this point. Please help me resolve this issue.

**Comment by ioleo** [comment]
* `sbt.version=1.6.2`
* Bloop version `1.4.13`
* Metals extension version `1.13.0`

**Comment by ioleo** [comment]
For some reason switching to `sbt` as build server did not help aswell. Then I uninstalled the `java-latest-openjdk` and replaced it with `java-11-openjdk` (although in both cases `java -version` reported the same), and switched to `sbt` as build server and now got my VSCode hints back.

Although still not clear whats going on with bloop, and I would, if possible, love to get it working.

**Comment by ioleo** [comment]
@dos65 Thanks for takeing interest in this issue. How can I use the latest version with this commit?

**Comment by tgodzik** [comment]
You should be able to set the Bloop version in the settings to `1.4.13-64-4e5281cb` or anything latest here as shown here https://scalacenter.github.io/bloop/docs/build-tools/sbt

**Comment by ioleo** [comment]
Added `addSbtPlugin("ch.epfl.scala" % "sbt-bloop" % "1.4.13-64-4e5281cb")`, switched back to bloop as build server... and now it works. Generated succesfully.

Removed `addSbtPlugin("ch.epfl.scala" % "sbt-bloop" % "1.4.13-64-4e5281cb")` to see if the error comes back. Generated sucessfully.

Magic. It seems like the issue resolved itself, just as it appeared out of nowhere.

**Comment by tgodzik** [comment]
At least we've got  a better error message now. Next time we should get a clearer view of what's going on. Let's see if anyone can report something new later on.

**Comment by tgodzik** [comment]
Let's reopen once we get any reasonable error message
