### ISSUE TITLE
Add integration tests for nailgun

### ISSUE THREAD

**Issue by jvican** [scalacenter/bloop#172]
We badly need integration tests for nailgun. The way bloop works with or without nailgun is not the same, and nailgun is eventually the UX for bloop. Having integration tests for nailgun will help us assert that issues with stdin, stdout and stderr (as I'm having right now with the bsp implementation) don't happen, or that the CLI interface works as expected, to prevent errors like #88 or https://github.com/scalacenter/bloop/issues/100.
  
One way we can test nailgun is by having tests that operate like clients and spin up a nailgun server before they start. The clients will reuse the python script (whose path would be generated by `BuildInfo`) and would send commands. As these are integration tests, we would check that the side effects of bloop commands happen (compilation generates analysis files, `clean` removes them, `test` gives the test output of a project, etc).

**Comment by jvican** [comment]
@Duhemm You did have a prototype for this, right? Would love to check it out.

**Comment by Duhemm** [comment]
It was merged 15 days ago: #271
