### ISSUE TITLE
Gradle bloop support for Scala 3

### ISSUE THREAD

**Issue by Flowdalic** [scalacenter/bloop#1728]
It appears that the gradle-bloop plugin is only available for Scala 2. Please consider adding Scala 3.

**Comment by tgodzik** [comment]
Thanks for reporting! You should be able to use the 2.13 plugin version maybe? Are you able to apply a specific version of the Bloop plugin?

**Comment by tgodzik** [comment]
I don't think there is currently a need to release for Scala 3 as Scala 2.13 release plugin can be used. Do let us know if it's not possible for you!

**Comment by Arthurm1** [comment]
FYI - This should only ever be needed if another Gradle plugin is being used and _that_ is only compiled under Scala 3 as plugins share the same classpath in Gradle
