### ISSUE TITLE
Make sure that nailgun aliases register all bloop commands

### ISSUE THREAD

**Issue by jvican** [scalacenter/bloop#173]
Currently, the nailgun aliases are strings that are detached from our bloop commands, and we forgot to add some of them like `configure` to the nailgun aliases.

**Comment by olafurpg** [comment]
Why do you use nailgun aliases? I would rather configure the installation to let commands go directly to bloop. The nailgun error messages are very cryptic when you get the aliases wrong.

**Comment by jvican** [comment]
Because I want to avoid the use of `--`, and I prefer the CLI to be intuitive. See #175 and its commit messages for details.

**Comment by olafurpg** [comment]
What error message gets printed out when the user types `bloop tes` or `bloop compil`? I would expect it to print out "Command not found: compil". The user won't have to type `--` if `bloop` is aliased correctly.

**Comment by olafurpg** [comment]
Here's what I get on a slightly outdated version

```
$ bloop help
bloop-frontend 7687838a+20180112-1047
$ bloop compil
Jan 18, 2018 4:14:24 PM com.martiansoftware.nailgun.NGSession run
INFO: Server unexpectedly exited with unhandled exception
java.lang.ClassNotFoundException: compil
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at com.martiansoftware.nailgun.NGSession.run(NGSession.java:271)
```
