### ISSUE TITLE
Can I take over the AUR package, please?

### ISSUE THREAD

**Issue by japgolly** [scalacenter/bloop#1736]
Hi @TheElectronWill . Would I be able to take over the AUR bloop package please? I'm happy to keep it up to date. Cheers!

https://aur.archlinux.org/packages/bloop

**Comment by TheElectronWill** [comment]
Sure!
It's better if a bloop contributor takes care of it. Sorry for the lack of updates 😅
I'll give you the rights. I assume you're user https://aur.archlinux.org/account/japgolly ?

**Comment by japgolly** [comment]
Thank you! Yes that's me (in aur land).

**Comment by tgodzik** [comment]
> Sure! It's better if a bloop contributor takes care of it. Sorry for the lack of updates sweat_smile I'll give you the rights. I assume you're user https://aur.archlinux.org/account/japgolly ?

I don't know much about the AUR packages, so you have my blessing @japgolly to take care of it! :tada:

**Comment by japgolly** [comment]
Great, thank you!! I use this pretty regularly so I'm happy to keep it up to date :+1:
