### ISSUE TITLE
`bloop help` (as well as other commands) hangs on Mac M1 - unable to connect to server in metals

### ISSUE THREAD

**Issue by masonedmison** [scalacenter/bloop#1739]
If I restart my machine I am to run simple commands and metals is able to connect to the server. This seems to be an intermittent problem but triggered if I switch projects in vscode in which metals will complain with
```
2022.06.21 15:30:29 ERROR error: The launcher failed to establish a bsp connection, aborting...
2022.06.21 15:30:29 ERROR Failed to connect with build server, no functionality will work.
java.lang.RuntimeException: The server did not start, got FailedToOpenBspConnection
	at bloop.launcher.LauncherMain.failPromise$1(Launcher.scala:92)
	at bloop.launcher.LauncherMain.runLauncher(Launcher.scala:119)
	at scala.meta.internal.metals.BloopServers$$anon$2.run(BloopServers.scala:434)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(Thread.java:834)
```
and any attempt to run a simple `bloop` command ` (e.g. `bloop help`) will hang and cease to every complete or actually print anything to the console.

bloop version = `bloop 1.5.0-18-003e6c7b`
macos = `Monterey 12.4`
java=`adopt:11`

Sorry for the lack of information and lame bug report, I don't even know where to begin to resolve this issue (log locations , config files, etc.)

**Comment by kpodsiad** [comment]
This seems familiar, I think that you need to kill bloop process. Run `jps` and then pick pid for a `Server` and run `kill -9 <pid>`.

This should help but nobody knows why it's needed :|

**Comment by kubukoz** [comment]
I'm hitting something like this on a daily basis (CLI / IDE hanging), not even sure it's M1-specific. I have a heap/thread dump if that helps.

**Comment by kubukoz** [comment]
Some profiler output too:

<img width="1287" alt="image" src="https://user-images.githubusercontent.com/894884/197055324-231ae847-4886-4934-a38d-8d4ad850cda1.png">

**Comment by kubukoz** [comment]
This is plain bloop, but I feel like it's more frequent if scala-cli's bloop is also running...

**Comment by tgodzik** [comment]
That's another argument to migrate both. Need to work on that soon :thinking:

**Comment by tgodzik** [comment]
We switched a lot with Bloop 2.0.0, could anyone confirm if this helped? For Metals you will need to update to the newest snapshot to check

**Comment by kubukoz** [comment]
I haven't seen it in a while.

**Comment by tgodzik** [comment]
We can reopen if anyone sees this again.
