### ISSUE TITLE
Use `akka` for integration tests and benchmarks

### ISSUE THREAD

**Issue by jvican** [scalacenter/bloop#181]
Akka is a good project to add to our integration test suite and benchmark it to test the impact of our changes. We should add it to our project so that we have results about it too. The akka sbt build is not trivial too, and that will give us an extra assurance that projects of such a high importance work.

**Comment by olafurpg** [comment]
Another personal favorite of mine is slick/slick, it's less heavy than akka but is still interesting both as a build (codegen, many modules) and the code patterns used (heavy path dependent types, type inference, although that's less interesting for bloop).
