### ISSUE TITLE
Canceling a watch command sometimes causes the build server to stop

### ISSUE THREAD

**Issue by s-nel** [scalacenter/bloop#1835]
When I run several CLI bloop commands (without `--watch`) one server is used for all the commands, but when I cancel the watch command with ctrl-c SIGINT, the server process sometimes exits. The next bloop command I run starts a new server and has to recompile everything.

Steps to reproduce intermittent:
1. `bloop compile foo --watch`
   ```
   No server running at 127.0.0.1:8212, let's fire one...
   Resolving ch.epfl.scala:bloop-frontend_2.12:1.5.3...
   Starting bloop server at 127.0.0.1:8212...
   Attempting a connection to the server...
   Attempting a connection to the server...
   Attempting a connection to the server...
   ```
3. Notice that the server is running `jps -v | grep Server`
4. Send SIGINT
5. Notice that the server is no longer running `jps -v | grep Server`
6. `bloop compile foo --watch`
   ```
   No server running at 127.0.0.1:8212, let's fire one...
   Resolving ch.epfl.scala:bloop-frontend_2.12:1.5.3...
   Starting bloop server at 127.0.0.1:8212...
   Attempting a connection to the server...
   Attempting a connection to the server...
   Attempting a connection to the server...
   ```

Environment: 
```
bloop v1.5.3

Using Scala v2.12.15 and Zinc v1.6.0
Running on Java JDK v11.0.16
```

M1 Mac 12.6

Are there logs for the build server I can check?

**Comment by dos65** [comment]
Thanks for reporting!
It is a regression from #1759 . Will look at it

**Comment by dos65** [comment]
Oh you noticed that you use bloop 1.5.3 then it shouldn't be related to #1759 and it's an old behavior

**Comment by s-nel** [comment]
I'll upgrade and reopen if I run into this again. Thanks
