### ISSUE TITLE
Bloop 1.5.3 is being served as 1.5.4

### ISSUE THREAD

**Issue by japgolly** [scalacenter/bloop#1836]
1. Go to https://github.com/scalacenter/bloop/releases/tag/v1.5.4
2. Download `bloop-x86_64-pc-linux`
3. Run `chmod 755 bloop-x86_64-pc-linux`
4. Run `bloop-x86_64-pc-linux about`

Output is:

```
bloop v1.5.3

Using Scala v2.12.15 and Zinc v1.6.0
Running on Java JDK v11.0.16 (/usr/lib/jvm/java-11-graalvm)
  -> Supports debugging user code, Java Debug Interface (JDI) is available.
Maintained by the Scala Center and the community.
```

**Comment by tgodzik** [comment]
Thanks for reporting, did you shut down the old Bloop server beforehand? It shows the correct version for me.

You can use `bloop exit` for that

**Comment by windymelt** [comment]
You saved my time. thank you!

**Comment by tgodzik** [comment]
> You saved my time. thank you!

Glad to hear it, we can close this for now and reopen if another issue like this pops up.
