### ISSUE TITLE
Don't use the bloop shell for benchmarks

### ISSUE THREAD

**Issue by Duhemm** [scalacenter/bloop#184]
Bloop shell was just created for prototyping and easing development while Nailgun integration was very experimental. However, we ended up using it also for the benchmarks.

It'd still be nice to finally remove it, since it isn't demonstrating how Bloop is supposed to be used.

Todo before re-removing Bloop shell:

- [ ] Stop using Bloop shell for the benchmarks
- [x] Remove all mentions of Bloop shell from the docs
- [x] Update `bin/install.sh` to no longer install Bloop shell

Ref #168  #171  #180

**Comment by jvican** [comment]
I've changed the title of this issue since the work in two out of three ticket items has already been completed in related pull requests. Now, the only thing missing here is removing the bloop shell for benchmarks.

**Comment by jvican** [comment]
Let's just close this. We can live with our tiny shell, as it's actually not that bad for things like benchmarking. :smile:
