### ISSUE TITLE
Consider starting to use Mima

### ISSUE THREAD

**Issue by ckipp01** [scalacenter/bloop#1846]
I just realized in https://github.com/com-lihaoyi/mill/pull/2088 that the bump from 1.5.3 to 1.5.4 broke compatibility due to https://github.com/scalacenter/bloop/pull/1774 being added. In reality that shouldn't have been a patch release. I think adding something like https://github.com/lightbend/mima would help here.

**Comment by tgodzik** [comment]
Good idea! We should at least add it for the config module, since that might be used by the additional plugins.

**Comment by tgodzik** [comment]
Although, this should not really be na issue aside from updating the dependency. I can't imagine we would end up with a conflict with two libraries using Bloop configuration :thinking:

**Comment by ckipp01** [comment]
> Although, this should not really be na issue aside from updating the dependency.

Well the `apply` changed since the signature of `Project` changed, which is a breaking change.

**Comment by tgodzik** [comment]
I just meant that we should have a dependency hell kind of issues and only compile issues when updating. We can add mima for sure, it's just I was worried for a second it might be a bigger issue.

**Comment by julienrf** [comment]
I also recommend following a well defined versioning scheme. Not just to avoid issues like dependency hell, but to clearly signal the type of API changes between releases.

**Comment by ckipp01** [comment]
We can close this now since I split out config and started using MiMa in https://github.com/scalacenter/bloop-config.
