### ISSUE TITLE
Importing project in VSCode+Metals hangs indefinitely in 1.5.4 (vs 1.5.3 where it works)

### ISSUE THREAD

**Issue by kovacshuni** [scalacenter/bloop#1848]
## Facts:

- Importing a large project with many submodules
- Bottom right corner of metals writes Importing... and the ▯ like rectangular character moves very slowly. Keeps ongoing indefinitely.
- If I reimport the project, it re-generates the bloop.json files, but after all still I just receive this error: _Using presentation compiler only._
- noticed that Metals 0.11.9 will launch bloop 1.5.4 but when I downgrade the project (project settings) to Metals 0.11.8 bloop 1.5.3 is used
- Metals 0.11.8 and bloop 1.5.3 the project quickly jumps onto the Indexing... stage and after that starts to compile each submodule and finishes the import. One can navigate quickly, easily, everything works.

## Notes:
I can't share my project because it's private, property of a company.
How can I give you logs about what's happening?

**Comment by tgodzik** [comment]
Thanks for reporting! Could you retry with the newest snapshot `1.5.4-14-7cb43276`? There was a bug which might have caused this issue. You can just change the bloop version setting.

Alternatively, if that doesn't work, it would be good to identify what is the exact problem with Bloop. Do you run with with the same server version or do you restart it when prompted? Is there a specific change in `.json` files that causes the issue? Is there anything in the logs?

We can also try getting a jstack of the Bloop process to see where it's hanging.

What build tool are you using for the project?

**Comment by kovacshuni** [comment]
Does seem to work with bloop `1.5.4-14-7cb43276`

Thanks for the quick response!

**Comment by tgodzik** [comment]
Thanks for confirming, I will do a release soon and update it in Metals.
