### ISSUE TITLE
Handle error output in our streams

### ISSUE THREAD

**Issue by jvican** [scalacenter/bloop#192]
I think we're not handling error output in our streams, and we only redirect output streams (stdout) to loggers.

**Comment by Duhemm** [comment]
`System.err` and `System.out` are redirected to the best of my knowledge:

https://github.com/scalacenter/bloop/blob/d292681b23628347ab003c60d018ea9bc8b28c66/frontend/src/main/scala/bloop/exec/MultiplexedStreams.scala#L14-L15

https://github.com/scalacenter/bloop/blob/d292681b23628347ab003c60d018ea9bc8b28c66/backend/src/main/scala/bloop/logging/ProcessLogger.scala#L20-L27

**Comment by jvican** [comment]
I remember seeing somewhere it wasn't the case, but perhaps it was fixed in one of your latest PRs and didn't update my knowledge :smile:. I'm closing.
