### ISSUE TITLE
Blooop 1.5.6 reports wrong version.

### ISSUE THREAD

**Issue by kczulko** [scalacenter/bloop#1991]
Blooop 1.5.6 reports wrong version (1.5.4).

Discovered with `nix`. [This derivation](https://github.com/NixOS/nixpkgs/blob/5ed481943351e9fd354aeb557679624224de38d5/pkgs/development/tools/build-managers/bloop/default.nix) when installed, returns bloop version `1.5.4` 

Indeed, when you download this release manually it reports `1.5.4`.

```
$ wget "https://github.com/scalacenter/bloop/releases/download/v1.5.6/bloop-x86_64-pc-linux";
$ # patchelf stuff goes here...
$ [nix-shell:~/Downloads]$ ./bloop-x86_64-pc-linux -h
bloop 1.5.4
Usage: bloop [options] [command] [command-options]
```

And this is what I get in my nixos (notice the bloop version in the nix store path)

```
$ /nix/store/3q7pj5qp0swqq1236lnfw4v0zg5zc6qd-bloop-1.5.6/bin ~ ./bloop -h
bloop **1.5.4**
Usage: bloop [options] [command] [command-options]
```

**Comment by tgodzik** [comment]
Thanks for reporting! Did you restart the Bloop server? If it was running before it will not be killed automatically on update.

**Comment by kczulko** [comment]
:facepalm: 
Thank you @tgodzik . You're right :) Restarting helps :)
