### ISSUE TITLE
"--watch" mode should print something when successful compilation is complete

### ISSUE THREAD

**Issue by propensive** [scalacenter/bloop#202]
When using `bloop compile --watch`, multiple messages are displayed saying, for example,
```
Compiling 1 Scala source to '/somewhere/'...
```
but it's not possible to distinguish between compilation having successfully completed, and an ongoing, incomplete compilation.

Some sort of visual cue would be very helpful. The easiest solution would be to print an additional line when each successful compilation finishes.

**Comment by jvican** [comment]
This was addressed in a recent PR because we default to upstream Zinc's behaviour: we print "Done compiling." so that it is totally informative of what module has just been compiled and that compilation is obviously finished.
