### ISSUE TITLE
`bloop run --watch` runs even when compilation fails

### ISSUE THREAD

**Issue by propensive** [scalacenter/bloop#204]
I think that running should be conditional on successful compilation.

**Comment by propensive** [comment]
Just experimenting further, and it seems like bloop works as desired if the compilation failure is in the same project as the one being run, but not if the compilation failure happens in a dependent submodule.

If a dependent submodule fails, compilation appears to continue, using an earlier successful build.

**Comment by jvican** [comment]
I'll have a look at this when I'm done with the bsp implementation, should be easy to fix. Thanks for reporting Jon.

**Comment by propensive** [comment]
Seems like it should be, though it's more difficult to test whether it's actually fixed, I think.

As I mentioned on Gitter, let me know if you're interested in having a `docker` integration test setup.

**Comment by jvican** [comment]
I think this is fixed in current master. @propensive Could you please confirm? :smile:

**Comment by jvican** [comment]
I confirm this is fixed.

**Comment by jvican** [comment]
OK, just found a nitpick though. I'm fixing it and releasing it in M8.

**Comment by propensive** [comment]
Ok, give me a shout when M8 is actually released. Note that in M7, filewatching was more or less unusable for me. (There's a separate issue about this, and *that* will be the first thing I check when I upgrade!)

**Comment by jvican** [comment]
M8 is already out!
