### ISSUE TITLE
Errors are output in reverse order

### ISSUE THREAD

**Issue by propensive** [scalacenter/bloop#205]
Is this a bug or a feature?! It seemed weird at first, but I could learn to love it, as the "first" errors appear in the part of the output I see.

I don't mind what the default is, but I think this should be configurable.

**Comment by jvican** [comment]
> Is this a bug or a feature?! It seemed weird at first, but I could learn to love it, as the "first" errors appear in the part of the output I see.
  
It's a feature, it's the way sbt-errors-summary works. You have a way to disable it with `--reporter`.

**Comment by propensive** [comment]
Cool, I quite like it, actually. Just took me by surprise! ;)

**Comment by jvican** [comment]
I don't want to have open issues in the tracker that are docs, so I'm closing them. I'll explain how to access them in the developer guide in our website soon.
