### ISSUE TITLE
A developers' guide would be useful

### ISSUE THREAD

**Issue by propensive** [scalacenter/bloop#208]
It would be nice to be able to work on my own changes for `bloop`. Unfortunately, the installation instructions in the README file do not scale well: the build/install cycle takes many minutes, and (from what I can tell, though it's too time-expensive to test more than twice) installing using the script uses `coursier` which expects to find an artifact in a remote repository somewhere, corresponding to a git hash. If this does not exist (because, obviously, you didn't publish your experimental changes!), the installation fails.

That's the naive person's approach to trying to make a single change, though I'm sure there's a nicer development experience available to potential `bloop` developers, even if it does involve `sbt`, which I'm sure is just a short explanation away from me...

I'm happy to write up some instructions, if someone can give me some pointers.

**Comment by Duhemm** [comment]
I started something in #287

**Comment by jvican** [comment]
The developers guide has been merged in #287, try it out and let us know if it's useful or which things you'd like us to elaborate on.
