### ISSUE TITLE
Incremental compile is broken in 1.5.10

### ISSUE THREAD

**Issue by hamnis** [scalacenter/bloop#2140]
Seems like something happened when upgrading zink.
Now everything recompiles all the time regardless if anything in a module has been changed.

1.5.9 works fine.

**Comment by tgodzik** [comment]
Thanks for reporting! It seems to happen for me too, though I am not entirely sure how one of the recent changes would cause any problems.

**Comment by tgodzik** [comment]
It should be fixed in 1.5.11, sorry for the issues! Let us know if you see any more issues

**Comment by tgodzik** [comment]
Looks like this is fixes as far as I can see.
