### ISSUE TITLE
Bloop home directory on Linux

### ISSUE THREAD

**Issue by untainsYD** [scalacenter/bloop#2142]
Can I change `bloop` home directory: `$HOME/.bloop` on Linux? Are there any plans to add XDG specification support?

**Comment by tgodzik** [comment]
I don't have time to look into that currently, but this shouldn't be hard to do if anyone is willing.

**Comment by ckipp01** [comment]
btw this is a duplication of https://github.com/scalacenter/bloop/issues/1844.
