### ISSUE TITLE
sbt-bloop (0.5.12) suddenly started compiling when running sbt bloopInstall

### ISSUE THREAD

**Issue by hamnis** [scalacenter/bloop#2201]
I had a compilation error and then I got a wall of text full of Value(...) which I unfortunately cant submit here without heavy editing (proprietary repo).

Fix for us was to downgrade to 0.5.11 which does not do this.

**Comment by tgodzik** [comment]
This is fixed, I will release this week. Sorry about this!

**Comment by hamnis** [comment]
is there also a way to avoid compiling when generating the bloop files?

**Comment by tgodzik** [comment]
There release is out, let me know if there are any further issues.
