### ISSUE TITLE
Is there an older version of bloop that I can use with Gradle 2.x ?

### ISSUE THREAD

**Issue by nbauma109** [scalacenter/bloop#2310]
I have multi-module gradle project with some proprietary vendor build files that are tied to version 2.x of Gradle (because they're using some 2.x langage idioms) and one of the projects is a scala project building with gradle.

Can I use bloop ?

Reading the docs, it was unclear to me whether bloop integration with gradle shows the errors in Eclipse in realtime, as you save your files, or if a full build is required.

**Comment by Arthurm1** [comment]
The earliest version of the bloop gradle plugin required minimum of gradle 3.0.

**Comment by tgodzik** [comment]
And it doesn't really work with eclipse. Might be worth using https://scala-ide.org/ for your case. If the version of Gradle is old then the version of Scala is probably also. 

The other option is to upgrade to at least Gradle 3 and then you can use [Metals](scalameta.org/metals)
