### ISSUE TITLE
Source generator config should be able to track a script file as an input

### ISSUE THREAD

**Issue by bishabosha** [scalacenter/bloop#2386]
If the source generator command is itself a script that is expected to change often, then bloop does not track it as an input, therefore if the generator input files do not change, but the script file does (which might change the output of the source generator), then the generator will not be ran again.

I think a fix would be to allow to add "unmanaged" inputs - i.e. not passed as arguments to the generator command, but changes to those inputs will trigger running the command again. Then a bsp client could pass the script file as one of these unmanaged inputs.

Relevant for Scala CLI source generators - https://github.com/VirtusLab/scala-cli/issues/610

**Comment by tgodzik** [comment]
Makes sense https://github.com/scalacenter/bloop-config/pull/95
