### ISSUE TITLE
Bloop doesn't work for multi project build in gradle

### ISSUE THREAD

**Issue by q-joshualeong** [scalacenter/bloop#2394]
Hi all, 

I’m using gradle for my project but can’t seem to get metals working across multiple sub projects. I’m also new to bloop.

I’ve  done up a minimal kinda project example of what my project structure looks like. 

https://github.com/q-joshualeong/example-scala-metals

When I do gradlew bloopInstall i see the .bloop folder has bloop config files generated and i can see that the classpath section is pointing to “.bloop/data-source-common/build/classes” but there isn’t actually any such folder. So I’m abit confused what I’m missing here. 

Thanks in advance guys!

**Comment by tgodzik** [comment]
I can see that the children projects are compiled correctly, but the middle projects do not have any Scala source files, so it's expected that the classpath for them is empty. `common-model` and `person-model` do have sources compiled. What would you expect to happen otherwise?

**Comment by q-joshualeong** [comment]
Hi turns out it's my lack of understanding of bloop. No issues with bloop, I realised it was due to a config I missed out when configuring nvim-metals plugin on neovim.
