### ISSUE TITLE
Build server does not provide information on main entry points

### ISSUE THREAD

**Issue by soronpo** [scalacenter/bloop#2413]
Since the build server does not provide information on main entry points, Metals cannot detect main entry points that are generated by a compiler plugin.

For example:
```scala
//> using scala 3.5.0
//> using dep io.github.dfianthdl::dfhdl::0.7.1
//> using plugin io.github.dfianthdl:::dfhdl-plugin:0.7.1

import dfhdl.* 
@top class Foo extends EDDesign
```
The `@top` annotation causes the plugin to create an object named `top_Foo` with a `main` method. Scalac does detect `top_Foo`, but Metals does not.
After discussion about this on the Metals discussion board (https://github.com/scalameta/metals/discussions/6729#discussioncomment-10477069), I'm opening this ticket for follow-up. IMO it makes sense that the main entry point information will be directly available via BSP instead of the current guess-work logic implemented by the tools.

**Comment by tgodzik** [comment]
I tried to reproduce the issue today and it seems you can run from launch.json. So this is actually not an issue, sorry about that.
