### ISSUE TITLE
Bloop 2.0.0 no longer reads JVM options from `$HOME`?

### ISSUE THREAD

**Issue by filipwiech** [scalacenter/bloop#2417]
I could be wrong, but from what I remember in the older Bloop versions I could configure the global JVM options using a config file located in the `$HOME/.bloop/bloop.json` ([as described in the documentation](https://scalacenter.github.io/bloop/docs/server-reference)), with for example `{"javaOptions":["-Xmx2g"]}`. But it seems that Bloop 2.0.0 is ignoring those settings, instead always starting with a set of hardcoded flags from here:
https://github.com/scalacenter/bloop/blob/1a586e3e74eb71179d4128377b8c71134e4ec371/bloop-rifle/src/main/scala/bloop/rifle/BloopRifleConfig.scala#L75-L84
In the same file I can see ways to override the configuration with either environment variable or system property, but not through the previously available JSON. Has this indeed changed (and if so, on purpose), or am I just missing something here? :slightly_smiling_face:

**Comment by tgodzik** [comment]
Yes, that got changed, but metals.bloopProperties should work correctly. I need to update the docs.

**Comment by filipwiech** [comment]
Thanks for the info, I will adjust my setup then. :+1: Should I close this issue then? :slightly_smiling_face:

**Comment by tgodzik** [comment]
It should remind me to update the docs. Will do that soon I hope

**Comment by simao** [comment]
In addition to the scala options, it seems to me that the `javaHome` property is now also not read from `.bloop/bloop.json`, is this correct? The only way now to prevent the build server from downloading and using jvm 17 is by setting `JAVA_HOME`?
