### ISSUE TITLE
Expand test discovery to detect methods in test suites that evaluate to tests.

### ISSUE THREAD

**Issue by masonedmison** [scalacenter/bloop#2435]
The motivation for this is that I regularly interact with code bases that have tests like
```scala
class MySuite extends munit.FunSuite {
  private def helper(name: String, num: Int): String =
    s"$name$num"

  test(helper("foo", 42)) {
    val obtained = 42
    val expected = 42
    assertEquals(obtained, expected)
  }
}
```
and it would be very nice to have code lens for these tests.

IIUC, Metals will make an RPC call to bloop to get test classes, and whatever is returned will then be used to to create code lens. From the little bit of investigation I've done so far, it seems like tests are discovered [here](https://github.com/scalacenter/bloop/blob/main/frontend/src/main/scala/bloop/engine/tasks/TestTask.scala#L354). I think it could be cool to try to encrich the test discovery to capture tests like those I've shared above. What would you guys think about this? Also, please correct me if I've said anything incorrectly.

**Comment by tgodzik** [comment]
Thanks for reporting! It's actually super hard to add discovery for such tests since the name will be created only at runtime. So we would need to run the tests to know which tests to run, which is a bit of a conundrum :sweat_smile: 

I actually removed showing those tests because this would quickly end up flaky.

Would be great to make it work, but I don't see how currently :/

**Comment by tgodzik** [comment]
Filtering is certainly an option, but we have no way of actually finding the blob to use 100% from a code.

Let's say we have a test using munit:
```scala
val n = 24
test((n*34).toString){
   .....
}
```
how would you go about finding the part to add after `--`? I have no idea how to do it

**Comment by masonedmison** [comment]
Closing this as Bloop isn't currently responsible for discovering individual tests.
