### ISSUE TITLE
prebuilt in released bloop-coursier.json seems wrong

### ISSUE THREAD

**Issue by gonsolo** [scalacenter/bloop#2444]
In all releases up to v2.0.0 there is a line like
` "prebuilt": "https://github.com/scalacenter/bloop/releases/download/v${version}/bloop-${platform}",
`
but in v2.0.1 it looks like this
` "prebuilt": "$PREBUILT",
`
which breaks the Arch Linux build:
`Exception in thread "main" java.net.MalformedURLException: No protocol found in URL $PREBUILT
        at coursier.paths.CachePath.localFile(CachePath.java:63)
	at coursier.cache.FileCache$.localFile0(FileCache.scala:395)
`

**Comment by tgodzik** [comment]
I had to manually release and missed that one :/ I can do a follow up release and fix that

**Comment by tgodzik** [comment]
Should be fixed in a follow up release https://github.com/scalacenter/bloop/pull/2445

**Comment by gonsolo** [comment]
Thanks.
