### ISSUE TITLE
Fork or vendor jsonrpc4s to address bugs in it

### ISSUE THREAD

**Issue by alexarchambault** [scalacenter/bloop#2479]
https://github.com/scalacenter/bloop/issues/2478 originates from a bug in [jsonrpc4s](https://github.com/jvican/jsonrpc4s).

Could you create a fork of it, in order to publish a version fixing this bug and use it in Bloop?

For easier maintenance, the jsonrpc build could be switched to scala-cli, like done [here](https://github.com/alexarchambault/jsonrpc4s/commit/0ec4a357f8542d00c5e9fc8d6a6cab076731b877) for example.

**Comment by tgodzik** [comment]
Sure, I was actually hoping to switch to  just bsp4j, but that hasn't happened yet. I can also just use your fork now? Only fork it once needed

**Comment by alexarchambault** [comment]
Sure, you can use my fork, I can give you write access

**Comment by alexarchambault** [comment]
Just sent the invite
