### ISSUE TITLE
move - FileAlreadyExistsException

### ISSUE THREAD

**Issue by mbovel** [scalacenter/bloop#2506]
I had some problems with Metals when working on Dotty yesterday. Looking at the logs, I saw a `FileAlreadyExistsException` exception. I am not sure if this is the root cause or not.

[reports.zip](https://github.com/user-attachments/files/17713876/reports.zip)

<img width="1295" alt="image" src="https://github.com/user-attachments/assets/4841784a-4ce2-4bd3-8d28-e16895159af7">

**Comment by mbovel** [comment]
Might be related to #2008?

**Comment by tgodzik** [comment]
This shouldn't be a big issue unless it repeats itself even after reloading. What kinds of problems were you having? I did some improvements in Bloop 2.0.5, which will be released soon in new metals.

**Comment by mbovel** [comment]
>  What kinds of problems were you having?
I think the general problem is Bloop trying to recompile many things, making Metals slow and unresponsive. I seem to have this problem often: `scala3-compiler` getting recompiled over and over when there are issues. I don't remember the details in this specific instance, but I will fill issues when I observe it again!

Should I close this issue if you fixed it in 2.0.5?

**Comment by tgodzik** [comment]
> I think the general problem is Bloop trying to recompile many things, making Metals slow and unresponsive.

Yeah, not sure how to solve this. We should avoid excessive recompilation, might be worth a separate issue in Metals.

The file not found exception should be fixed, let me know if you see it again!
