### ISSUE TITLE
Working directory for bloop run is root

### ISSUE THREAD

**Issue by olafurpg** [scalacenter/bloop#254]
I installed bloop via homebrew and the working directory with `bloop run` seems to be root `/`

```
$ bloop run -p vork --args --in --args docs
error: File /docs does not exist.
```

Adding `$(pwd)/` fixes the problem
```
$ bloop run -p vork --args --in --args $(pwd)/docs
```

I would expect bloop to use the working directory from where the nailgun client is invoked, which might require forking. Not sure if setting `sys.props("user.dir")` could work

**Comment by Duhemm** [comment]
Thanks for the report!

This is easy to fix when `fork = true`, but it's going to be a bit more involved when running in the same JVM. We'll probably do as we did with the standard streams.
