### ISSUE TITLE
bloop test does not test/compile test config

### ISSUE THREAD

**Issue by olafurpg** [scalacenter/bloop#256]
At commit https://github.com/olafurpg/vork/commit/85e63f7dff59b2a6051f77fbea0c7ed3e17b4a80
```
Projects loaded from '/Users/ollie/dev/vork/.bloop-config':
 * root
 * runtime
 * vork

$ bloop test -p vork
// nothing
$ sbt vork/test
...
[info] FailSuite:
[info] - fail
[info] - triplequote
[info] - fail-error
[info] - fail-success
[info] - mixed-fail-success-error
[info] Run completed in 4 seconds, 378 milliseconds.
[info] Total number of tests run: 28
[info] Suites: completed 9, aborted 0
[info] Tests: succeeded 28, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
[success] Total time: 10 s, completed Feb 12, 2018 12:04:03 PM
```

I tried

```
$ bloop test -p vork-test
[E] No projects named 'vork-test' found in '/Users/ollie/dev/vork/.bloop-config'.
[E] Use the `projects` command to list existing projects.
```

**Comment by Duhemm** [comment]
Would you by any chance have used `bloopGenerate` instead of `installBloop`? I can reproduce your output with `bloopGenerate`, but everything works out great (😄) with `installBloop`.

We shouldn't expose `bloopGenerate`

**Comment by olafurpg** [comment]
Indeed, I ran bloopGenerate. I did not find `installBloop` because I opened sbt and `bloop<TAB>` and took whatever was the most likely candidate. By convention, sbt plugins should prefix their tasks by the plugin name so I think it would make sense to rename installBloop to bloopInstall.

**Comment by olafurpg** [comment]
I can confirm that test works with `bloopInstall`, thanks!
