### ISSUE TITLE
Print out total compile time on success/error

### ISSUE THREAD

**Issue by olafurpg** [scalacenter/bloop#258]
Currently, bloop prints out "Done compiling." after compilation. It would be nice if it included the total time it took to compile, like

```
[I] Total time: 10 s
```

Even nicer would be to include total number of lines compiled, but that's a separate ticket probably.

**Comment by Duhemm** [comment]
You can see how long the compilation took by adding `--verbose` to your options.

Adding it to the current `Done compiling.` would be hard because this is a message that is output by Zinc (and which I would really much like to remove).

**Comment by jvican** [comment]
> Adding it to the current Done compiling. would be hard because this is a message that is output by Zinc (and which I would really much like to remove).
  
I think it's about time we send a PR upstream fixing this. And not only saying how much time it took, but also which module was compiled...
