### ISSUE TITLE
Consider auto start server

### ISSUE THREAD

**Issue by Duhemm** [scalacenter/bloop#259]
As suggested by @olafurpg, we may want to have Bloop server start automatically after installation via Homebrew, instead of telling the user to type `brew services start scalacenter/bloop/bloop`.

Pros:
 - Smoother installation
 - No risk of the user missing this message and not being able to use Bloop
 - Users that don't want it can still disable it.

Cons:
 - Waste of resources? Not sure about that.

**Comment by jvican** [comment]
I discussed about this in #209.

**Comment by jvican** [comment]
Now that we have OSX and Systemd support I’ve realized this is not something worth investing in. Users will need anyway to control logs of the server, and given how long running we’re aiming for this process to be and how critical this is to maximize raw compilation speed, I’m closing the ticket. I feel an automatic server start wouldn’t emphasize this enough. Feel free to comment if you disagree and we can reconsider.
