### ISSUE TITLE
BSP `Local` communication channel doesn't work on Windows

### ISSUE THREAD

**Issue by Duhemm** [scalacenter/bloop#281]
See:

https://github.com/scalacenter/bloop/pull/216/files#diff-e35ad9d16b8aa5f828fd6950e0a7caf0R57
https://github.com/scalacenter/bloop/pull/216/files#diff-e35ad9d16b8aa5f828fd6950e0a7caf0R74

**Comment by jvican** [comment]
Windows CI support is not yet merged, so I'm closing this ticket until the PR is picked up again :smile:.

**Comment by Duhemm** [comment]
Reopening now that we have a Windows CI

**Comment by jvican** [comment]
https://github.com/scalacenter/bloop/commit/c86c6fc47e90598d8042b3faa09923ecf7c3941a doesn't fix this. Still open until an investigation is carried out.

**Comment by jvican** [comment]
@jackkoenig this is the ticket you're working on, feel free to push any progress update or link to it from a PR whenever it's ready

**Comment by jvican** [comment]
@jackkoenig Are you still interested in having a look at this? If so I'll assign the ticket to you

**Comment by jackkoenig** [comment]
I am interested but I'm not sure if I can commit to it. Is this related/required for getting named pipes working in `bloopgun` or are these separate issues?

**Comment by jvican** [comment]
They are the same issue

**Comment by tgodzik** [comment]
This should now work after merging the Bloop fork with support for named sockets.
