### ISSUE TITLE
Add a drop-in replacement for the scalac command line interface

### ISSUE THREAD

**Issue by olafurpg** [scalacenter/bloop#289]
It would be nice if there was a `bloop scalac` command that could be used as a drop in replacement for the `scalac` command line interface. This would enable users to `alias scalac = "bloop scalac"` and enjoy always-hot compilation from the command line.

**Comment by jvican** [comment]
This is a good idea but we lack manpower to implement it! I'd imagine this would behave as `fsc` did back in the day. If somebody is willing to contribute it, let's reopen.
