### ISSUE TITLE
Add anchor links in the website

### ISSUE THREAD

**Issue by olafurpg** [scalacenter/bloop#297]
Currently it's a bit difficult to link to a section of a page like https://scalacenter.github.io/bloop/docs/getting-started-sbt/#configuring-sbt (see `#configuring-sbt` suffix). I use "Inspect element"

<img width="441" alt="screen shot 2018-02-28 at 17 02 00" src="https://user-images.githubusercontent.com/1408093/36797862-58a4d78a-1ca9-11e8-854a-82a905f5af94.png">

It would be nice to have anchor links next to the headers like

<img width="314" alt="screen shot 2018-02-28 at 17 04 16" src="https://user-images.githubusercontent.com/1408093/36797899-7674649c-1ca9-11e8-8323-371d59490366.png">

There's usually a simple option to enable this in static site generators.

**Comment by jvican** [comment]
I have registered a feature request upstream: https://github.com/jeblister/kube/issues/22. Implementing it ourselves doesn't seem difficult, but it's better to ask upstream first.

**Comment by jvican** [comment]
The search support in the website has made this pretty easy because when you search it automatically brings you to the anchor heading.

**Comment by jvican** [comment]
This is a nice ticket, but with the search capabilities and the short doc pages we have I don't think it's something worthy of being open in the issue tracker for now. If there's interest in this, either by a contributor or by a spree author, we can reopen.
