### ISSUE TITLE
Copy-paste friendly addSbtPlugin

### ISSUE THREAD

**Issue by olafurpg** [scalacenter/bloop#298]
Currently, the sbt-bloop installation instructions require the user to manually insert the latest bloop version in the addSbtPlugin command.

<img width="890" alt="screen shot 2018-02-28 at 17 06 07" src="https://user-images.githubusercontent.com/1408093/36797981-af649768-1ca9-11e8-8fd3-3c0b6922296d.png">

It would be nice if the command was copy-pasteable. Alternatively, it would be nice to have at least a maven badge displaying the latest published version number.

**Comment by jvican** [comment]
We cannot link to the badge because it shows the latest on-merge release, not the latest release. The best way of enabling this use case is adding support for tut in our docs, which is something we have to do anyway, and then get the latest release from `git describe`.

**Comment by MasseGuillaume** [comment]
Scaladex knows this:

[![Latest version](https://index.scala-lang.org/scalacenter/bloop/sbt-bloop/latest.svg?color=orange&style=flat-square)](https://index.scala-lang.org/scalacenter/bloop/sbt-bloop)

**Comment by jvican** [comment]
We can add that for now until we have the tut-based solution, which is ultimately the solution I favor because our docs won't depend on Sonatype/Bintray delays to show us the latest version. :+1:

**Comment by olafurpg** [comment]
> Sonatype/Bintray delays 

This is sometimes a blessing. In my projects where the docs update after merge I've had people unhappy about the docs showing unreleased version numbers (for example, pending sync to maven central)

**Comment by MasseGuillaume** [comment]
The disadvantage of the solution above is that you cannot copy paste.

**Comment by jvican** [comment]
Guillaume implemented a JS script to get the version from Central. In the future, we'll have tut support so that if that fails we at least get the latest version that was published from the dev environment.
