### ISSUE TITLE
Offload compilation from sbt to bloop

### ISSUE THREAD

**Issue by jvican** [scalacenter/bloop#315]
The idea is to have our sbt integration delegate the `compile`, `test` and `run` tasks to bloop via BSP. The benefit of this is that sbt can always reuse hot compilers, no matter if users `reload` their builds or open multiple sbt shells in different projects.
  
While `bloop` can still be used via CLI (and it's the recommended workflow, since sbt is just too memory consuming and blows up from time to time), this issue tries to integrate as much as possible with people's workflow so that they don't need to get used to working with the bloop CLI if they feel lazy or don't like it.

**Comment by julienrf** [comment]
Is there any update on this? Do you plan to address this issue, and do you have an ETA?

**Comment by jvican** [comment]
I'm narrowing down the scope of this ticket to only compilation, integrating bloop's test and bloop's run with sbt is a non-goal of this ticket.

**Comment by rtar** [comment]
Would not this feature be awesome for using on continuous integration servers such as Jenkins? I.e. you have various sbt tasks one after another, interleaved with deployments etc. and then you can have your compiler there hot and waiting for sbt to use it.
