### ISSUE TITLE
Rename blp-server to bloop-server

### ISSUE THREAD

**Issue by olafurpg** [scalacenter/bloop#320]
blp-server pros:
* tab completion

blp-server cons:
* not self-explanatory. One more thing the user needs to learn, whereas `bloop-server` needs no explanation
* cryptic named long-running binary process that appears in htop/activity monitor

Most users won't invoke blp-server manually because it can be handled by something like `services start bloop`. And even if you invoke it manually, you do it once and let it run in the background so the tab completion is not that desirable.

Same applies to blp-coursier.

cc/ @propensive

**Comment by olafurpg** [comment]
Alternatively, we could tweak the `bloop` python client to support `bloop startserver` and the user never needs to know the difference between bloop and bloop-server.

**Comment by jvican** [comment]
I lean towards having `bloop server --start` so that if we, in the future, want to add more flags to control the server, we can.

**Comment by propensive** [comment]
Aesthetically, @jvican's suggestion is the best I've seen. :)
