### ISSUE TITLE
Rename `--filter` to `--only`

### ISSUE THREAD

**Issue by jvican** [scalacenter/bloop#327]
Instead of `bloop test my-tests -f test.Foo`, it should be `bloop test my-tests -o test.Foo`. It's more idiomatic and people are already used to that style.

**Comment by olafurpg** [comment]
Would it be possible to support without the flag `bloop test core com.FooSuite`?

**Comment by jvican** [comment]
What do you do when there is more than one project? `bloop test core foo bar com.FooSuite`? What's the criteria that allows us to tell project and filters apart?

**Comment by olafurpg** [comment]
That's a good question. I haven't used that functionality before because it's not supported in sbt.

One option would be to separate the filter with `--` so the command becomes `bloop test core foo bar -- com.FooSuite`. I use this functionality frequently with scalatest to run an individual test or enable full stack traces with `core/testOnly *FooSuite -- -z -oF`

**Comment by jvican** [comment]
The issue here is that `--` would be reserved for test options https://github.com/scalacenter/bloop/pull/291/files, just as sbt does (your input here is valuable @Duhemm, I don't remember if this holds anymore).
  
So, in this case, the only reasonable option left would be to have the filter in the test options too (and have them only at the beginning, since there's no CLI parser we can use for them). Example: `bloop test core foo bar -- com.FooSuite -z -oF`.
  
I'm not sure this is the way to go though, as I've said we would only support the filters that are at the beginning of extra args (after `--`) and not if they are at the end of extra args `-z -oF *FooSuite`.
  
@olafurpg Do you think `-o` is such a bad option after all?

**Comment by jvican** [comment]
I don't think there's a reasonable way to support several filters with ease. Given that it's not supported in sbt, I think it's fair that we support it under several `-o` args: `bloop test foo bar -o ch.epfl.scala.CoolSuite -o ch.epfl.scala.FunSuite`.

**Comment by jvican** [comment]
Note that for those test frameworks like junit that do support several test filters in their test options, you can do `bloop test foo bar -- ch.epfl.scala.CoolSuite ch.epfl.scala.FunSuite` if you want nicer syntax.
