### ISSUE TITLE
install.py in release is broken

### ISSUE THREAD

**Issue by valencik** [scalacenter/bloop#334]
The [install.py](https://github.com/scalacenter/bloop/releases/download/v1.0.0-M6/install.py) that makes it into the release assets on GitHub is broken as it contains python expressions before the almighty import `from __future__`.

The following should just be moved below the imports.
```
NAILGUN_COMMIT = "ebe7ab23"
BLOOP_VERSION = "1.0.0-M6"
```

**Comment by jvican** [comment]
Thanks for the heads up @valencik, @Duhemm has already a fix on its way to the PR queue.
