### ISSUE TITLE
Add docs to set up systemd to run bloop server

### ISSUE THREAD

**Issue by jvican** [scalacenter/bloop#337]
It would be great if Linux/*BSD users have a template they can copy-paste to install a systemd service in their machine that would run the bloop server in the background. This would be quite a big improvement in terms of usability for those users (e.g. me) because it would mean they don't need to manually handle the creation of the server themselves, and they can keep track of their lifetime over time.
  
Relevant links:
  
1. https://wiki.archlinux.org/index.php/systemd
2. https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/system_administrators_guide/sect-managing_services_with_systemd-unit_files

**Comment by jvican** [comment]
Another avenue we may want to consider is using desktop entries: https://wiki.archlinux.org/index.php/desktop_entries. We can still consider having both ways of starting up a service, but the good thing is that this mechanism works across different Linux distributions.
  
A desktop entry looks like the following one, extracted from jetbrains-toolbox:
  
```
[Desktop Entry]
Type=Application
Name=JetBrains Toolbox
Exec=/opt/jetbrains-toolbox/jetbrains-toolbox --minimize
Icon=/home/jvican/.local/share/JetBrains/Toolbox/toolbox.svg
StartupNotify=false
Categories=Development;IDE;
Terminal=false
X-GNOME-Autostart-enabled=true
StartupWMClass=jetbrains-toolbox
MimeType=x-scheme-handler/jetbrains;
Hidden=true
```
  
The good thing about desktop entries is that they are automatically started by the desktop environment on startup if they are XDG compliant. The desktop entries need to be in `$XDG_CONFIG_DIR/autostart`.

**Comment by jvican** [comment]
Kudos to @tues for picking this up :tada:.

**Comment by tues** [comment]
Hi @jvican, thanks for merging #440 (and thanks to the reviewers) 🙂

What about https://github.com/tues/bloop/tree/ticket/337-xdg? Do you want me to open a PR for that one as well?
I guess it's not very important to have both a systemd service and a desktop entry, but in case anyone is interested it looks like this: https://imgur.com/CU9mz3L

**Comment by jvican** [comment]
@tues it looks great! Didn’t know that Ubuntu shows desktop entries in the launcher. Can you PR the changes? 😄 it may be worth it explaining in which cases users should prefer desktop entries over systemd .

**Comment by tues** [comment]
Created PR.

KDE does the same and other DEs should do as well :slightly_smiling_face: 

By the way, I've found out that if `$XDG_CONFIG_HOME` is not set explicitly, then the default value is `$HOME/.config`, so we could probably reconsider installing systemd service and/or desktop entry automatically (a new issue for someone to pick?). I think systemd could be detected by checking if process with `PID = 1` has `systemd` in its name or if `systemctl` command is available.
