### ISSUE TITLE
Use custom reporter *from within Scalac*

### ISSUE THREAD

**Issue by jvican** [scalacenter/bloop#36]
This is a crazy idea.
  
I didn't realize this was possible as of 2.12: https://github.com/scala/scala/pull/4544.
  
I think it would be cool to experiment with better error messages only for 2.12.x. That approach would allow us to create a reporter that would understand concrete error messages (by using regexes, since we don't have context information of where those messages were created) and then prettify them.
  
Having this in bloop may be nice, but what I think it would be nicer is that we consider making this change upstream in scalac. If we make it upstream, we have the benefits of:
  
1. Much better implementation since we can touch the call sites creating the error messages.
2. Bigger impact and less ad-hoc solution.

**Comment by ShaneDelmore** [comment]
This sounds like it could be some variation of scala-clippy.  I love the idea.

**Comment by jvican** [comment]
We already have our own reporter via Zinc, I think that work on this area should happen in the actual compiler, and I would consider doing so in the future.
