### ISSUE TITLE
Remove one level of heading in Design Goals docs page

### ISSUE THREAD

**Issue by jvican** [scalacenter/bloop#368]
https://scalacenter.github.io/bloop/docs/bloop-basics/

**Comment by sid2201** [comment]
Hey @jvican ! I would like to take this one. Could you please let me know which heading needs resizing?

**Comment by jvican** [comment]
@sid2201 Cool :smile: Just decrease one level for all the headers, that should work!

**Comment by jvican** [comment]
This is fixed in master by #415.
