### ISSUE TITLE
No autocompletion for `bloopInstall` in sbt

### ISSUE THREAD

**Issue by jvican** [scalacenter/bloop#373]
`bloopInstall` is a global task key, and global task keys are for some reason not autocompleted in sbt. This is not a bug in bloop, so I'm not labelling it as such.
  
I don't know what we could do to fix this issue in bloop... Maybe scoping it `in ThisBuild` will fix it? Who knows.
  
I'm adding this so that our users are not confused if autocompletion doesn't work for this task. This will be alleviated when #140 happens.

**Comment by olafurpg** [comment]
I hit on this because `bloopIn<TAB>` completes to `bloopInternalClasspath` which is definitely what I wanted to do.

**Comment by jvican** [comment]
We should probably add a clarification in our docs.
