### ISSUE TITLE
Don't create extra folders when doing `bloopInstall`

### ISSUE THREAD

**Issue by MasseGuillaume** [scalacenter/bloop#378]
```
src/main/java
src/main/scala-2.12
...
etc
```

they had the same issue in ensime-sbt: https://github.com/fommil/ensime-sbt/commit/147315e0e4962e5355fc40b51a5576bfd1548db0

**Comment by jvican** [comment]
This is a problem in sbt/sbt, and it's probably caused because of `managedSources`. These files are not checked into the repo (folders is empty), so I'm closing this issue because this should be filed in sbt/sbt.

**Comment by MasseGuillaume** [comment]
This is fixed in `ensime-sbt`.

**Comment by jvican** [comment]
The directory watcher requires that all the watched source directories exist. Bloop is currently creating the directories for the watcher not to throw an exception.
  
If Bloop wasn't creating these directories, the watcher will fail or at best ignore them. The problem with that is that if a new file is created in `scala-2.12`, for example, it won't be picked up by the watcher, and the user will be forced to cancel the file watching and run the same command again for bloop to detect the change.
  
As this is a major inconvenience, and I deem the current behaviour to be not so annoying, I'm labeling this as `wontfix` and closing the ticket. I'm happy to reconsider if someone has solid arguments in favor of not creating extra source folders configured in the stock build tool.
