### ISSUE TITLE
REPL appears not to start

### ISSUE THREAD

**Issue by propensive** [scalacenter/bloop#385]
A command invocation such as `bloop console kaleidoscope/core` appears to work right up until it starts the REPL. The last lines I see are (including a blank one),
```
Starting scala interpreter...

```
The invocation does not appear to terminate, and the cursor is left "hanging".

There is no output at all on the server until I hit `Ctrl+C`, then:
```
Client in <path> has disconnected with a 'SocketError' event. Cancelling tasks...
```

This is the beaviour for the first five invocations of `bloop console`. On the sixth attempt, no output is shown on the frontend at all.

Bloop-frontend: 1.0.0-M7
Zinc: 1.1.0+9-57ca9e0f
Scala: 2.12.4

**Comment by propensive** [comment]
Update: running `bloop console` on a freshly-started bloop server, it gets a bit further: It reports the intro message from the REPL (`Welcome to Scala 2.12.4...`), and sends an ANSI code to turn my text pink, but it doesn't work interactively. This appears to only be the case if it's the first thing bloop does.

I wonder if the JLine interactivity in the REPL is failing due to some sort of buffering going on. I have vague memories of having to send some sort of `stty -icanon` command in my terminal on some project I worked on in the past, though I can't remember the details. But it's something to Google for, maybe.

**Comment by propensive** [comment]
Still not working with M8, including the behavior described in my "update" comment.

**Comment by propensive** [comment]
Thanks for the detailed analysis, @tues! Hopefully gets us a step closer to a fix. :)

**Comment by tues** [comment]
I've tested this with the newest `master` and it seems that the first issue has been fixed:
> The REPL starts correctly only if it's the first command after starting bloop server

The other two issues are still present:
```
[C    7] console
[H    0]
[1   29] Starting scala interpreter...
[1    1]

[1    1]

[1  118] Welcome to Scala 2.12.6 (OpenJDK 64-Bit Server VM, Java 1.8.0_162).
Type in expressions for evaluation. Or try :help.

[1   17]
scala>
[H    0]
```
I was typing `:help\n` but nailgun client didn't even send it to the server.

I've been experimenting with `Tasks.console` a bit:
```
    val foo = scala.io.StdIn.readLine()
    scala.io.StdIn
    println(s"foo: $foo")

    state.logger.warn(s"*** stdin: ${System.in}")
    state.logger.warn(s"*** stdout: ${System.out}")

    compiler.console(classpathFiles, project.scalacOptions, classpathOptions, "", "", state.logger)(
      Some(loader))
```

and `readLine` seems to be working perfectly fine:

```
[1    4] foo?
[1    1]

[S    0]
[H    0]
[0    4] bar

[1    8] foo: bar
[1    1]

[1   87] [W] *** stdin: com.martiansoftware.nailgun.ThreadLocalInputStream@12256b78
[1    1]

[1   88] [W] *** stdout: com.martiansoftware.nailgun.ThreadLocalPrintStream@6b7a0a22
[1    1]

[1   29] Starting scala interpreter...
[1    1]
```

so it seems that `sbt.internal.inc.AnalyzingCompiler` doesn't inherit correct stdin for some reason.

It's worth noting that stdin is working for the `run` command which is using the new `Forker` class (#449). I'm still learning Bloop's codebase, but my wild guess is that maybe we should implement a `ConsoleServer` similar to the `TestServer` being used currently and start forking new processes for the REPL?

**Comment by tues** [comment]
Turned out to be much easier to fix. I was fooled by `xsbt.ConsoleInterface` overriding `ILoop.createInterpreter` and forcefully setting its own input reader, but somehow passing `-Xnojline` (which should affect only `ILoop`'s `preLoop` reader) worked.

```
[C    7] console
[H    0]
[1   29] Starting scala interpreter...
[1    1]

[1    1]

[1  118] Welcome to Scala 2.12.6 (OpenJDK 64-Bit Server VM, Java 1.8.0_162).
Type in expressions for evaluation. Or try :help.

[1   17]
scala>
[S    0]
[0   13] val foo = 13

[1   39] foo: Int = 13
[1    1]

[1   17]
scala>
[S    0]
[0    6] :quit

[X    1] 0
[X    1]

[X    1] 0
[X    1]
```

**Comment by folex** [comment]
> The REPL starts correctly only if it's the first command after starting bloop server

I'm experiencing this on M11, is that expected?
```
    Bloop-frontend version    `1.0.0-M11`
    Zinc version     `1.1.7+62-0f4ad9d5`
    Scala version    `2.12.6`
```

**Comment by tues** [comment]
Hi @folex :slightly_smiling_face: No, it's not expected, it's a bug: please see #497. Unfortunately I haven't managed to find the cause yet :slightly_frowning_face:
