### ISSUE TITLE
The --args parameter only passes a single argument

### ISSUE THREAD

**Issue by propensive** [scalacenter/bloop#392]
A command such as,
```
> bloop run myapp --args foo bar
```
will take `foo` as the single argument to the `--args` parameter, and will interpret `bar` as a second project name (which is invalid).

I would suggest going with the convention of replacing `--args` with just `--`, and requiring that it be the final item on the `bloop` parameter list, with all subsequent arguments being passed to the application's `main` method.

**Comment by jvican** [comment]
This is supported, I think. Can you try? In any case, if you want to pass in several args parameters you can do `--args foo --args bar`. That's how case-app works.

**Comment by jvican** [comment]
Indeed, this was already fixed in https://github.com/scalacenter/bloop/commit/b81241cd73c422ebe7c7987386efa3c22429e0f4.

**Comment by propensive** [comment]
Yes, that does work with `M7`, and the fix you linked is perfect, thank you. :)
