### ISSUE TITLE
install.py Error while downloading https://repo1.maven.org/maven2/io/get-coursier/coursier-cli_2.11/1.0.1/coursier-cli_2.11-1.0.1-standalone.jar: repo1.maven.org, ignoring it

### ISSUE THREAD

**Issue by stasimus** [scalacenter/bloop#403]
I'm using proxy server

and my env variables are set to:

export SBT_OPTS="-Dhttp.proxyHost=myhost -Dhttp.proxyPort=myport"
export http_proxy=myproxy
export https_proxy=$http_proxy
export ftp_proxy=$http_proxy
export rsync_proxy=$http_proxy
export ANT_OPTS="-Dhttp.proxyHost=myhost -Dhttp.proxyPort=myport"
export JAVA_OPTS=$ANT_OPTS

**Comment by jvican** [comment]
It looks like this has to do with sbt, you need to report it upstream in sbt/sbt. Also, please, for the next time, if you report such a ticket make sure you specify which commands you ran. This is not a ticket anyone can act upon.
