### ISSUE TITLE
Coursier resolution error from the install.py python script under a proxy

### ISSUE THREAD

**Issue by stasimus** [scalacenter/bloop#405]
When I run 
  `python install.py` to install bloop on my Ubuntu environment

I'm getting the output error log:
`Error while downloading https://repo1.maven.org/maven2/io/get-coursier/coursier-cli_2.11/1.0.1/coursier-cli_2.11-1.0.1-standalone.jar: repo1.maven.org, ignoring it
Coursier couldn't create /home/stas/.bloop/blp-server. Please report an issue.`
`Command: ['java', '-jar', '/home/stas/.bloop/blp-coursier', 'bootstrap', 'ch.epfl.scala:bloop-frontend_2.12:1.0.0-M7', '-r', 'bintray:scalameta/maven', '-r', 'bintray:scalacenter/releases', '-o', '/home/stas/.bloop/blp-server', '-f', '--standalone', '--main', 'bloop.Server']
Return code: 255`

It's probably because of proxy settings are ignored by tool, I have those ENV variables set: 
`export SBT_OPTS="-Dhttp.proxyHost=myhost -Dhttp.proxyPort=myport"`
`export http_proxy=myproxy`
`export https_proxy=$http_proxy`
`export ftp_proxy=$http_proxy`
`export rsync_proxy=$http_proxy`
`export ANT_OPTS="-Dhttp.proxyHost=myhost -Dhttp.proxyPort=myport"`
`export JAVA_OPTS=$ANT_OPTS`

**Comment by jvican** [comment]
Now we're getting somewhere, thanks for reporting :smile:.
  
This error comes from coursier because you're behind a proxy. Could you run `java -jar /home/stas/.bloop/blp-coursier bootstrap ch.epfl.scala:bloop-frontend_2.12:1.0.0-M7 -r bintray:scalameta/maven -r bintray:scalacenter/releases -o /home/stas/.bloop/blp-server -f --standalone --main bloop.Server` in a terminal and report the error you get back from Coursier?
  
I'm not even sure myself that coursier supports this use case (it should, by all means). Its issue tracker doesn't seem to have any report either.

**Comment by stasimus** [comment]
`java -jar /home/stas/.bloop/blp-coursier bootstrap ch.epfl.scala:bloop-frontend_2.12:1.0.0-M7 -r bintray:scalameta/maven -r bintray:scalacenter/releases -o /home/stas/.bloop/blp-server -f --standalone --main bloop.Server`

produces

`Error while downloading https://repo1.maven.org/maven2/io/get-coursier/coursier-cli_2.11/1.0.1/coursier-cli_2.11-1.0.1-standalone.jar: repo1.maven.org, ignoring it`

I have to trick install.py as well - be able to use system set proxy, if needed I can contribute the changes - but I think it should come with fix for current issues.

**Comment by jvican** [comment]
> I have to trick install.py as well - be able to use system set proxy, if needed I can contribute the changes - but I think it should come with fix for current issues.

Yes, please, if you got it go to send a PR :+1:

**Comment by jvican** [comment]
@stasimus How is that PR coming along? Would love to support proxies in our installation script :smile:.

**Comment by jvican** [comment]
Superseeded by https://github.com/scalacenter/bloop/pull/699
