### ISSUE TITLE
Bloop should indicate when --watch is waiting for source changes

### ISSUE THREAD

**Issue by olafurpg** [scalacenter/bloop#422]
I ran `bloop test --watch tests-test` in the metadoc repo and when the tests complete the last line that is printed out is

```
- .semanticdb.json
```
It would be nice if that line was followed with some message from bloop indicating that bloop is waiting for more source changes, something like

```
Waiting for source changes... (press ??? to interrupt)
```

**Comment by jvican** [comment]
Thanks for the ticket! @rberenguel you may wanna be interested in this ticket too, fix should be two lines of code :smile: ^^

**Comment by rberenguel** [comment]
@jvican :D I will, I'm still getting used to the development cycle for bloop

**Comment by rberenguel** [comment]
@olafurpg @jvican I can't reproduce this locally, I get `File watching 28 directories...` as last message when watching on tests or compile the same.

**Comment by rberenguel** [comment]
Oh, got it now, the message only appears on first run, does not get repeated on file modified
