### ISSUE TITLE
Add tests for autocompletion features

### ISSUE THREAD

**Issue by rberenguel** [scalacenter/bloop#426]
Currently there is no way of testing autocompletion functionality. Autocomplete helpers for [Zsh](https://github.com/scalacenter/bloop/blob/master/frontend/src/main/scala/bloop/cli/completion/ZshFormat.scala) and [Bash](https://github.com/scalacenter/bloop/blob/master/frontend/src/main/scala/bloop/cli/completion/BashFormat.scala), Autocomplete functionality is provided with the [Autocomplete command](https://github.com/scalacenter/bloop/blob/63cad2ddfe3e8a940b43a6838bb72dfee4c92f28/frontend/src/main/scala/bloop/cli/Commands.scala).

This autocomplete command can be invoked by invoking the autocomplete method https://github.com/scalacenter/bloop/blob/684942ec08bae5d4a1dc6f28202e1907f39882d6/frontend/src/main/scala/bloop/engine/Interpreter.scala#L215 or via command line with `bloop autocomplete --format SHELLTYPE --mode MODE --command COMMAND` Comparing the output with the expected result should get this covered

**Comment by jvican** [comment]
https://github.com/scalacenter/bloop/pull/749 linked to this ticket but it's not fixing it: this ticket is mostly about testing the autocompletion features we have, whereas the PR I've just merged adds support for discovered test classes. Just a FYI for a motivated contributor that wants to pick this up :smile:
