### ISSUE TITLE
Brew package depends on sphinx-doc

### ISSUE THREAD

**Issue by dragos** [scalacenter/bloop#446]
This seems like an oversight.

```
==> Installing bloop from scalacenter/bloop
==> Installing dependencies for scalacenter/bloop/bloop: sphinx-doc, openssl, sqlite, python
==> Installing scalacenter/bloop/bloop dependency: sphinx-doc
==> Downloading https://homebrew.bintray.com/bottles/sphinx-doc-1.7.2.high_sierra.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/97/97b1529514651b14f4744ac088d8ce50677e622f011c8f7
######################################################################## 100.0%
==> Pouring sphinx-doc-1.7.2.high_sierra.bottle.tar.gz
==> Caveats
```

**Comment by dragos** [comment]
..it also depends on Python 3, maybe it is a transitive dependency of sphinx? This seems like a huge dependency for bloop:

```
🍺  /usr/local/Cellar/python/3.6.5: 9,098 files, 154.7MB, built in 11 minutes 47 seconds
```

**Comment by jvican** [comment]
Thanks for reporting Iulian!

```
==> Installing dependencies for scalacenter/bloop/bloop: sphinx-doc, openssl, sqlite, python
```
  
@Duhemm do you have any idea what's happening here? [Our only dependencies are java and python](https://github.com/scalacenter/homebrew-bloop/blob/master/bloop.rb#L9-L10), so it seems sphinx is a transitive dependency of bloop?
  
We currently support both python2 and python3. I think the dependency download depends on what "python" means in every OSX system (which Python Development Kit is the default).

**Comment by jvican** [comment]
Thanks for reporting Iulian!

```
==> Installing dependencies for scalacenter/bloop/bloop: sphinx-doc, openssl, sqlite, python
```
  
@Duhemm do you have any idea what's happening here? [Our only dependencies are java and python](https://github.com/scalacenter/homebrew-bloop/blob/master/bloop.rb#L9-L10), so it seems sphinx is a transitive dependency of bloop?
  
We currently support both python2 and python3. I think the dependency download depends on what "python" means in every OSX system (which Python Development Kit is the default).

**Comment by jvican** [comment]
ping @Duhemm wanna close this soon.

**Comment by valencik** [comment]
`sphinx-doc` appears to be a ["build" dependency on Homebrew's python formula](https://github.com/Homebrew/homebrew-core/blob/01bb91d7d99636cccb610088604cc6d44b1c2f38/Formula/python.rb#L23).

Although, I think this should only affect people building the python formula, as they have bottles for the major macOS versions.

**Comment by jvican** [comment]
@valencik :+1: It seems we cannot get rid of the dependency because the installation scripts are all written in Python. I'm closing, if you guys have any idea of we can sidestep the use of sphinx, let me know, I'll be happy to listen to potential solutions.

**Comment by dragos** [comment]
Couldn't you use Python 2.x, which is already available on most systems, instead of Python 3 which comes with 10k files?

**Comment by jvican** [comment]
> Couldn't you use Python 2.x, which is already available on most systems, instead of Python 3 which comes with 10k files?
  
Our scripts are compatible with both, I think it's a matter of what alias python redirects to in your system. I'm not an OSX user, so I cannot provide more insights. But in Linux world, `python` is aliased to either python2 or python3 depending on how you configured it (or what the default is).
  
@dragos Maybe you have python be python3 and can change to default to python2? I don't see what else we can do in our formula, we're as generic as possible.
