### ISSUE TITLE
Detected shadowing in Zinc forces recompilation

### ISSUE THREAD

**Issue by dragos** [scalacenter/bloop#447]
```
$ bloop clean hydra
$ bloop compile hydra
Compiling 4 Java sources to /Users/dragos/workspace/triplequote/hydra/.bloop/license-checking/classes ...
Done compiling.
Compiling 24 Scala sources to /Users/dragos/workspace/triplequote/hydra/.bloop/hydra/scala-2.12/classes ...
Done compiling.
$ bloop compile hydra
Compiling 7 Scala sources to /Users/dragos/workspace/triplequote/hydra/.bloop/hydra/scala-2.12/classes ...
Done compiling.
dragos@aquarius $ bloop compile hydra
dragos@aquarius $
```

These are my test sources. Notice that if I compile `hydra-test`, it compiles those 7 files *in the same output directory* as for hydra:

```
$ bloop compile hydra
Compiling 4 Java sources to /Users/dragos/workspace/triplequote/hydra/.bloop/license-checking/classes ...
Done compiling.
Compiling 24 Scala sources to /Users/dragos/workspace/triplequote/hydra/.bloop/hydra/scala-2.12/classes ...
Done compiling.
dragos@aquarius $ bloop compile hydra-test 
Compiling 7 Scala sources to /Users/dragos/workspace/triplequote/hydra/.bloop/hydra/scala-2.12/classes ...
Done compiling.
dragos@aquarius hydra $ bloop compile hydra
dragos@aquarius hydra $ 
```

**Comment by Duhemm** [comment]
Hi @dragos,

Thanks for the report! Looking at the log, it looks to me as if Bloop was not finding any sources in `hydra-test`, only in `hydra`.

It's extremely strange that running `bloop compile hydra` or `bloop compile hydra-test` again recompiles when there have been no changes. Is it always reproducible with `bloop clean hydra; bloop compile hydra; bloop compile hydra --verbose`? Could you share the output of the last command?

The second surprising thing is that no sources are found for `hydra-test`. `bloop compile hydra-test` should be the equivalent of `sbt hydra/test:compile`. Could you open `/Users/dragos/workspace/triplequote/hydra/.bloop/hydra-test.conf` and look at `project.sources`? Does it match your expectation of where to find the sources of your tests? Does it correspond to `sbt hydra/test:sourceDirectories`?

**Comment by dragos** [comment]
Here's the relevant part of `hydra-test.json`:

```
{
    "version" : "1.0.0",
    "project" : {
        "name" : "hydra-test",
        "directory" : "/Users/dragos/workspace/triplequote/hydra/hydra",
        "sources" : [
            "/Users/dragos/workspace/triplequote/hydra/hydra/src/test/scala-2.12",
            "/Users/dragos/workspace/triplequote/hydra/hydra/src/test/scala",
            "/Users/dragos/workspace/triplequote/hydra/hydra/src/test/java",
            "/Users/dragos/workspace/triplequote/hydra/hydra/target/scala-2.12/src_managed/test"
        ],
...
```

I see the problem, it was just a coincidence in the number of files. The root problem seems to be:

```
[D] Invalidating /Users/dragos/workspace/triplequote/hydra/hydra/src/main/scala-2.12/com/triplequote/hydra/compiler/HydraGlobal.scala: shadowing is detected for class com.triplequote.hydra.compiler.HydraGlobal
```
and a few more like that. What is shadowing? I have some files in `src/main/scala-2.12` and `.../scala-2.11` with the same types, but only one source directory is ever part of a compilation.

**Comment by jvican** [comment]
Yes, this is the issue I've noticed in our codebase as well. I'll have a look at it tomorrow and try to fix it. Thanks for the logs and the reproduction @dragos.

**Comment by jvican** [comment]
@dragos Should be fixed with the linked commit. Our sbt integration was using the same out dir for both compile and test class files :wink:.
