### ISSUE TITLE
Bloop will compile multiple times the same bridge concurrently

### ISSUE THREAD

**Issue by Duhemm** [scalacenter/bloop#45]
For instance when compiling sbt/sbt, there are multiple leave projects that will be built concurrently. If Bloop needs a new compiler bridge, it'll compile multiple times the same bridge concurrently.

**Comment by jvican** [comment]
In essence, what we want to do here is to have all bloop instances coordinate to compile and reuse the compiler bridge if it's missing. I think this is a great good first issue where we could get help from contributors :smile:.

**Comment by jvican** [comment]
This is not a major issue for now -- just a nice to have. Removing from the milestone and leaving it for the future.

**Comment by jvican** [comment]
I'm removing this from the issue tracker. This is not an issue we'll devote time to fix soon, and it's very difficult that will bite someone in the future.
