### ISSUE TITLE
Position of diagnostics in BSP are off

### ISSUE THREAD

**Issue by jastice** [scalacenter/bloop#450]
compiling something in bloop via bsp, compile error diagnostics are reported with
line == character and start == end

bloop version: 1.0.0-M9+84-c59d6fcc

<img width="486" alt="image" src="https://user-images.githubusercontent.com/770879/39060436-ffb801d0-44c9-11e8-8fa4-12ef0fbdd5fa.png">

**Comment by jvican** [comment]
The positions are the same because `-Yrangepos` is not enabled. The positions are the same because the convention is to make them equal range positions are disabled. Thanks for reporting!
