### ISSUE TITLE
Adding bloop breaks scalafmt

### ISSUE THREAD

**Issue by ArulselvanMadhavan** [scalacenter/bloop#453]
Hello,
Thanks for creating bloop. I love it. I tried adding bloop to our workflow at work. We also use scalafmt. After adding bloop, whenever I try running `scalafmt` I get this error.

Bloop Version:
```scala
addSbtPlugin("ch.epfl.scala" % "sbt-bloop" % "1.0.0-M9")
```
scalafmt Version:
```scala
addSbtPlugin("com.geirsson" % "sbt-scalafmt" % "1.4.0")
```

```bash
[error] Caused by: java.lang.ClassNotFoundException: scala.meta.inputs.Input
[error] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[error] 	at org.scalafmt.sbt.ScalafmtPlugin$.$anonfun$scalaConfig$2(Sca
```

FWIW, we don't use source dependencies.

**Comment by olafurpg** [comment]
Thanks for reporting! Upgrading bloop's dependency to metaconfig:0.7.0 (released yesterday after https://github.com/olafurpg/metaconfig/pull/42) should fix this binary incompatibility :)

**Comment by jvican** [comment]
@ArulselvanMadhavan You should be able to use the new bloop in a bit. It's on its way to Bintray, so you'll be able to depend on it as soon as the https://ci.scala-lang.org/scalacenter/bloop/2891/9 job is done. The publish step will tell you what the version number is.
