### ISSUE TITLE
Use fixed version of Coursier and make it configurable

### ISSUE THREAD

**Issue by tues** [scalacenter/bloop#472]
Currently Bloop is using https://git.io/vgvpD as the link for downloading Coursier in the `install.py` script, which is a link to the `master` branch of Coursier:
https://github.com/alexarchambault/coursier/raw/master/coursier
This makes it possible for the installation to break if Coursier changes in an incompatible way, as in #463.

I think that ideally `install.py` should download the same version of Coursier as the one defined in `Dependencies.coursierVersion`:
https://github.com/scalacenter/bloop/blob/20e42dfc807d55ea5e11dba01161535b02c356fc/project/Dependencies.scala#L7
This could be done automatically during release or manually whenever someone changes `coursierVersion` (in which case it would be nice to include a comment mentioning this in `Dependencies.scala`).

Moreover, it should be possible to override default version by passing `--coursier` option to `install.py` (just like it's being done for `nailgun`).

It's also worth considering whether the following `if` is really needed:
https://github.com/scalacenter/bloop/blob/20e42dfc807d55ea5e11dba01161535b02c356fc/bin/install.py#L147
Now the only way to update Bloop in case the newer version requires an incompatible version of Coursier is to `rm ~/.bloop/blp-coursier` first.

**Comment by jvican** [comment]
Fixed in #473.
