### ISSUE TITLE
Separate configuration files from compiled sources

### ISSUE THREAD

**Issue by tindzk** [scalacenter/bloop#476]
Although it is possible to change the path of the `.bloop` directory, it would be desirable to specify a different path for the compiled sources. For example, using `/dev/shm/bloop-$project/` should yield speed gains similar to [sbt-tmpfs](https://github.com/cuzfrog/sbt-tmpfs).

**Comment by jvican** [comment]
I don't know how https://github.com/cuzfrog/sbt-tmpfs works, but you can control where the classes directories are written via the `classesDir` field in our bloop configuration file: https://scalacenter.github.io/bloop/docs/configuration-format/. There are two options to remount it to `tmpfs`:
  
1. You have an script that rewrites the prefix of `classesDir`.
2. You modify your `classesDir` in sbt directly, so that sbt-bloop writes the right path in the file.

**Comment by jvican** [comment]
@tindzk Can you elaborate on the kind of solution you'd like to see here for this ticket to be closed?

**Comment by jvican** [comment]
Where is target pointing to? The bloop configuration directory created in the project under `.bloop`? If that's the case, you can already do that via `--config-dir` and you can also change the place where the bloop configuration directory is written in the sbt-bloop plugin via https://github.com/scalacenter/bloop/blob/master/integrations/sbt-bloop/src/main/scala/bloop/integrations/sbt/SbtBloop.scala#L88. If you want to change only the place where classes dir points to, you can do so via the trick explain in the FAQ https://scalacenter.github.io/bloop/faq/

**Comment by tindzk** [comment]
No, `--target` from my example above would only store the compiled classes in the RAM (`/dev/shm`). I would like to keep it separate from `.bloop` such that the JSON configuration files are retained when I restart the system. Thanks for hint on `bloopTargetDir`. That should cover my use case.

**Comment by arbitrary-dev** [comment]
For those who struggle...
```
bloop-configure-tmpfs() {
  [ ! -d .bloop ] && echo "No .bloop directory found!" && return 1
  sed -i "/classesDir/ s=`pwd`/.bloop=/tmp/bloop-`basename $(pwd)`=" .bloop/*.json
}
```

**Comment by arbitrary-dev** [comment]
But unfortunately it results in:
```
ERROR Failed to compile 'project-1', 'project-1' and 118 more projects
```

**Comment by arbitrary-dev** [comment]
I tried adding this to project's modules settings:
```
bloopClassDirectory := file(s"/tmp/bloop-project/${ normalizedName.value }"),
```

But `.bloop/*.json` configs are still being created with default path for `classesDir`.

Can someone help me out?

**Comment by jvican** [comment]
This feature is not supported @arbitrary-dev

**Comment by arbitrary-dev** [comment]
Created feature request :-)
https://github.com/scalacenter/bloop/issues/1031
