### ISSUE TITLE
Parallel REPL sessions not working as expected

### ISSUE THREAD

**Issue by tues** [scalacenter/bloop#491]
If you run multiple REPL sessions (`bloop console`) in parallel, they seem to be executed in turns. E.g. running:

```
$ bloop console root
```

in shell A, then:

```
$ bloop console root
```

in shell B, and then:

```
[shell A]
scala> val x = 13
x: Int = 13
```

the `scala>` prompt isn't displayed until you do:

```
[shell B]
scala> val y = 14
y: Int = 14
```

and now `scala>` isn't displayed in shell B until something is typed in shell A.

I'm not sure yet if it's Nailgun's fault or if it's caused by the implementation of the console task itself. I'm leaning towards Nailgun because one line is printed right away, only the prompt (which isn't a full line terminated with `\n`) is delayed.

**Comment by tues** [comment]
Actually no, if you try running some side-effecting code like writing to files it won't be executed until you press `Enter` a few times in the other shell, so I'm not sure if it's Nailgun. I'll try sniffing network traffic between the Nailgun client and the server to see what's going on tomorrow.

**Comment by jvican** [comment]
@tues I have the impression this is an implementation limitation from the REPL (which probably uses some kind of global state). I wonder if Ammonite also has this problem.

**Comment by tues** [comment]
I haven't checked Ammonite yet, but I have looked at the data Nailgun sends:

```
[C:46008 | A |    4] root
[C:46008 | C |    7] console
[S:46008 | 1 |   29] Starting scala interpreter...
[S:46008 | 1 |    1]

[S:46008 | 1 |    1]

[S:46008 | 1 |  118] Welcome to Scala 2.12.6 (OpenJDK 64-Bit Server VM, Java 1.8.0_171).
Type in expressions for evaluation. Or try :help.

[S:46008 | 1 |   17]
scala>
[S:46008 | S |    0]
[C:46010 | A |    4] root
[C:46010 | C |    7] console
[S:46010 | 1 |   29] Starting scala interpreter...
[S:46010 | 1 |    1]

[S:46010 | 1 |    1]

[S:46010 | 1 |  118] Welcome to Scala 2.12.6 (OpenJDK 64-Bit Server VM, Java 1.8.0_171).
Type in expressions for evaluation. Or try :help.

[S:46010 | 1 |   17]
scala>
[C:46008 | 0 |   11] val x = 13

[S:46010 | S |    0]
[S:46008 | 1 |   37] x: Int = 13
[S:46008 | 1 |    1]

[S:46008 | 1 |   17]
scala>
[C:46010 | 0 |   11] val y = 14

[S:46008 | S |    0]
[S:46010 | 1 |   37] y: Int = 14
[S:46010 | 1 |    1]

[S:46010 | 1 |   17]
scala>
[C:46008 | 0 |   13] val x2 = 131

[S:46010 | S |    0]
[C:46010 | 0 |   13] val y2 = 141

[S:46008 | 1 |   39] x2: Int = 131
[S:46008 | 1 |    1]

[S:46008 | 1 |   17]
scala>
[S:46008 | S |    0]
[S:46010 | 1 |   39] y2: Int = 141
[S:46010 | 1 |    1]

[S:46010 | 1 |   17]
scala>
[C:46008 | 0 |   13] val x3 = 132

[S:46010 | S |    0]
[S:46008 | 1 |   39] x3: Int = 132
[S:46008 | 1 |    1]

[S:46008 | 1 |   17]
scala>
[C:46010 | 0 |    3] :q

[S:46008 | S |    0]
[S:46010 | X |    1] 0
[S:46010 | X |    1]

[C:46008 | 0 |    3] :q

[S:46008 | X |    1] 0
[S:46008 | X |    1]
```

`46008` and `46010` are port numbers of the two REPLs.

It seems that the `S` ("start reading input") chunk is sent to one console only after some input is typed in the other one (which already got `S` chunk before). That is, only one console has `stdin` working at any time, which means that it's either an issue with Nailgun/our way of redirecting `stdin`, or indeed, as @jvican pointed out, global state used by the REPL itself, so that it never calls `system.in.nextLine` (or whatever) before the previous one returns.

BTW, I wrote a simple Python script using Scapy to decode `pcap`s containing Nailgun traffic: https://gist.github.com/tues/20ba6c72068a7a1b2f4250a975927e7d

**Comment by tues** [comment]
Ammonite uses separate processes for each REPL so obviously it's not affected.

**Comment by tues** [comment]
I added:

```
    println("foo1:")
    val foo1 = io.StdIn.readLine()
    println(s"got $foo1; foo2:")
    val foo2 = io.StdIn.readLine()
    println(s"got $foo2; foo3:")
    val foo3 = io.StdIn.readLine()
    println(s"got $foo3.")
```

before the creation of `ILoop` in Zinc's `CompilerInterface` and it's showing the same behaviour, so I guess it's not ILoop's global state.

Nailgun seems to be using `InheritableThreadLocal` variables for its `InputStream`s, so I'm wondering if it's because the same `InputStream` gets inherited by both `console` tasks...

**Comment by jvican** [comment]
I would be surprised if the input stream is used for different processes because it's supposed to change on a per client basis. Whenever we get the cached state, we redefine common options:

```scala
    cached.map(_.copy(pool = pool, commonOptions = opts, logger = logger))
```

**Comment by tues** [comment]
Yes, Nailgun does override that `InheritableThreadLocal` variable for each client. However, Scala itself uses an `InheritableThreadLocal` variable to hold in/out/err stream instances in the form of `Console.in`, `Console.out` and `Console.err`. I have tried replacing `io.StdIn` with `System.in` in my last code snippet and it started working correctly indeed.

As it turns out, somewhere between Zinc's `AnalyzingCompiler.console` and `ConsoleInterface.run` `Console.in` is set to a `BufferedReader` shared between all REPLs. My guess is that this is caused by a different class loader used for running `ConsoleInterface.run` so the `Console.in` we set in Bloop is lost. Thus, I'm not sure if this can be fixed without modifying Zinc.

I have tried a somewhat hacky solution of wrapping `ILoop`'s creation (`ConsoleInterface.run`) in `Console.withIn(new InputStreamReader(System.in))` and it's working fine.

**Comment by jvican** [comment]
Great debugging skills!

> I have tried a somewhat hacky solution of wrapping ILoop's creation (ConsoleInterface.run) in Console.withIn(new InputStreamReader(System.in)) and it's working fine.
  
As you note, this is probably something that should be fixed in Zinc somehow, but as we have this workaround I suggest we use it and move to the next challenge! What's happening here is that the console initialization sees the old input streams somehow, instead of the ones we set in the session.

**Comment by jvican** [comment]
@tues That kind of change merits a pull request in sbt/zinc, it seems general-purpose enough that it will not conflict with the current behaviour. We'll merge it then and propagate it to use it in Bloop. Would you mind doing so when you've got some free time?

**Comment by jvican** [comment]
Scala REPL sessions won't be supported in 2.0 anymore, so I'm closing because I intend to deprecate this integration in favor of Ammonite's integration.
