### ISSUE TITLE
Could not find goal 'bloopInstall'

### ISSUE THREAD

**Issue by lefou** [scalacenter/bloop#492]
When running the following maven command:

```
mvn ch.epfl.scala:maven-bloop_2.12:1.0.0-M10:bloopInstall 
```

 I get an error:

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.125 s
[INFO] Finished at: 2018-05-18T09:21:41+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Could not find goal 'bloopInstall' in plugin ch.epfl.scala:maven-bloop_2.12:1.0.0-M10 among available goals bloop -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoNotFoundException
```

As the goal name was changed from `bloop`to `bloopInstall` quite a while before the release, I suspect that the released version does not correspond to the git tag 1.0.0-M10.

**Comment by jvican** [comment]
And that is a good suspicion. You're right! We just merged the PR that adds support for Maven. Could you remove the version number to make it work? It will fetch the latest merged release in our repo.

**Comment by jvican** [comment]
I'll close this ticket as soon as Maven support is in a stable release. We're planning to release another one next week.

**Comment by lefou** [comment]
After locally building and installing version `1.0.0-M10+21-76187ec5` from current master, the goal is properly called `bloopInstall`.
