### ISSUE TITLE
Test failure returns always success exit code

### ISSUE THREAD

**Issue by tindzk** [scalacenter/bloop#496]
The exit code is always 0 regardless of whether the tests failed or succeeded. Unfortunately, this makes it difficult to use `bloop test` in CI jobs.

**Comment by jvican** [comment]
Thanks for the bug report, I'm happy to accept a PR to fix this! By the way Tim, I'll try to have a look at your open PR soon, I've been quite busy these last days at Scaladays.

**Comment by tindzk** [comment]
No problem. I submitted a pull request to implement the required functionality.

**Comment by tindzk** [comment]
Implemented in #499.
