### ISSUE TITLE
Sometimes REPL exits immediately

### ISSUE THREAD

**Issue by tues** [scalacenter/bloop#497]
This was actually reported as part of #385:

> The REPL starts correctly only if it's the first command after starting bloop server

Back then I thought it had been magically fixed by some other changes, but it seems that it just depends on the project for which `bloop console` is run. For small projects it always works fine, for big projects it works only once, while for medium-size projects it works a few times, then the server needs to be restarted.

Apparently `ILoop.createInterpreter` is called, but then the `ILoop` immediately closes (`ILoop.closeInterpreter` is called). I don't know what happens in between yet.

**Comment by propensive** [comment]
I'm continuing to see the behavior I reported in #385, however it's working better now. I can actually use the REPL iff it's the first thing I do after starting `bloop`.

The jline interactivity appears to be nonexistent, though. Unfortunately, I'm so familiar with this that it's barely usable without it these days...

Ping me if you'd like to chat about this some time. I've been using NuProcess since @jvican told me about it, and have had some problems of my own which might be related. I would be interested in comparing notes.

**Comment by tues** [comment]
Yes, AFAIK the REPL isn't intended to be used directly without `jline`. This mode is rather for integration with other tools which take advantage of the `:completions` command, like `emacs-sbt-mode`.

Unfortunately because of Nailgun's limitations we can't use `jline`. We would have to enhance Nailgun significantly or switch to something else.

Alternatively, we could probably modify Nailgun's client to make it use `readline` and support `:completions`, although that would make it very Bloop-specific. OTOH it already has default port set to `8121` which is Bloop-specific so I guess there's nothing wrong with that.

And the least invasive solution is to create a wrapper around `bloop console` which would use `readline` itself. Not ideal, but should be easy to do and maybe an acceptable workaround until we implement proper `jline` support in Nailgun?

> Ping me if you'd like to chat about this some time. I've been using NuProcess since @jvican told me about it, and have had some problems of my own which might be related. I would be interested in comparing notes.

Sure, that would be great! I'd like to try debugging this myself first though just to have anything to compare your notes with :wink: Unfortunately I'm doing this in my spare time and working on a few other tickets as well so the progress is slow - sorry :disappointed:

**Comment by jvican** [comment]
> Alternatively, we could probably modify Nailgun's client to make it use readline and support :completions, although that would make it very Bloop-specific. OTOH it already has default port set to 8121 which is Bloop-specific so I guess there's nothing wrong with that.
  
If we can do this without modifying the semantics that the nailgun reader has, I would be happy to merge it. We've added so many bloop-specific changes to the python script that I think it's already fair to call it Bloopgun :smile:

**Comment by tpolecat** [comment]
Is there any known workaround here? This seems like a critical bug to me.

**Comment by jvican** [comment]
@tpolecat To keep you in the loop, the plan is to deprecate the Scala REPL integration and instead favor our Ammonite integration, which we partially support now by default via `bloop console $PROJECT`. The Ammonite integration needs to be improved (for example, we'll be adding support for Ammonite to offload compilation of code snippets to Bloop) but for now it's good enough that the deprecation of the Scala REPL will become a deletion in Bloop 2.0.
