### ISSUE TITLE
Can bloop be installed with JDK7?

### ISSUE THREAD

**Issue by abigailbunyan** [scalacenter/bloop#498]
Our multilingual project is still stuck on JDK7 due to legacy clients, which means we can't use Bloop. (Currently we use [`typesafehub/zinc`](https://github.com/typesafehub/zinc).) Would it be possible to release against Scala 2.11 as well as 2.12?

**Comment by jvican** [comment]
I'm sorry, it isn't possible. Zinc 1 (the incremental compiler, a binary dep for bloop) assumes JDK8. Isn't there a chance you use JDK8 for devops and then test everything with JDK7? That should work.
