### ISSUE TITLE
Don't make --verbose position dependent in the CLI

### ISSUE THREAD

**Issue by tindzk** [scalacenter/bloop#501]
Specifying `--verbose` after the command behaves as expected: `bloop test module --verbose`.

However, many CLI programs allow to specify `--verbose` at any position. The following does not work with Bloop:

```
$ bloop --verbose test module
Usage: bloop [options] cmd arg1 arg2 ...

bloop: error: no such option: --verbose
```

**Comment by jvican** [comment]
This is most likely due to the fact that parsing `--verbose` requires the caseapp parser for `CliOptions`, which is `@Recurse`d in the class definition. I'm not sure how to fix this issue, but sounds like something we could fix.

**Comment by jvican** [comment]
I'm closing this ticket since this should be reported upstream in alexarchambault/case-app :smile:.
