### ISSUE TITLE
Don't ignore additional source folders in mvn project

### ISSUE THREAD

**Issue by lefou** [scalacenter/bloop#506]
Additional Scala source folders (e.g. `shared/main/scala`), added with the build-helper plugin in the `initialize` phase, are ignored by `bloopInstall` goal. The generated json config files only reference the `src/main/scala` directory in the `sources` section.

When compiling with `net.alchim31.maven:scala-maven-plugin:3.3.2` those sources are properly compiled.

**Comment by mohithg** [comment]
I'm facing this issue too, in sbt though, can anyone help?

**Comment by jvican** [comment]
@mohithg The sbt plugin is unlikely to be missing additional source folders. If you're 100% sure that's the case, make sure you're setting them up correctly. This ticket is only for Maven projects, if you have any question drop by Gitter and some people there might be able to help you out find the issue

**Comment by jvican** [comment]
Been a long time this ticket has been opened and marked as "help wanted". If someone wants to take a stab at it, please let me know and I'll reopen it.
