### ISSUE TITLE
Maven integration: maven plugin fails when there are non-Scala projects

### ISSUE THREAD

**Issue by lefou** [scalacenter/bloop#507]
When running `maven-bloop:bloopInstall` from the cmdline I get an error like this:

```
$ mvn ch.epfl.scala:maven-bloop_2.12:1.0.0-M10+26-41fe0561:bloopInstall
...
[ERROR] Failed to execute goal ch.epfl.scala:maven-bloop_2.12:1.0.0-M10+26-41fe0561:bloopInstall (default-cli) on project example.projectA: Execution default-cli of goal ch.epfl.scala:maven-bloop_2.12:1.0.0-M10+26-41fe0561:bloopInstall failed: The plugin net.alchim31.maven:scala-maven-plugin could not be found. -> [Help 1]
```

After working around this issue by running the plugin by configuring it in the pom, it generates JSON config files, which have dependencies to these non-Scala projects:

```
$ bloop compile example.projectB
[E] key not found: example.projectA
```

**Comment by jvican** [comment]
The issue here is that our current Maven integration only works with `scala-maven-plugin` because it gets all the scala configuration from there by using some special tricks from Maven. I apologize for not clarifying that in the docs, I'll submit a PR to fix that.
  
There's nothing that can be done here unless you also add compatibility for whatever maven plugin you're using to do Scala.

**Comment by lefou** [comment]
There are two cases here:

Case 1, the simple one, also my case: some project isn't a scala project at all. bloop-maven should handle it gracefully by not failing and by not creating bloop dependencies on this project

Case 2, the advanced one, we don't need to support (right now). It's a scala project, but build with some other currently not supported maven plugin. I think, bloop-maven should just ignore it and handle it like case 1.

**Comment by lefou** [comment]
Unfortunately, PR #511 only fixes the Maven error, but not the inter-project dependencies of bloop. I created a simple Maven project to reproduce the issue. https://github.com/lefou/bloop-it-maven-non-scala

After thinking more about it, ignoring Java projects seems to be not the right move, as they still need to be compiled with bloop when other (scala) projects depend on it. But, we should not try to read any scala setting from Java projects (which has to fail) but only the Java configuration.
