### ISSUE TITLE
sbt-bloop does not create projects for all configs

### ISSUE THREAD

**Issue by MateuszKubuszok** [scalacenter/bloop#514]
In my project I use `Compile`, `Test` and `IntegrationTest`. sbt-bloop generates projects only for `Compile` and `Test` configs, so I cannot benefit from using Bloop when I compile integration tests.

I have bloop enabled globally and I globally set up `bloopAggregateSourceDependencies in Global := true`.

I see that [it is hardcoded](https://github.com/scalacenter/bloop/blob/f7d1bbb7d28529d3479fb246338ffca766c461f2/integrations/sbt-bloop/src/main/scala/bloop/integrations/sbt/SbtBloop.scala#L92), but is it a goal to make it discover other configs automatically?

**Comment by tues** [comment]
Hi @MateuszKubuszok, please take a look at #505 - basically it was fixed and merged today :slightly_smiling_face: We still need to update user documentation, but if you follow the instructions from #512 it should work :slightly_smiling_face:

**Comment by jvican** [comment]
@MateuszKubuszok As Pawel says, this was just fixed yesterday. To use it, use the latest release `1.0.0-M10+69-f7d1bbb7` and follow the instructions of the linked PR. Docs should be available in the website soon.

**Comment by MateuszKubuszok** [comment]
Awesome! Great thanks for your hard work!

**Comment by tues** [comment]
Also, if your `IntegrationTest` configuration depends on `Test` (or some other configuration different than `Compile`), there's an open bug about Bloop not generating the dependency in that case: #515. However, you can simply add `"<project>-test"` to `.bloop/<project>-it.json`'s `dependencies` manually as a temporary workaround.

**Comment by jvican** [comment]
Great to see this is fixed, closing!
