### ISSUE TITLE
Sbt plugin crash when scalafmt is loaded too

### ISSUE THREAD

**Issue by Tomahna** [scalacenter/bloop#518]
When I try to generate a bloop config with sbt bloopInstall on a project using sbt-scalafmt (ensime-server for example), it crashes with ```[error] java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: metaconfig/HasFields```

I assume it comes from incompatible versions of metaconfig-core.

**Comment by jvican** [comment]
Yes, this issue was already filed as https://github.com/scalacenter/bloop/issues/490. Updating to the linked version or 1.6.0-RC1 should fix it.

**Comment by timcharper** [comment]
Thanks, found this issue via a search for another project, and this worked.

**Comment by jvican** [comment]
@timcharper note that 1.0.0 is already out 😁
