### ISSUE TITLE
Detect java projects in the Maven plugin

### ISSUE THREAD

**Issue by lefou** [scalacenter/bloop#519]
Currently, bloops Maven plugin ignores non-scala projects, but it shouldn't.

See also this repo: https://github.com/lefou/bloop-it-maven-non-scala  for a minimal test case.

(This is a follow up to #507)

**Comment by mnd999** [comment]
This branch supports Java modules, and attempts to read the Javac args from there as well but the second part doesn't seem to work.

https://github.com/mnd999/bloop/tree/generate-maven-java-modules
