### ISSUE TITLE
Allow custom JVM options when running via Nailgun

### ISSUE THREAD

**Issue by tues** [scalacenter/bloop#531]
As mentioned in #530, there seems to be no way to pass additional JVM arguments when running `bloop server`.

Solving this will probably involve adding a new command line option to Nailgun clients, or at least respecting some commonly used environment variables like `JAVA_OPTS`.

This is how the Python client runs JVM currently:
https://github.com/scalacenter/nailgun/blob/60c2d1307d88cb798abf5022daaeaa7edb2110f8/pynailgun/ng.py#L921

~It would be nice to merge this upstream afterwards.~

Also, the docs for debugging Bloop could be updated with instructions on how to enable JDWP agent when running `bloop server`.

**Comment by jvican** [comment]
Nitpick: this cannot be merged upstream because the default nailgun python client doesn't have support for the `server` command, that's bloop specific.

**Comment by tues** [comment]
I've tried `JAVA_TOOL_OPTIONS` ([doc](https://docs.oracle.com/javase/8/docs/platform/jvmti/jvmti.html#tooloptions)) and it seems to work:

```
$ JAVA_TOOL_OPTIONS='-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5005' bloop server
Picked up JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5005
Listening for transport dt_socket at address: 5005
```

**Comment by jvican** [comment]
Yeah, that's another way to do it. It's great that `java` detects that automatically. I didn't know about `JAVA_TOOL_OPTIONS` though, thanks for the info :wink:. I'll submit PR modifying the nailgun script and adding this to the docs!

**Comment by tues** [comment]
Yes, those environment variables aren't documented very well... And I never remember whether it's `JVM_OPTS`, `JAVA_OPTS`, `JVM_OPTIONS`, `JAVA_OPTIONS`, `JAVA_TOOL_OPTS`, `JAVA_TOOL_OPTIONS`... :sweat_smile:
