### ISSUE TITLE
Write integration tests for mill

### ISSUE THREAD

**Issue by jvican** [scalacenter/bloop#534]
We should figure out how to test the recently contributed mill integration by @Baccata. I have no idea how mill is supposed to be tested... but ideally, we'd like something that we can run from the host sbt process via `millBloop/test`.

**Comment by Baccata** [comment]
Here's some pointers :  

* https://github.com/lihaoyi/mill/blob/master/main/test/src/mill/util/ScriptTestSuite.scala#L8 
* https://github.com/lihaoyi/mill/blob/b659cb97f58a3d7be641f94885c940375b1aa23f/main/test/src/mill/main/JavaCompileJarTests.scala

The gist of it is basically instantiating a runner using whichever directory where a test project is located, call a command using the runner(assert that it returns successfully), then check the expected output files.

**Comment by jvican** [comment]
Closing since we've moved the mill integration to mill-contrib
