### ISSUE TITLE
Include line next to file in Bloop reporter

### ISSUE THREAD

**Issue by gabro** [scalacenter/bloop#536]
This little diff would allow to jump to the error in the editor when running bloop into an integrated terminal in VSCode (and similar editors, I assume)

```diff
-[E] [E3] shared/src/main/scala/crowdfense/shared/CryptoUtils.scala
+[E] [E3] shared/src/main/scala/crowdfense/shared/CryptoUtils.scala:32
 [E]      object openssl is not a member of package org.bouncycastle
 [E]      L32: import org.bouncycastle.openssl.jcajce.JcaPEMKeyConverter
```

This is currently the only reason why I use the scalac reporter, but I'd like to switch to bloop's reporter (I like seeing the errors in reverse order).

@jvican is this a change that would be welcome? I can try submitting a PR if you're on board

**Comment by Duhemm** [comment]
@gabro That sounds like a great idea. I think that you’ll need to tweak https://github.com/scalacenter/bloop/blob/master/backend/src/main/scala/bloop/reporter/DefaultReporterFormat.scala to get that to work. 

Thanks in advance !

**Comment by jvican** [comment]
Echo that!

**Comment by gabro** [comment]
Cool, I'll get to it as soon as I have second :) Thanks for the prompt feedback
