### ISSUE TITLE
Fix non-working test summary 

### ISSUE THREAD

**Issue by jvican** [scalacenter/bloop#543]
The test summary for all the test suites doesn't work, even if test suites are run.
  
```scala
===============================================
Total duration: 0ms
No test suites were run.
===============================================
```
  
Code: https://github.com/scalacenter/bloop/blob/topic/bsp-1.0.0-M2/frontend/src/main/scala/bloop/testing/TestSuiteEvent.scala#L99-L122
  
If there's work in this area, it would be good if the printing of test summary is better, see https://github.com/scalacenter/bloop/issues/510.

**Comment by tindzk** [comment]
I noticed the same yesterday. It appears to be a regression as it worked before.
