### ISSUE TITLE
Add a way to define a default project

### ISSUE THREAD

**Issue by dzamlo** [scalacenter/bloop#553]
The sbt plugin generates at least two project. But, most of the time, I want to use the same project (the one  without the "-test-" suffix) when using bloop. 

It would be nice if instead of having to indicate the project on each bloop invocation, I could specify which one to use by default.

If this is implemented, I think it would also be a good idea for the sbt plugin to set the default project for the simple case where only two projects are generated and one of them is the test project.

**Comment by jvican** [comment]
Thanks for the suggestion! :smile: I think I don't really understand the motivation of this feature request, but I'm very wary of adding fields to the configuration file formats only to improve user ergonomics. If you want to improve the ease of invoking a command, you should probably be doing `alias`es in your shell to type less. Also note two things:
  
1. You have autocompletions, so whenever you autocomplete it will autocomplete by default to the shortest name (the one that is not test).
2. You can do `bloop test foo` as an alias for `bloop test foo-test` now.
  
I'm closing the ticket, but I'm still willing to reconsider if you motivate the change and convince me it's worth it :wink:

**Comment by dzamlo** [comment]
The issue with using `alias`es is that when you ofter switch projects, you need to either change you alias, use different alias, or implement an ad-hoc solution that detect the current projects.


> You can do bloop test foo as an alias for bloop test foo-test

 That one more reason to support having a default project, because that one more command when you want to use the same project name.

If a command has some obvious default for one of the parameter, I think it makes sense that you don't need to specify it for every invocation. For example, you use `ls` not `ls .`, or  `make` not `make all`, or `sbt compile` not `sbt project-name/compile`

But I agree that this is minor ergonomic issue and that this feature may not carry its weight.

**Comment by jvican** [comment]
We will soon have a workspace settings file where we could allow users to set the default project. `bloop compile` would then not fail, but instead use the default project set in the workspace settings file.
  
If you're interested in helping implement this approach, please contact me in Gitter so that I can give you more context and advice on how to tackle the implementation work.

**Comment by tgodzik** [comment]
I don't think there are any plans to work on this currently. For anyone wanting a good default behaviour you could try out scala-cli, which is now included as part of Scala 3.5.0 (and uses Bloop by default underneath)
