### ISSUE TITLE
Clear screen on startup during watch mode

### ISSUE THREAD

**Issue by japgolly** [scalacenter/bloop#562]
Currently Bloop clears the screen between runs during watch mode. It would be nice to also clear the screen before the first run during watch mode too. I believe most other tools behave this way too.

**Comment by Duhemm** [comment]
This sounds like a good idea, and shouldn't be too hard to do.

Thanks for the suggestion, PRs are welcome!

Relevant source positions:
https://github.com/scalacenter/bloop/blob/07bf16e7731457ca48e32df47e22e9e0b8b89f0a/frontend/src/main/scala/bloop/engine/Interpreter.scala#L107-L119
https://github.com/scalacenter/bloop/blob/07bf16e7731457ca48e32df47e22e9e0b8b89f0a/frontend/src/main/scala/bloop/io/SourceWatcher.scala#L18-L108

**Comment by tues** [comment]
Fixed by #639
