### ISSUE TITLE
Missing JRE from scalac invocation using sbt plugin

### ISSUE THREAD

**Issue by andrezimmermann** [scalacenter/bloop#564]
My project depends on the JRE classes (rt.jar) which compiles fines with sbt compile.

During a `bloop compile`, after running `sbt bloopInstall`, the compilation fails with the following error
```
[T] java.util.concurrent.ExecutionException: Boxed Error
[T]     scala.concurrent.impl.Promise$.resolver(Promise.scala:83)
[T]     scala.concurrent.impl.Promise$.scala$concurrent$impl$Promise$$resolveTry(Promise.scala:75)
[T]     scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:280)
[T]     scala.concurrent.Promise.tryFailure(Promise.scala:108)
[T]     scala.concurrent.Promise.tryFailure$(Promise.scala:108)
[T]     scala.concurrent.impl.Promise$DefaultPromise.tryFailure(Promise.scala:183)
[T]     monix.eval.internal.TaskRunLoop$$anon$1.onError(TaskRunLoop.scala:281)
[T]     monix.eval.internal.TaskRunLoop$.monix$eval$internal$TaskRunLoop$$loop$1(TaskRunLoop.scala:242)
[T]     monix.eval.internal.TaskRunLoop$.startWithCallback(TaskRunLoop.scala:260)
[T]     monix.eval.internal.TaskRunLoop$.$anonfun$restartAsync$1(TaskRunLoop.scala:59)
[T]     java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
[T]     java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[T]     java.base/java.lang.Thread.run(Thread.java:844)
[T] Caused by: java.lang.NoClassDefFoundError: java/sql/PreparedStatement
[T]     java.base/java.lang.Class.getDeclaredMethods0(Native Method)
[T]     java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3119)
[T]     java.base/java.lang.Class.privateGetPublicMethods(Class.java:3144)
[T]     java.base/java.lang.Class.getMethods(Class.java:1863)
```
Meaning the the jre jars are not included within the configuration json

I have only JDK 8
I exported to `JAVA_HOME` with
```
export JAVA_HOME="`/usr/libexec/java_home`"
```
and set in the build.sbt the key javaHome := sys.env.get("JAVA_HOME") map file
sbt show javaHome
```
[info] javaHome
[info]     Some(/Library/Java/JavaVirtualMachines/jdk1.8.0_151.jdk/Contents/Home)
```
The output of `sbt compile` with `--debug` correctly shows the jars in the bootclasspath

```
[debug]     -bootclasspath
[debug]     /Library/Java/JavaVirtualMachines/jdk1.8.0_151.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_151.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_151.jdk/Contents/Home/jre/lib/sunrsasign.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_151.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_151.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_151.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_151.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_151.jdk/Contents/Home/jre/classes:/Users/user/.sbt/boot/scala-2.12.6/lib/scala-library.jar
```
Also without setting the javaHome (and JAVA_HOME) my compilation works and correctly adds the jars to the -bootclasspath
```
[info] javaHome
[info]     None
```
```
[debug]     -bootclasspath
[debug]     /Library/Java/JavaVirtualMachines/jdk1.8.0_151.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_151.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_151.jdk/Contents/Home/jre/lib/sunrsasign.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_151.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_151.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_151.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_151.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_151.jdk/Contents/Home/jre/classes:/Users/user/.sbt/boot/scala-2.12.6/lib/scala-library.jar
```
My expectation is that bloopInstall would match the -bootclasspath generated by sbt and my compilation would finish successfully

**Comment by Duhemm** [comment]
I think there are several issues. First, we do not correctly pass the `JAVA_HOME` to the `Compilers` instance that we create with Zinc:

https://github.com/scalacenter/bloop/blob/07bf16e7731457ca48e32df47e22e9e0b8b89f0a/backend/src/main/scala/bloop/CompilerCache.scala#L23-L26

Second, we create the `bootclasspath` using the environment in which the Bloop server has been created, which is wrong, since that means that the scala compiler won't see the `JAVA_HOME` that you want to use for a given project.

Can you send us a small reproduction of your project?

**Comment by andrezimmermann** [comment]
Thanks for the quick reply.
I might take a while to create a MCVE (no free time) 

> Second, we create the bootclasspath using the environment in which the Bloop server has been created

If that is true,  any project with any dependency to JRE would fail. 
So having a `val arrayList = new java.util.ArrayList()` would reproduce the ClassNotFound Exception


https://github.com/scalacenter/bloop/blob/07bf16e7731457ca48e32df47e22e9e0b8b89f0a/integrations/sbt-bloop/src/main/scala/bloop/integrations/sbt/SbtBloop.scala#L696

Does this (`c.bootLibrary`) output the correct jars?

**Comment by andrezimmermann** [comment]
If I manually add the missing jars into the `scala.jars` I can compile my project.
The sbt compile --debug had two weird entries that weren't accepted by bloop
```
[0m[33m[W][0m Scala instance jar C:\Program Files\Java\jre1.8.0_171\lib\sunrsasign.jar doesn't exist!
[0m[33m[W][0m Scala instance jar C:\Program Files\Java\jre1.8.0_171\classes doesn't exist!
```
They indeed do not exist, I have no idea why sbt generated these entries and why it work as is with SBT.

**Comment by andrezimmermann** [comment]
I'm going to close this since I can't reproduce the error anymore
The -bootclasspath is being correctly generated
I think also setting the javaHome in sbt and expecting that the bloop server actually starts a new process with that jvm if not running already, is a bit problematic given the architecture of the bloop server. 
As a compromise, like maven, honoring the JAVA_HOME var would be good.

**Comment by jvican** [comment]
@andrezimmermann Just saw this. I think we honor `JAVA_HOME`, but it needs to be set in whichever environment you launch the bloop server (if you do it via systemctl, for example, you need to make sure that `JAVA_HOME` is available from there).
  
> I think also setting the javaHome in sbt and expecting that the bloop server actually starts a new process with that jvm if not running already, is a bit problematic given the architecture of the bloop server.
  
If you mean that you want the bloop server to run with this java home, then yeah, that's impossible. But if you mean that run or test processes will use `javaHome` and fork, then this is already the case (it's just that we cannot do the same for compile since the zinc compilers are in-process).

**Comment by jvican** [comment]
By the way, linking to https://stackoverflow.com/questions/7701692/setting-up-sbt-to-use-java-7-for-compilation. Even if we supported java home for compilation as sbt does, it wouldn't solve this problem. The most reliable way is to expose `JAVA_HOME` in the environment where you spawn bloop's server.

**Comment by andrezimmermann** [comment]
So the error itself was caused by JDK 10 that wasn't supported at the time.  Right now it's working fine. 
The current `JAVA_HOME` implementation is fine, I was just trying to work around my issue.

**Comment by jvican** [comment]
Happy to hear that :+1:
