### ISSUE TITLE
Improve the ergonomics of the Windows installation

### ISSUE THREAD

**Issue by andrezimmermann** [scalacenter/bloop#567]
The python script could add the bloop install folder in the `PATH` and having an simple `bloop.cmd` we can have the same experience as mac users with the home brew installation.

It's safe to assume that since you ran the python script you would already have the python in your `PATH`

Example of `bloop.cmd` that works for me.

```
@echo off
python %~dp0bloop %*
```
I would gladly open a PR if this is approved

**Comment by jvican** [comment]
I would definitely be happy to have a better Windows installation, so :+1: for this ticket.
  
A few questions:
  
1. Is it common to add the bloop install folder in the `PATH` automatically? This seems borderline for me, anything that auto-adds to PATH is scary in the Unix world and therefore to be avoided.
2. Is there a default way we can help Windows users manage the lifecycle of bloop through the Windows equivalent of systemctl?
3. How do other CLI tools deal with this? What's the most common way to install an application in Windows, in your experience?
  
Perhaps we should be bundling bloop in one of these three options:
1. [scoop](https://github.com/lukesampson/scoop)
2. [Chocolatey](https://chocolatey.org/)
3. [OneGet](https://github.com/OneGet/oneget), apparently bundled in Windows 10
  
If you think that there's no need for a more sophisticated solution, good, let's just create a bash script. My only worry is the handling of PATH.

**Comment by Katrix** [comment]
As I windows user, I really just want a simple way to install it without having to download anything else (Cygwin or similar which is the current requirement, or some package manager). Being able to specify the install location is also semi-important for me.

As for adding stuff to PATH, I wouldn't worry about it. On windows, I'd consider it weird if a command line tool didn't add itself to the PATH. Most others do. That also expand to other official scala tools like scalac and sbt.

**Comment by andrezimmermann** [comment]
As a windows user, I can affirm that is pretty common, most (if not all) register themselves into the PATH.
For managing the lifecycle, an creating a service is the way in windows, although I'm pretty happy with staring the bloop service myself when I start coding. There is a few ways to register a new service from python code. 

Seems AWS, Azure, and Goggle Clould, all of their cli installers for windows are packed in `.msi` installers. SBT is also packed into an `.msi` which is also adds itself to the PATH. Then you get an uninstaller to remove from path.

I'm not sure how difficult is to create the `.msi` installer but that seems the most common user experience for windows.

**Comment by jvican** [comment]
Let's create an `.msi` installer. Thank you guys for your insights, your opinion is valuable.
  
I'm adding this to the back-burner since I cannot work on this any time soon. If you're a Windows user and want this, please upvote this ticket and bother me in Gitter.

**Comment by jvican** [comment]
I would be grateful if a Windows user can look into this. I've had a look at the specifics of how we could implement this, and the answer is `sbt-native-packager`. Its [Windows plugin](https://www.scala-sbt.org/sbt-native-packager/formats/windows.html) allows us to specify in a succinct way what JARs or BATs should be installed in the system (and Wix will add them to the classpath automatically).
  
An example from the docs:
  
```
mappings in Windows ++= (packageBin in Compile, sourceDirectory in Windows) map { (jar, dir) =>
  Seq(jar -> "lib/cool.jar", (dir / "cool.bat") -> "bin/cool.bat")
}

wixFeatures += WindowsFeature(
    id="BinaryAndPath",
    title="My Project's Binaries and updated PATH settings",
    desc="Update PATH environment variables (requires restart).",
    components = Seq(
      ComponentFile("bin/cool.bat"),
      ComponentFile("lib/cool.jar"),
      AddDirectoryToPath("bin"))
)
```
 
In our case, we would need to create a BAT script that runs our `bin/install.py` script to install bloop. The script would take the inputs (directory where it will be installed, version to be resolved via coursier) and then put the executables in the specified directory. The only thing we need to figure out is how we can add the specified directory to the PATH via Wix, I haven't looked into this but I suspect the docs of sbt-native-packager will give us more insights about this.
  
As I said, if you're a Windows user and feel like helping, this would be an excellent way to contribute to the repository.
