### ISSUE TITLE
Use colors on Powershell or cmd.exe

### ISSUE THREAD

**Issue by andrezimmermann** [scalacenter/bloop#568]
SBT does correctly output color on powershell or `cmd.exe`. I don't see why not bloop can't also support color on windows.

**Comment by jvican** [comment]
A pull request on this is very much welcome, labeling as "Help Wanted".

**Comment by jvican** [comment]
I'll eventually fix this. Note that if you're using Windows 10, then you have to enable ASCII escape sequences manually because it's turned off by default https://stackoverflow.com/questions/51680709/colored-text-output-in-powershell-console-using-ansi-vt100-codes

**Comment by jvican** [comment]
Also, for those Windows users with cygwin (and not necessarily on Windows 10): you can run powershell inside cygwin to benefit from the current ansii escape sequences https://superuser.com/questions/85058/powershell-not-displaying-unix-colors

**Comment by jvican** [comment]
And for future reference this is about the best guide i've read to get colored output working on Windows https://github.com/rspec/rspec/wiki/Getting-colored-output-working-on-Windows 
  
Given that this is not high priority, I won't be focusing on this in the short-term. Help on this is welcome

**Comment by jvican** [comment]
Let's open this when someone is interested in having a look at this
