### ISSUE TITLE
Eliminate Nailgun messages

### ISSUE THREAD

**Issue by tindzk** [scalacenter/bloop#574]
The following messages are printed by the Bloop server:

```
Jun 23, 2018 9:37:39 AM com.martiansoftware.nailgun.NGSession run
INFO: NGSession shutting down
```

If Bloop is used in a CI setup, these messages pollute the output and therefore should be hidden.

**Comment by jvican** [comment]
These messages won't go away because they are sometimes useful to debug what the server is doing. If you're running this in the CI, you should find a way to redirect the output of the bloop server to a file.
