### ISSUE TITLE
Don't test dependent targets by default

### ISSUE THREAD

**Issue by jvican** [scalacenter/bloop#578]
Bloop's default test behavior is to test a project and all its dependencies. I think this is not the best default because it does exactly the opposite that many build tools do. We should change `--isolated` to `--dependent` or `--aggregate` or `--cascade` and revert the default behaviour.

**Comment by Duhemm** [comment]
I agree that the default behavior should be to test only the specified project.

We should maybe support calling `bloop test` without specifying a project to test all the projects.

What would be cooler than testing a project and its dependencies in my opinion, would be to test a project and the projects that depend on them. I'm not sure `--dependent` is actually useful. When we're changing a project, we're more interested in seeing how it affects the ones that depend on it, than the other way around.

Imagine a build where `my-dependent-project` depends on `my-lib`, which in turns depends on `my-root-project`.

```sh
# Introducing bugs in my-lib...
$ bloop test my-lib --cascade
> all tests passed for my-lib
> 3 failures in my-dependent-project # oh no, I broke this downstream project
```

```sh
# Introducing bugs in my-lib...
$ bloop test my-lib --dependent
> all tests passed for my-root-project # who cares? it cannot be impacted by changes in my-lib
> all tests passed for my-lib
```

I like `--cascade` or `--dependent` for that behavior.

**Comment by jvican** [comment]
>  I'm not sure --dependent is actually useful.
  
`--dependent` is our way of simulating aggregate in build tools like sbt, so that users can do `bloop test --dependent rootJS` and `bloop test --dependent rootJVM`.
  
It seems that the `--dependent` flag feels natural here, so let's use that one.

> We should maybe support calling bloop test without specifying a project to test all the projects.
  
We can take on this one when we do #575.

> What would be cooler than testing a project and its dependencies in my opinion, would be to test a project and the projects that depend on them. I'm not sure --dependent is actually useful. When we're changing a project, we're more interested in seeing how it affects the ones that depend on it, than the other way around.
  
Yes, I agree this would be cool. I always though of this as a partial step to implement reliable incremental test execution https://github.com/scalacenter/bloop/issues/61, so I think it's something we can do post 1.0.0. `testQuick` does this at the file level, your proposal does it at the project level. We probably need both.

**Comment by jvican** [comment]
This proposal reminds me of https://github.com/sbt/sbt-pull-request-validator which does the execution at the project level too.

**Comment by jvican** [comment]
The removal of `--isolated` is done in #590, and the implementation of `--cascade` is left for future work.
