### ISSUE TITLE
Add Total Elasped Time Info after Compile output

### ISSUE THREAD

**Issue by andrezimmermann** [scalacenter/bloop#583]
There is an already an elapsed time  after an `bloop compile <project> --verbose`
```
[D] Elapsed: 243020.210769 ms
```

Is it possible to add it as the regular info logger with human readable message? 
```
Elapsed: 4 minutes and 3 seconds
```

**Comment by jvican** [comment]
Duplicated of https://github.com/scalacenter/bloop/issues/258
