### ISSUE TITLE
Demote severity of missing top-level declaration error

### ISSUE THREAD

**Issue by jvican** [scalacenter/bloop#585]
@raul782 reports that the incremental compiler is being too stubborn when it cannot track dependencies in a file and fails with an error. There's nothing bad with this approach, except that this reporting happens in a generated source file by Play, and then it means it cannot be modified by the user to compile successfully.
  
Generated reverse route by Play:
```scala
import base.Routes.{prefix => _prefix, defaultPrefix => _defaultPrefix}
import play.core._
import play.core.Router._
import play.core.Router.HandlerInvokerFactory._
import play.core.j._

import play.api.mvc._
import _root_.controllers.Cms.Page
import _root_.se.radley.plugin.salat.Binders._
import _root_.org.joda.time._
import _root_.com.project.play.lib.binders.Binders._

import Router.queryString
```
  
Error:
```
[E] [E1] /target/scala-2.11/src_managed/main/cms/routes_reverseRouting.scala
[E]
[E]      Found names but no class, trait or object is defined in the compilation unit.
[E]      The incremental compiler cannot record the dependency information in such case.
[E]      Some errors like unused import referring to a non-existent class might not be reported.
[E]
[E]      L1: // @SOURCE:/Users/me/api/modules/cms/conf/cms.routes
```
  
The way I propose we fix this issue is by downgrading the level of severity of the warning, and maybe renaming the error message to be less verbose. Something like: "Attention: Zinc cannot detect dependencies in file with no top-level class, trait or object". This patch should be done upstream.

**Comment by jvican** [comment]
@raul782 I'm doing a lot of changes in the compiler bridge for 1.1.0, so I'm going to stage the fix for this with that branch instead of fixing this in 1.0.0. I'll ping you whenever the fix for this is publicly available :smile:.

**Comment by raul782** [comment]
Awesome 👍 thanks, will track the progress and try the issue as soon as it available

**Comment by jvican** [comment]
@raul782 You had fatal warnings enabled here, right?

**Comment by jvican** [comment]
I'm pretty sure this is fixed in latest master because the sbt plugin was fixed to pick up some scalac options that could be missed under certain scenarios.

**Comment by raul782** [comment]
Thank you, @jvican This issue fell out of my sight, I will test and report back
