### ISSUE TITLE
Enable line editing and completion in console

### ISSUE THREAD

**Issue by tues** [scalacenter/bloop#591]
As reported by @propensive in https://github.com/scalacenter/bloop/issues/497#issuecomment-393124794, due to the fact that we had to disable `jline` to make `console` work over `nailgun`, we no longer have line editing or tab completion. There are several ways to fix that proposed in https://github.com/scalacenter/bloop/issues/497#issuecomment-393134809. @jvican endorsed the following solution:
> we could probably modify [our] Nailgun client to make it use readline and support :completions

**Comment by jvican** [comment]
Note that I think ammonite does something similar to this in [its remote REPL implementation](http://ammonite.io/#RemoteREPL) (got from https://contributors.scala-lang.org/t/adding-network-input-and-output-to-the-repl/2063/4). Unfortunately we would need to roll out something of our own because Ammonite does not support Windows...

**Comment by jvican** [comment]
Actually, there is experimental Windows support in Ammonite via https://github.com/lihaoyi/Ammonite/pull/775/files. If somebody wants to give this a try, it would be interesting to have support for Ammonite too and let the users choose which shell should be used.

**Comment by propensive** [comment]
As an alternative idea (which I'm intending to use in Fury) you could modify the `bloop` script to special-case `bloop console` commands, and have it invoke `scala` directly, passing the appropriate classpath argument (which would come from Bloop, over Nailgun).

**Comment by jvican** [comment]
> As an alternative idea (which I'm intending to use in Fury) you could modify the bloop script to special-case bloop console commands, and have it invoke scala directly, passing the appropriate classpath argument (which would come from Bloop, over Nailgun).
  
@torkelrogstad has great make progress in adding ammonite support to bloop by using this strategy during today's Scala Center open source spree. We should apply the same strategy to the Scala console so that we also fix all errors around jline.

**Comment by jvican** [comment]
I'm adding `help wanted` on this one. @torkelrogstad's ammonite feature has just been merged :tada: so I'd love if someone takes care of doing the same for `scalac` so that we can close this ticket and these other two https://github.com/scalacenter/bloop/labels/task%20%2F%20console

**Comment by jvican** [comment]
We're planning to use a Scala-based Nailgun client as the CLI tool by default in a future version. The nailgun client is http://github.com/jvican/snailgun. It currently uses `readline` to read stdin as the default Python client.

However, it'd be good if somebody figures out what we would need to support line editing and console. Maybe there is a way we can support a remote scalac if we tweak the way we read stdin (we have the possibility of read stdin in bursts without blocking, for example, but I'm not sure if that alone is enough to have a remote jline work).

**Comment by jvican** [comment]
Bloop 2.0 will move completely away from the Scala console REPL interface and instead settle on Ammonite, which will in turn have support to offload compilation to Bloop via the upcoming code snippet API that it's in the works. Therefore, the idea proposed in this ticket won't be explored anymore.
