### ISSUE TITLE
Fix path to JSON schema in the docs

### ISSUE THREAD

**Issue by xingyif** [scalacenter/bloop#619]
On https://scalacenter.github.io/bloop/docs/configuration-format/#json-schema site,
![screen shot 2018-08-10 at 19 03 28](https://user-images.githubusercontent.com/15064985/43984695-185c0052-9cd0-11e8-960c-4ee5150fa99b.png)

JSON schema link (https://scalacenter.github.io/bloop/docson/bloop-schema.json) points to a 404 page

Should be an easy fix.

**Comment by jvican** [comment]
PR on this welcome. Thanks for reporting.
