### ISSUE TITLE
Speed up test execution (hot classloading)

### ISSUE THREAD

**Issue by jvican** [scalacenter/bloop#627]
I've noticed that the creation of the single-threaded pool to run tests takes around 1 second or sometimes slightly more in my laptop. This cost should go away. Bloop should cache the test loader across different test runs. The current cost also happens in tools like sbt.

**Comment by tindzk** [comment]
On a similar note, I observed that small cross-compiling test suites actually run up to twice as fast with Node (#572), but for larger test suites, JVM performs better and its start-up time becomes barely noticeable.

Would it be possible to run tests without forking?

**Comment by jvican** [comment]
I think having an open-source version of jrebel would be cool, but the amount of effort it would take would be staggering. I think the ideas collected here are great, but someone else would need to act on them (outside the scope of bloop, probably, and with lots of tests to make sure it works). On top of that, jrebel has some issue with regards to initialization (if a new field to a class is added, the field will not be initialized in objects that existed in the stack previous to this change), so it remains to be seen how much productivity it can be gained from jrebel after all.
  
I'll look into our test framework execution and see if we can make it faster to start up in another ticket.
