### ISSUE TITLE
Support jvm args as a command line option of test

### ISSUE THREAD

**Issue by pjfanning** [scalacenter/bloop#648]
Would it be possible to support JVM args alongside the existing `--args` support?
(https://scalacenter.github.io/bloop/docs/commands-reference/)

My use case is that my team's build.sbt files require that a -Dconfig.file param is used when calling the `test` task. The default setup in the build.sbt is for the CI server and local testing requires that you override the config.file system property with a local version.

**Comment by jvican** [comment]
Hello @pjfanning, the only thing you need to pass those arguments to the test framework is to write the arguments after `--`. For example, given a dummy test:
  
```scala
package bloop

import org.junit.Test

class DummyTest {
  @Test
  def foo: Unit = {
    println(System.getProperty("bloop.test"))
  }
}
```
  
You can run ` bloop test frontend -o bloop.DummyTest -- -Dbloop.test=asdf` and the test will print `asdf`.

**Comment by pjfanning** [comment]
Thanks @jvican - it turns out that my issue was with `sbt bloopInstall`. When I run this, it turns out I need the `-Dconfig.file=conf/application-test.conf` because this then gets baked into the .bloop json file. For example,

```
        "platform" : {
            "name" : "jvm",
            "config" : {
                "home" : "/Library/Java/JavaVirtualMachines/jdk1.8.0_172.jdk/Contents/Home/jre",
                "options" : [
                    "-Duser.timezone=UTC",
                    "-Dconfig.file=conf/application-test.conf"
                ]
            },
            "mainClass" : [
            ]
        },
```

**Comment by jvican** [comment]
:smile: great to know this issue is fixed on your end!
