### ISSUE TITLE
Implement buildTarget/mainClasses

### ISSUE THREAD

**Issue by jvican** [scalacenter/bloop#683]
Similar in spirit to #682, we want to expose our implementation to detect main classes via BSP's `buildTarget/mainClasses`, which was released in 1.0.0 as it was a functional requirement for a minimally decent BSP client-server experience.
  
This is going to be easy, we already have all the machinery to run JVM, Scala.js and Scala Native code.

**Comment by tgodzik** [comment]
That's already closed in Marek's PR
