### ISSUE TITLE
Send empty diagnostics after successful compilation

### ISSUE THREAD

**Issue by olafurpg** [scalacenter/bloop#692]
Consider the following sequence of events

1. Code compiles successfully, bloop does not publish diagnostics as expected
2. Change code so that it no longer compiles, bloop published error diagnostics as expected
3. Fix code so that it compiles again, bloop does not publish empty diagnostics (unexpected).

With the current behavior, the error diagnostics from stage 2 are still displayed in the editor after stage 3 even if all errors have been fixed.

It is not necessary, but allowed, for bloop to publish empty diagnostics every time a source file compiles successfully. I would recommend to publish only empty diagnostics if you know that given text document had errors in a previous compilation report.

**Comment by jvican** [comment]
See comment in #693.
