### ISSUE TITLE
Aggregate diagnostics for each text document

### ISSUE THREAD

**Issue by olafurpg** [scalacenter/bloop#693]
Currently, bloop sends a `build/publishDiagnostics` notification for every diagnostic 

```json
{
  "jsonrpc": "2.0",
  "method": "build/publishDiagnostics",
  "params": {
    "uri": "file:/Users/ollie/dev/metals/test-workspace/src/test/scala/example/UserTest.scala",
    "diagnostics": [
      {
        ...
        "message": "object User is not a member of package a"
      }
    ]
  }
}
{
  "jsonrpc": "2.0",
  "method": "build/publishDiagnostics",
  "params": {
    "uri": "file:/Users/ollie/dev/metals/test-workspace/src/test/scala/example/UserTest.scala",
    "diagnostics": [
      {
        ...
        "message": "not found: value name"
      }
    ]
  }
}

```

This means the last diagnostics "wins" and the earlier diagnostics do not appear in the editor.

I expected bloop to aggregate the diagnostics for each run so that the resulting json would look like this instead.
```json
{
  "jsonrpc": "2.0",
  "method": "build/publishDiagnostics",
  "params": {
    "uri": "file:/Users/ollie/dev/metals/test-workspace/src/test/scala/example/UserTest.scala",
    "diagnostics": [
      {
        ...
        "message": "object User is not a member of package a"
      },
      {
        ...
        "message": "not found: value name"
      }
    ]
  }
}
```

Alternatively, bloop can keep the current behavior if the `originId` is populated in which case we can do the aggregation on the client side.

**Comment by jvican** [comment]
After an offline discussion with @olafurpg, we have decided that #692 and #693 (this ticket) should be a responsibility of the language server. This way, all BSP clients don't have to choose between aggregation or streaming of diagnostics -- they get streaming by default, and if they aggregate if they will.
