### ISSUE TITLE
Support proxy in coursier instalation

### ISSUE THREAD

**Issue by crakjie** [scalacenter/bloop#698]
`http_proxy` and `https_proxy` are not passed to Java when starting the coursier installation.
[Indeed](https://docs.oracle.com/javase/8/docs/technotes/guides/net/proxies.html) java is not pulling `http_proxy` and `https_proxy` from environment vars.
I'm preparing a PR that correct this.

**Comment by crakjie** [comment]
I thinks there is another problem deeper.
When running `bloop compile aproject` I got this error:

```
[E] Server access Error: Failed to connect to repo1.maven.org/151.101.120.209:443 url=https://repo1.maven.org/maven2/ch/epfl/scala/compiler-bridge_2.11/1.1.7%2B62-0f4ad9d5/compiler-bridge_2.11-1.1.7%2B62-0f4ad9d5.pom
[E] Server access Error: Failed to connect to oss.sonatype.org/52.6.213.150:443 url=https://oss.sonatype.org/content/repositories/staging/ch/epfl/scala/compiler-bridge_2.11/1.1.7%2B62-0f4ad9d5/compiler-bridge_2.11-1.1.7%2B62-0f4ad9d5.pom
[W] 	module not found: ch.epfl.scala#compiler-bridge_2.11;1.1.7+62-0f4ad9d5
[W] ==== local: tried
[W]   /home/etienne/.ivy2/local/ch.epfl.scala/compiler-bridge_2.11/1.1.7+62-0f4ad9d5/ivys/ivy.xml
[W] ==== public: tried
[W]   https://repo1.maven.org/maven2/ch/epfl/scala/compiler-bridge_2.11/1.1.7+62-0f4ad9d5/compiler-bridge_2.11-1.1.7+62-0f4ad9d5.pom
[W] ==== sonatype-staging: tried
[W]   https://oss.sonatype.org/content/repositories/staging/ch/epfl/scala/compiler-bridge_2.11/1.1.7+62-0f4ad9d5/compiler-bridge_2.11-1.1.7+62-0f4ad9d5.pom
[W] 	::::::::::::::::::::::::::::::::::::::::::::::
[W] 	::          UNRESOLVED DEPENDENCIES         ::
[W] 	::::::::::::::::::::::::::::::::::::::::::::::
[W] 	:: ch.epfl.scala#compiler-bridge_2.11;1.1.7+62-0f4ad9d5: not found
[W] 	::::::::::::::::::::::::::::::::::::::::::::::
[W] 
```

I have check and it seems this file exists on `repo1.maven.org` so there is another proxy setting that was not parametred somewhere.

**Comment by jvican** [comment]
Yes, we happen to resolve two times more inside bloop (though this is something I want to get rid of, see #581). I would accept changes to make it work temporarily though. We use both coursier (for normal dep resolution) and ivy (for compiler bridge resolution).
  
`(state: State).commonOptions.env` contains the environment variables at the place where the nailgun client was run, so the final fix for this will probably entail mutating the system properties with the information of the environment variables.

**Comment by jvican** [comment]
> Should the proxy settings being read in from environment variable on each bloop command? ( in bloop.scala run )
  
This is the approach I favor. You can access the user-defined environment variables with the incantation I wrote in the previous message. I would add a small method in `Cli` that checks if the http proxy settings are in the user environment and, if they are, mutate the system property with its contents. I would invoke the method in the `run` method of `Cli`. That will be accessible for all the clients of the bloop server immediately, so we're assuming that https_proxy et all are defined consistently for its clients (which kind of makes sense).
  
Whenever we implement remote compilation, we may want to revisit this design decision as that invariant will not be met. But we're far away from that right now anyway, and we can always remove this special logic when #581 goes in.

**Comment by jvican** [comment]
@crakjie ^ this comment describes how i would go about to implement the fix for this issue
