### ISSUE TITLE
Add support for file watching `~`

### ISSUE THREAD

**Issue by jvican** [scalacenter/bloop#7]
We should probably add a really fast source file watching for `~compile` and `~test`. We may want to add this directly to Zinc rather than experiment with it directly in blossom. I prefer this approach since it's more generic.

**Comment by Jasper-M** [comment]
Is there something inherently wrong with just using `java.nio.file.WatchService` for this? Not that it has the most beautiful interface...

**Comment by jvican** [comment]
We're using directory-watcher because it claims speedups in OSX and does not do polling. I have a prototype with it I'll PR any time soon.

**Comment by fsvehla** [comment]
> Is there something inherently wrong with just using java.nio.file.WatchService for this? Not that it has the most beautiful interface...

It uses polling under macOS and Linux, which leads to for example SBT using 40% of CPU constantly watching a medium size code base.

**Comment by jvican** [comment]
Does it under LInux? I think under linux it uses fsevents.

**Comment by fsvehla** [comment]
My information re: Linux might be outdated, I am not using it for development.

**Comment by gmethvin** [comment]
The OS differences are basically:
 - Windows JDK `WatchService` does async watching and recursive watching (`ExtendedWatchEventModifier.FILE_TREE`).
 - Linux JDK `WatchService` does async watching but not recursive watching. In practice you can handle the recursive case you can register a new `WatchKey` for directories when they are created.
 - macOS JDK `WatchService` uses polling and at best can be configured to poll every two seconds. To get a decent experience you need to use a separate native program or JNI/JNA (directory-watcher uses JNA).

I think it makes sense to use a higher-level API, perhaps something like `File.Monitor` from better-files. (directory-watcher already implements that: https://github.com/gmethvin/directory-watcher/#better-files-integration-scala). Besides the fact that the `WatchService` API is not very nice, it's also useful to customize the recursive aspect so it uses the most efficient mechanism for each OS.

**Comment by jvican** [comment]
#125 successfully implements this feature with your work, thanks @gmethvin. In the next days we'll experiment with file watching in bloop in larger projects and we'll see how it fares in comparison with the default file watching algorithms in sbt/sbt.
