### ISSUE TITLE
Improve systemd documentation

### ISSUE THREAD

**Issue by crakjie** [scalacenter/bloop#701]
the systemd part of the documentation ask to do `ln -s $HOME/.bloop/systemd/bloop.service $HOME/.config/systemd/user/` en then enable bloop.

In my case it's fail with  `Failed to execute operation: Too many levels of symbolic links`.

I read [there](https://www.raspberrypi.org/forums/viewtopic.php?t=203616) that we should let systemd make the link with   
`systemctl --user enable $HOME/.bloop/systemd/bloop.service`

I'm not sure all of this but it seems to work in my configuration

**Comment by jvican** [comment]
I would welcome a PR making this change @crakjie :smile:

**Comment by jvican** [comment]
Fixed in #702
