### ISSUE TITLE
Avoid duplicate compilation for parallel requests

### ISSUE THREAD

**Issue by olafurpg** [scalacenter/bloop#703]
To reproduce: send two `buildTarget/compile` requests for the same build target.

Obtained

```
Compiling 4 Scala sources to /Users/olafurpg/dev/sbt/.bloop/stdTaskProj/scala-2.12/classes ...
Compiling 4 Scala sources to /Users/olafurpg/dev/sbt/.bloop/stdTaskProj/scala-2.12/classes ...
```

Expected
```
 Compiling 4 Scala sources to /Users/olafurpg/dev/sbt/.bloop/stdTaskProj/scala-2.12/classes ...
```

As a BSP client, I expect bloop to synchronize on build targets to avoid redundant compilation.

**Comment by jvican** [comment]
Closing in favor of the more general https://github.com/scalacenter/bloop/issues/704. Note that this was also discussed in https://github.com/scalacenter/bloop/pull/680:
  
> Alongside these missing items, I'd like to implement request buffering in bloop so that the clients can indiscriminately send request without taking into account whether they finished or not. I suspect this is not going to be easy.
