### ISSUE TITLE
Respect logLevel setting from sbt

### ISSUE THREAD

**Issue by olafurpg** [scalacenter/bloop#707]
To reproduce, create an empty project in a directory `warnings/`

```scala
// build.sbt
logLevel := LLevel.Error
scalacOptions += "-Ywarn-unused"
// src/main/scala/Foo.scala
import scala.concurrent.Future
object Foo
```
Running from the shell `sbt bloopInstall && bloop compile warnings` results in the following warning
```
bloop compile warnings
Compiling 1 Scala source to /Users/olafurpg/dev/scalafix/target/warnings/.bloop/warnings/scala-2.12/classes ...
[W]  [E1] src/main/scala/Foo.scala:1:25
[W]       Unused import
[W]       L1: import scala.concurrent.Future
[W]                                   ^
[W] src/main/scala/Foo.scala: L1 [E1]
```
Compiling from sbt produces no warning
```
> compile
[success] Total time: 1 s, completed Nov 8, 2018 6:10:33 PM
```

While testing the BSP integration in the Scalafix build I get a lot of unwanted warnings in the editor
![2018-11-08 18 11 57](https://user-images.githubusercontent.com/1408093/48215101-cf1ef900-e381-11e8-9345-ed91950651c5.jpg)

**Comment by jvican** [comment]
@olafurpg Do you expect other tasks like test to only show errors and filter out warnings? Or are you a proponent of interpreting `logLevel` only for compilation?

**Comment by olafurpg** [comment]
I expect only compilation warnings to be filtered out, but I'd follow sbt here if `logLevel` applies to test logs as well.

**Comment by jvican** [comment]
The `logLevel` in the ticket description will filter out any non-error coming from a task scoped to that module, so that applies to both `compile` and `test`. Maybe what you really meant was `logLevel in Compile := LLevel.Error`?
  
I'll think about how I can add it this to our json schema neatly. The final solution would probably be as generic as sbt's.

**Comment by olafurpg** [comment]
There are no test sources in the scalafix project where I use `logLevel`.

> The final solution would probably be as generic as sbt's.

Awesome, that would match my expectation.

**Comment by jvican** [comment]
> There are no test sources in the scalafix project where I use logLevel.
  
I meant the `compile` and `test` tasks, so if you had test sources and your tests emitted warnings, sbt would swallow them and not show them to you :smile: That's why I think you probably meant `logLevel in compile` instead of the more general `logLevel`.

**Comment by jvican** [comment]
I'm closing this feature request as I cannot see implementing it any time soon. If somebody is up for it, let me know and I'm happy to provide pointers to tackle the ticket.
