### ISSUE TITLE
Run main classes defined outside of project

### ISSUE THREAD

**Issue by tindzk** [scalacenter/bloop#716]
Currently, Bloop does not allow to run main classes that were defined by a dependency. For example, in the case of Play, the entry point for the web server is not defined within the project.

It is reproducible as follows using the default Play template (`sbt new playframework/play-scala-seed.g8`):

```shell
$ bloop run root -m play.core.server.ProdServerStart 
[E] Missing main class  in project 'root'
```

**Comment by jvican** [comment]
I guess that what we need here is to avoid comparing the user-defined main class (in this case `play.core.server.ProdServerStart`) with the discovered main classes in the project (in this case, zero) and just completely trusting the user when they say they want to run a certain main class. I believe this is what sbt does but it would be good to double-check.

**Comment by jvican** [comment]
I commented before I saw the open PR, which I just merged in https://github.com/scalacenter/bloop/pull/717. However, adding a test in another PR would be appreciated
