### ISSUE TITLE
Set current working directory to the project base directory

### ISSUE THREAD

**Issue by jvican** [scalacenter/bloop#724]
When a user runs an application in bloop, the current working directory of the spawned system process is set to the workspace directory. However, this goes against the tradition of using instead the project base directory of the executed application in, for example, sbt projects that have enabled forked tests or program execution (which is the default in bloop).
  
Bloop should have the same behavior.

**Comment by tindzk** [comment]
This would be useful for projects that rely on the current working directory being correctly set. There is already a member `directory` in `bloop.config.Project` which is populated with sbt's `baseDirectory` setting. We could change the current working directory to this value.

**Comment by er1c** [comment]
This might be partially incomplete.  In a multi-project config

```
// Main project that mimics the pre-sub-project ta-catalog project
lazy val `ta-catalog` = (project in file("."))
  .settings(commonSettings:_*).settings(
    // sbt-native-package requires a mainClass, it could be a non-existant "com.dummy.App", but lets default to the catalog web app
    //   We use the run.sh script to run arbitrary main classes from the staged script
    (mainClass in Compile := Some("ta.catalog.website.CatalogWebApp"))
  )
  .enablePlugins(JavaAppPackaging)
  .dependsOn(loader, website, webservice, flyway)
  .aggregate(sharedDeps, common, logging, orig, form, tecrmi, translations, loader, website, webservice, jooq, jooq_generator, flyway)

lazy val sharedDeps = project.settings(((name := "ta-catalog-deps") +: commonSettings ++: dependencySettings):_*)

lazy val common       = project.settings(((name := "ta-catalog-common") +: commonSettings):_*).dependsOn(sharedDeps, translations)
...
```

The working directory for compiling should be the parent (e.g. `ta-catalog`)


We have templates stored in the root project directory that get expanded from macros in a dependency project (e.g. `website`) that refer to simply `templates/foo.ssp` - which is relative to the parent project.

There is also a corresponding sbt configuration: 

```
  baseDirectory in (Compile, run) := file("."),
  baseDirectory in (Test) := file("."), // fork sets the working to the subproject, so a test can't read the config_crypto_keys
```

The generated `.bloop/website.json` has a `workspaceDir`: https://gist.github.com/er1c/00360f5263383f9a47e24e90ca06f542

```
$ bloop help
bloop 1.3.4
```

After running:

`$ METALS_ENABLED=true sbt bloopInstall`


```
$ cat ~/.sbt/1.0/plugins/metals.sbt
// DO NOT EDIT! This file is auto-generated.
// By default, this file does not do anything.
// If the environment variable METALS_ENABLED has the value 'true',
// then this file enables sbt-metals and sbt-bloop.

libraryDependencies := {
  import Defaults.sbtPluginExtra
  val oldDependencies = libraryDependencies.value
  if (System.getenv("METALS_ENABLED") == "true") {
    val bloopModule = "ch.epfl.scala" % "sbt-bloop" % "1.3.4"
    val metalsModule = "org.scalameta" % "sbt-metals" % "0.7.6"
    val sbtVersion = Keys.sbtBinaryVersion.in(TaskKey[Unit]("pluginCrossBuild")).value
    val scalaVersion = Keys.scalaBinaryVersion.in(update).value
    val bloopPlugin = sbtPluginExtra(bloopModule, sbtVersion, scalaVersion)
    val metalsPlugin = sbtPluginExtra(metalsModule, sbtVersion, scalaVersion)
    List(bloopPlugin, metalsPlugin) ++ oldDependencies.filterNot { dep =>
      (dep.organization == "ch.epfl.scala" && dep.name == "sbt-bloop") ||
      (dep.organization == "org.scalameta" && dep.name == "sbt-metals")
    }
  } else {
    oldDependencies
  }
}
```

But as far as I can tell the macro expansion isn't working correctly and its still using the 'baseDirectory` from the `directory` property: https://github.com/scalacenter/bloop/blob/master/frontend/src/main/scala/bloop/engine/Interpreter.scala#L544

**Comment by davidmlw** [comment]
I would suggest a command option to setup the working directory. In some cases there are senerio to set the working directory to the one that holds `.bloop`.
```
workspace/.bloop
workspace/projectA
workspace/projectB
```

```
bloop run --projects projectA main args ## working directory to be projectA
bloop run --work-dir . --projects projectA main args ## working directory to be workspace
```
