### ISSUE TITLE
Can not run `bloop server` on macOS, only `blp-server`

### ISSUE THREAD

**Issue by igor-ramazanov** [scalacenter/bloop#753]
```
rm -rf ~/.bloop
curl -L https://github.com/scalacenter/bloop/releases/download/v1.1.1/install.py | python
bloop server
Error: Invalid or corrupt jarfile /Users/igorramazanov/.bloop/blp-server
Traceback (most recent call last):
  File "/Users/igorramazanov/.bloop/bloop", line 1084, in <module>
    main()
  File "/Users/igorramazanov/.bloop/bloop", line 1047, in main
    except CallProcessError as e2:
NameError: global name 'CallProcessError' is not defined
```

**Comment by igor-ramazanov** [comment]
Seems that the `blp-server` script contains a typo:
`/usr/libexec/java_home -v 1.8 -F -R --exec java        rjar`
should be `/usr/libexec/java_home -v 1.8 -F -R --exec java        -jar`

**Comment by ouchxp** [comment]
This issue is not exist in the code, but only in the release, really strange.

**Comment by countfloyd** [comment]
Even after this fix, when I run "bloop server", I get:
```
Error: Invalid or corrupt jarfile /usr/local/bin/blp-server
Traceback (most recent call last):
  File "/usr/local/bin/bloop", line 1084, in <module>
    main()
  File "/usr/local/bin/bloop", line 1047, in main
    except CallProcessError as e2:
NameError: global name 'CallProcessError' is not defined
```

**Comment by jvican** [comment]
Does running `blp-server` instead fix it for you? Will have a look at the typo and what's happening here.
  
> This issue is not exist in the install.py code, but only in the release, really strange.
  
I had to manually update the `install.py` releases to fix some problems with the installation script. I didn't find time to fix it in the repository yet because I'm on vacation until Sunday.

**Comment by countfloyd** [comment]
Yes, or "brew services start bloop" works as well

**Comment by countfloyd** [comment]
Bloop 1.1.1 on Mac seems really broken. I ran "sbt bloopInstall" and then "bloop compile my-project" and it just hangs with no CPU activity. control-c aborts it.

**Comment by jvican** [comment]
@igor-ramazanov Why are you installing via curl and not brew? Brew is the recommended way to install bloop in Mac OS.

**Comment by jvican** [comment]
@igor-ramazanov That being said, there is clearly an issue with the `bloop server` invocation, I'll fix it today and probably do another release tomorrow even though there are some workarounds. Thanks for reporting!

**Comment by igor-ramazanov** [comment]
@jvican Thank you for your work!
I've checked installation and running by `brew` and seems that the `blp-server` contains a small typo as I've wrote in the first comment of this issue:
```
$ brew install scalacenter/bloop/bloop
$ brew services start bloop
$ cat /usr/local/Cellar/bloop/1.1.1/log/bloop/bloop.err.log
Error: Could not find or load main class rjar
```

After fixing the `blp-server` it works well.

**Comment by gabro** [comment]
I can confirm I had the same issue (installing with brew).

Even after fixing it, I can only run `blp-server` and not `bloop server`.

**Comment by manuzhang** [comment]
`bloop server` failed for me with `v1.1.2` on MacOS

```
Starting the bloop server... this may take a few seconds
Running /Users/doriadong/.bloop/blp-server as a jar...
Error: Invalid or corrupt jarfile /Users/doriadong/.bloop/blp-server
Running /Users/doriadong/.bloop/blp-server as a script...
Traceback (most recent call last):
  File "./bloop", line 1059, in main
    check_call(java_cmd)
  File "/Users/doriadong/miniconda3/envs/py3/lib/python3.7/subprocess.py", line 328, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['java', '-jar', '/Users/doriadong/.bloop/blp-server']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./bloop", line 1115, in <module>
    main()
  File "./bloop", line 1076, in main
    print("Shelling out in Unix system with " + cmd)
TypeError: can only concatenate str (not "list") to str
```

**Comment by jvican** [comment]
@manuzhang Upgrading to v1.2.0 (which is on its way to Maven) should fix it

**Comment by manuzhang** [comment]
It seems there is no release tag for 1.2.0 ?

**Comment by jvican** [comment]
@manuzhang v1.2.0 is now available in the GitHub releases page
