### ISSUE TITLE
Upgrade documentation is slightly wrong

### ISSUE THREAD

**Issue by gabro** [scalacenter/bloop#754]
In the release notes it says:

If you're on Mac OS X, upgrade to the latest version with:

```
$ brew install scalacenter/bloop/bloop
```

However that command will fail if you have a previous version installed:

```
❯ brew install scalacenter/bloop/bloop
==> Installing bloop from scalacenter/bloop
Error: bloop 1.0.0-M11 is already installed
To upgrade to 1.1.1, run `brew upgrade bloop`
```

The correct command for upgrading (as suggested by the error message) is

```
brew upgrade bloop
```

**Comment by jvican** [comment]
Fixed in the latest release notes, thanks :+1:
