### ISSUE TITLE
Don't report problems if origin files do not exist anymore

### ISSUE THREAD

**Issue by jvican** [scalacenter/bloop#762]
See https://twitter.com/channingwalton/status/1074592345256017920

**Comment by olafurpg** [comment]
Steps to reproduce

- create file A.scala
- add compile error to A.scala
- diagnostics are published as expected
```json
{
  "method": "textDocument/publishDiagnostics",
  "params": {
    "uri": "file:///Users/olafurpg/dev/metals/tests/unit/src/test/scala/tests/BspSwitchSlowSuite.scala",
    "diagnostics": [
      {
    ...
        "message": "type mismatch;\n found   : String(\"\")\n required: Int"
      }
    ]
  }
}
```
- remove A.scala
- expected a `publishDiagnostics` notification with `reset=true` and `diagnostics=[]` for `A.scala`, but obtained no notification.

**Comment by channingwalton** [comment]
Awesome, thank you.
