### ISSUE TITLE
Investigate macro failure in scalaz-deriving

### ISSUE THREAD

**Issue by kubukoz** [scalacenter/bloop#763]
As mentioned on gitter.

(opening this to make sure I don't forget to prepare a reproduction)

**Comment by jvican** [comment]
@olafurpg found a reproduction so I'll be using his, let me investigate about what's going on and will report back. Thank you @kubukoz for your willingness to find a reproduction and file this ticket :smile:

**Comment by jvican** [comment]
I found the issue here. Next release will have a fix for it.

**Comment by kubukoz** [comment]
Wonderful! Thanks a lot :)

**Comment by jvican** [comment]
I have manually confirmed this issue is fixed in https://github.com/scalacenter/bloop/releases/tag/v1.2.2
