### ISSUE TITLE
Bloop invocation has to happen in same drive it's installed

### ISSUE THREAD

**Issue by Katrix** [scalacenter/bloop#770]
Just installed bloop using scoop on Windows, but I can't seem to be able to run the bloop script if I'm not also on the same drive as where I installed bloop. Switching to the right drive fixes it.

```
PS C:\> bloop about
python: can't open file '\DevTools\Scoop\apps\bloop\1.1.2\bloop': [Errno 2] No such file or directory
PS C:\> cd D:\
PS D:\> bloop about
Could not connect to server 127.0.0.1:8212

Have you forgotten to start bloop's server? Run it with `bloop server`.
Check our usage instructions in https://scalacenter.github.io/bloop/
PS D:\>
```

**Comment by jvican** [comment]
Do you have any idea why this could be happening @Katrix?

**Comment by jvican** [comment]
@Katrix thanks :smile: https://github.com/scalacenter/bloop/pull/771 should fix it. have you checked it works in any disk? if that's the case we'll merge and then 1.2.0 will be cut soon and have this fix in

**Comment by Katrix** [comment]
I only have two disks connect to my computer, but I was able to run bloop from the C drive.
