### ISSUE TITLE
Fixed compile errors are not cleared with reset diagnostics

### ISSUE THREAD

**Issue by olafurpg** [scalacenter/bloop#785]
To reproduce

- compile the following source file, no compilation errors as expected
```scala
object A {
  val x = 2
}
```
- compile the following source, diagnostics are published as expected. However, note that two diagnostics are published with the same start offset but the second error has different end position.
```scala
object A {
  val x = 1
  val x = 2 // error: x is already defined
}
```
- compile the original source file, fixing the error, but bloop does not publish any diagnostics. I expected it to publish `reset: true, diagnostics: []`
```scala
object A {
  val x = 2
}
```

This bug results in errors remaining in the editor even if they have been fixed.
![screenshot 2019-01-08 at 14 45 40](https://user-images.githubusercontent.com/1408093/50834341-16127600-1354-11e9-9499-1a97990bb8ad.png)

Possibly related https://github.com/scalameta/metals/issues/426

<details><summary>JSON-RPC trace</summary>
{
  "jsonrpc": "2.0",
  "method": "build/initialized",
  "params": null
}
{
  "jsonrpc": "2.0",
  "id": "2",
  "method": "workspace/buildTargets",
...skipping...
  "method": "build/publishDiagnostics",
  "params": {
    "textDocument": {
      "uri": "file:///Users/olafurpg/dev/metals/test-workspace/src/main/scala/example/User.scala"
    },
    "buildTarget": {
      "uri": "file:/Users/olafurpg/dev/metals/test-workspace/?id\u003dtest-workspace"
    },
    "diagnostics": [
      {
        "range": {
          "start": {
            "line": 4,
            "character": 6
          },
          "end": {
            "line": 4,
            "character": 6
          }
        },
        "severity": 1,
        "message": "x is already defined as value x"
      }
    ],
    "reset": true
  }
}
{
  "jsonrpc": "2.0",
  "method": "build/publishDiagnostics",
  "params": {
    "textDocument": {
      "uri": "file:///Users/olafurpg/dev/metals/test-workspace/src/main/scala/example/User.scala"
    },
    "buildTarget": {
      "uri": "file:/Users/olafurpg/dev/metals/test-workspace/?id\u003dtest-workspace"
    },
    "diagnostics": [
      {
        "range": {
          "start": {
            "line": 4,
            "character": 6
          },
          "end": {
            "line": 4,
            "character": 11
          }
        },
        "severity": 1,
        "message": "x  is already defined as value x"
      }
    ],
    "reset": false
  }
}
{
  "jsonrpc": "2.0",
  "method": "build/taskFinish",
  "params": {
    "taskId": {
      "id": "3"
    },
    "eventTime": 1546954848844,
    "message": "Compiled \u0027test-workspace\u0027",
    "status": 2,
    "dataKind": "compile-report",
    "data": {
      "target": {
        "uri": "file:/Users/olafurpg/dev/metals/test-workspace/?id\u003dtest-workspace"
      },
      "errors": 2,
      "warnings": 0
    }
  }
}
{
  "jsonrpc": "2.0",
  "method": "build/logMessage",
  "params": {
    "type": 1,
    "message": "\u0027test-workspace\u0027 failed to compile."
  }
}
{
  "jsonrpc": "2.0",
  "id": "8",
  "result": {
    "statusCode": 2
  }
}
{
  "jsonrpc": "2.0",
  "id": "9",
  "method": "buildTarget/compile",
  "params": {
    "targets": [
      {
        "uri": "file:/Users/olafurpg/dev/metals/test-workspace/?id\u003dtest-workspace"
      }
    ]
  }
}
{
  "jsonrpc": "2.0",
  "method": "build/taskStart",
  "params": {
    "taskId": {
      "id": "4"
    },
    "eventTime": 1546954857093,
    "message": "Compiling \u0027test-workspace\u0027",
    "dataKind": "compile-task",
    "data": {
      "target": {
        "uri": "file:/Users/olafurpg/dev/metals/test-workspace/?id\u003dtest-workspace"
      }
    }
  }
}
{
  "jsonrpc": "2.0",
  "method": "build/taskFinish",
  "params": {
    "taskId": {
      "id": "4"
    },
    "eventTime": 1546954857098,
    "message": "Compiled \u0027test-workspace\u0027",
    "status": 1,
    "dataKind": "compile-report",
    "data": {
      "target": {
        "uri": "file:/Users/olafurpg/dev/metals/test-workspace/?id\u003dtest-workspace"
      },
      "errors": 0,
      "warnings": 0
    }
  }
}
{
  "jsonrpc": "2.0",
  "id": "9",
  "result": {
    "statusCode": 1
  }
}
</details>

**Comment by olafurpg** [comment]
To elaborate on one thing that may be unrelated to this issue.

> two "x is already defined" diagnostics are published with the same start offset but the second error has different end position.

The Scala `ConsoleReporter` extends [`AbstractReporter`](https://github.com/scala/scala/blob/2.12.x/src/compiler/scala/tools/nsc/reporters/AbstractReporter.scala) that filters messages based on offsets and severity. For example, in some cases, `bloop compile` reports two errors while `sbt compile` and `scalac` report only one

```scala
$ bloop compile test-workspace
[E] [E2] src/main/scala/example/User.scala:5:7
[E]      x  is already defined as value x
[E]      L5:   val x = 2
[E]                ^
[E] [E1] src/main/scala/example/User.scala:5:7
[E]      x is already defined as value x
[E]      L5:   val x = 2
[E]                ^

$ sbt compile
[info] Compiling 1 Scala source to /Users/olafurpg/dev/metals/test-workspace/target/scala-2.12/classes ...
[error] /Users/olafurpg/dev/metals/test-workspace/src/main/scala/example/User.scala:5:7: x is already defined as value x
[error]   val x = 2
[error]       ^
[error] one error found

$ scalac src/main/scala/example/User.scala
src/main/scala/example/User.scala:5: error: x is already defined as value x
  val x = 2
      ^
```

**Comment by jvican** [comment]
The commit linking to this ticket above [fixes this issue](https://github.com/scalacenter/bloop/commit/e2c1818dbcb8421b8d1ae6aaebac0e0b2add9809#diff-e35ad9d16b8aa5f828fd6950e0a7caf0R622). I didn't have to change the logic to make it pass, but before implementing the refactoring in the test suite I also implemented the rich diagnostics reporting based on phase information, so that's most likely why it passes now.

**Comment by olafurpg** [comment]
Thanks @jvican. I published Bloop locally at the commit e2c1818dbcb8421b8d1ae6aaebac0e0b2add9809 and was still able to reproduce the stale diagnostics issue.

To reproduce

- have running bloop server from commit e2c1818dbcb8421b8d1ae6aaebac0e0b2add9809
- checkout this branch in metals https://github.com/olafurpg/metals/tree/no-op-reproduce
- run `unit/testOnly -- tests.DiagnosticsSlowSuite.no-op` in sbt, it fails with the following diff

```diff

=======
=> Diff
=======
--- obtained
+++ expected
@@ -1,6 +1,1 @@
-a/src/main/scala/a/NoOp.scala:4:2: error: x is already defined as value x
-}
- ^
-a/src/main/scala/a/NoOp.scala:4:2: error: x  is already defined as value x
-}
- ^
+
  tests.DiffAssertions$.colored(DiffAssertions.scala:31)
  tests.BaseSuite.assertNoDiff(BaseSuite.scala:82)
  tests.DiagnosticsSlowSuite$.$anonfun$new$45(DiagnosticsSlowSuite.scala:265)
```

Here is a full BSP trace of the test case https://gist.github.com/olafurpg/ae9a563bdde66a4c9ef435fbfea552ea#file-bsp-trace-json-L727-L791 Observe that it goes from `errors: 2` to `errors: 0` without `build/publishDiagnostics` notifications.

**Comment by jvican** [comment]
Thanks, I was able to successfully reproduce after I found a tiny error in my test reproduction. I've pushed a commit that will hopefully fix all the problems with the diagnostics reporting when no-ops happen. I've taken the liberty of adding more test cases to make sure that it works not only in the presence of single errors but also combinations of errors and warnings.

**Comment by olafurpg** [comment]
Thanks @jvican I can confirm that I'm unable to reproduce this issue at 1.2.1+17 e3c02368 (latest commit in #792)
