### ISSUE TITLE
How do I shutdown blp-coursier?

### ISSUE THREAD

**Issue by olafurpg** [scalacenter/bloop#791]
When I start Bloop launcher via Metals I have three running processes, as expected
```
$ jps
66296 blp-coursier
66280 bloop-launch.jar
66271 Main
```

When I exit Metals I have one remaining process `blp-coursier`, as expected
```
$ jps
66296 blp-coursier
```

Running `bloop help` works as expected

```
$ bloop help
bloop 1.2.1
```

Running `bloop exit` seems to kill the process, as expected

```
$ bloop exit
Jan 12, 2019 2:42:06 PM com.martiansoftware.nailgun.NGServer shutdown
WARNING: Exception shutting down Nailgun server
java.lang.InterruptedException
$ bloop help
Could not connect to server 127.0.0.1:8212
```

Running `jps` shows that the `blp-coursier` process is still alive, unexpected
```
$ jps
66296 blp-coursier
```

Is there a better way to kill the `blp-coursier` process than `kill $PID`?

**Comment by jvican** [comment]
> Running jps shows that the blp-coursier process is still alive, unexpected
  
At this point, is the client that established the connection still running or is it dead? The blp-coursier process should die right after the moment the client of the launcher does too.

**Comment by olafurpg** [comment]
Yes, the Metals client (`66271 Main`) that started the launcher and `bloop-launch.jar` are both dead. The build shutdown procedure also took place

```json
{
  "jsonrpc": "2.0",
  "id": "9",
  "method": "build/shutdown",
  "params": null
}
{
  "jsonrpc": "2.0",
  "id": "9",
  "result": {}
}
{
  "jsonrpc": "2.0",
  "method": "build/exit",
  "params": null
}
```

**Comment by jvican** [comment]
I will try to reproduce, the right behavior should be that the coursier-launched bloop instance is killed right when the exit is handled by the client.

**Comment by jvican** [comment]
> Running jps shows that the blp-coursier process is still alive, unexpected
  
The blp-coursier process seems to be alive only when brew services launches it. I cannot reproduce in macOS by running `bloop server` in one terminal and killing it in another one. The coursier process that starts bloop is successfully killed.

**Comment by olafurpg** [comment]
It might be that brew services automatically restarts the process in that case, gonna close this with "working as expected" in that case. I'll report again if this pops up, we currently aren't using the bloop launcher yet in Metals.
