### ISSUE TITLE
Release compiler bridge for 2.13.0-RC1

### ISSUE THREAD

**Issue by tindzk** [scalacenter/bloop#806]
I created a [minimal Bloop project](https://github.com/tindzk/scala213-bloop) that uses the compiler version 2.13.0-M2. It appears that the pre-release version is stripped from the bridge's artefact name:

```
$ bloop run example                                            
Attempting to fetch ch.epfl.scala:compiler-bridge_2.13:1.2.1+106-0dad4a69.
[W]     module not found: ch.epfl.scala#compiler-bridge_2.13;1.2.1+106-0dad4a69
[W] ==== local: tried
[W]   /home/tim/.ivy2/local/ch.epfl.scala/compiler-bridge_2.13/1.2.1+106-0dad4a69/ivys/ivy.xml
[W] ==== public: tried
[W]   https://repo1.maven.org/maven2/ch/epfl/scala/compiler-bridge_2.13/1.2.1+106-0dad4a69/compiler-bridge_2.13-1.2.1+106-0dad4a69.pom
[W] ==== sonatype-staging: tried
[W]   https://oss.sonatype.org/content/repositories/staging/ch/epfl/scala/compiler-bridge_2.13/1.2.1+106-0dad4a69/compiler-bridge_2.13-1.2.1+106-0dad4a69.pom
[W]     ::::::::::::::::::::::::::::::::::::::::::::::
[W]     ::          UNRESOLVED DEPENDENCIES         ::
[W]     ::::::::::::::::::::::::::::::::::::::::::::::
[W]     :: ch.epfl.scala#compiler-bridge_2.13;1.2.1+106-0dad4a69: not found
[W]     ::::::::::::::::::::::::::::::::::::::::::::::
[W] 
[E] The compiler bridge sources ch.epfl.scala:compiler-bridge_2.13:1.2.1+106-0dad4a69:compile could not be retrieved.
[E] 
[E]     Note: Unresolved dependencies path:
[E]             ch.epfl.scala:compiler-bridge_2.13:1.2.1+106-0dad4a69
[E]               +- org.scala-sbt.temp:temp-module-52f238aede5a1d8d7a484c2bec27a144810e2ac0:1.2.1+106-0dad4a69
```

The correct artefact name is `compiler-bridge_2.13.0-M2`.

**Comment by jvican** [comment]
Yes, this problem is well known with 2.13, I’m closing because next zinc version will have this problem for the latest RC.

**Comment by tindzk** [comment]
As I understood [this message](https://github.com/scalacenter/bloop/issues/601#issuecomment-412236103), Zinc does support 2.13.0-M2, but not 2.13.0-M4. Aren't the compiler bridges resolved by Bloop and not by Zinc?

**Comment by jvican** [comment]
The issue here is that I forgot to publish Zinc for 2.13.0-M2, that's why you cannot use them :wink:

**Comment by tindzk** [comment]
I see, but the bridge does exist for Bloop v1.2.1: https://repo1.maven.org/maven2/ch/epfl/scala/compiler-bridge_2.13.0-M2/1.2.1+106-0dad4a69/compiler-bridge_2.13.0-M2-1.2.1+106-0dad4a69.pom Judging from the POM file, this artefact bundles the Zinc compiler.

**Comment by thesamet** [comment]
Hitting the same issue now with Scala 2.13.0-M5. Can we re-open this ticket, or should I file another one?

**Comment by jvican** [comment]
@thesamet I'll be releasing a zinc version that works for 2.13.0-M5 soon so, hopefully, we'll solve this issue once and for all.

**Comment by jvican** [comment]
Note that I was mostly making time until the RC is out, but it's taking some time so it's probably better to go ahead and release 2.13.0-M5 first.

**Comment by jvican** [comment]
RC1 is out and I'm already working on supporting it. I'll get back to you when I have something published and usable.

**Comment by jvican** [comment]
Fixed in latest master, users that need bloop as a linden can use it by installing bloop 1.2.5+454-4793d22a. Users that however need to install it need to follow the installation instruction in our developer docs https://scalacenter.github.io/bloop/docs/contributing-guide#install-a-snapshot-release-in-your-machine
