### ISSUE TITLE
Install script shows incorrect default for "-d" option

### ISSUE THREAD

**Issue by BardurArantsson** [scalacenter/bloop#807]
The install script contains this bit of code:

```py
parser.add_argument(
    '-d',
    '--dest',
    default=BLOOP_DEFAULT_INSTALLATION_TARGET,
    help="Where to install Bloop, defaults to %s" % os.getcwd())
```

but as I'm sure you're aware BLOOP_DEFAULT_INSTALLATION_TARGET is

```py
BLOOP_DEFAULT_INSTALLATION_TARGET = join(expanduser("~"), ".bloop")
```

so `os.getcwd()` should be replaced by `BLOOP_DEFAULT_INSTALLATION_TARGET`

EDIT: formatting

**Comment by jvican** [comment]
Yes, this is a small bug in the docs of our python installer. Would you mind sending a PR to fix it? https://github.com/scalacenter/nailgun
