### ISSUE TITLE
Add Bloop to SdkMan

### ISSUE THREAD

**Issue by diesalbla** [scalacenter/bloop#814]
[SdkMan](https://sdkman.io/) is a package manager, available for several operating systems, which is specialised for JVM development tools, such as compilers for several languages, and build tools (such as Ant, Maven, Gradle). Currently, both Scala and Sbt are already distributed through Sdk.

The purpose of this issue is to add Bloop as a package to SdkMan.

**Comment by jvican** [comment]
@diesalbla Would you be interested in contributing this in the next days? Otherwise I'll close the ticket until there is enough demand/someone that can spearhead this integration.

**Comment by diesalbla** [comment]
@jvican I am familiar with using the `sdkman` itself, but not with making packages for it, so I am afraid I cannot commit to doing this work.

**Comment by jvican** [comment]
@diesalbla Thanks for the feature request :smile: We'll revisit this as soon as there is someone willing to take up the work.
