### ISSUE TITLE
Should I be calling `bloop.Cli` to use Bloop?

### ISSUE THREAD

**Issue by jackkoenig** [scalacenter/bloop#823]
Thank you all for your great work!

I'm trying to use Bloop as a CLI for Zinc a la https://github.com/sbt/zinc/issues/544#issuecomment-393098057. For various reasons, the normal client/server flow doesn't fit into my larger build system.

I'm invoking the Bloop CLI using `coursier launch ... -M bloop.Cli`. Unfortunately, incremental compilation does not seem to work when invoked in this manner. It recompiles all of the Scala files every invocation.

I have made a repo that shows how to reproduce what I'm talking about: https://github.com/jackkoenig/bloop-incremental-compile

**Comment by jvican** [comment]
Hey @jackkoenig, sorry I've just seen this open ticket. Have you read the [Integration guide](https://scalacenter.github.io/bloop/docs/integration)? Concretely, [the launcher](https://scalacenter.github.io/bloop/docs/launcher-reference) is the recommended way of spawning a bloop server and using the CLI. The recommended way of connecting to the server is via BSP. There are BSP protocol bindings available for Java (bsp4j) and Scala (bsp4s) in https://github.com/scalacenter/bsp
  
In your example, the CLI is a short-lived process and right now it's not supposed to be used like you are using it. You need to use a server-client architecture which you can obtain via the previous docs.

**Comment by jvican** [comment]
Feel free to drop by our Gitter channel, by the way. I'd be happy to provide live support there.

**Comment by jackkoenig** [comment]
Thank you for your response @jvican (and all of your hard work on this great tool)!

Yeah I was *hoping* the CLI could serve as simple CLI for Zinc but I understand that's not what it's intended for, so I'll make the server-client architecture work.

I'll reach out on the Gitter channel if I have further questions. Thanks!
