### ISSUE TITLE
Bloop hangs after 4 broken bsp sessions ended

### ISSUE THREAD

**Issue by tpasternak** [scalacenter/bloop#825]
Repro steps:
1. Start bloop server
2. Start bloop bsp session `bloop bsp --socket=<socket>` and kill with `C-c`. Do this four times
3. Try `bloop about` - nothing happens, the server hanged

Here's the dockerfile showing this issue.
``` Dockerfile
FROM openjdk:8
RUN apt-get update
RUN apt-get install -y curl
RUN curl -s -L -O https://git.io/coursier
RUN chmod +x coursier
RUN ./coursier bootstrap --quiet -f --deterministic --output launcher ch.epfl.scala:bloop-launcher_2.12:1.2.5
RUN ./launcher --skip-bsp-connection 1.2.5 && \
    (rm -f /tmp/socket && timeout 2 ~/.bloop/bloop bsp  --socket /tmp/socket; exit 0)  && \
    (rm -f /tmp/socket && timeout 2 ~/.bloop/bloop bsp  --socket /tmp/socket; exit 0)  && \
    (rm -f /tmp/socket && timeout 2 ~/.bloop/bloop bsp  --socket /tmp/socket; exit 0)  && \
    (rm -f /tmp/socket && timeout 2 ~/.bloop/bloop bsp  --socket /tmp/socket; exit 0)  && \
    ~/.bloop/bloop about
```

**Comment by olafurpg** [comment]
Thanks for reproducing! I've never been able to reliably reproduce this myself but I believe I have hit on the same issue in Metals. At least, it's not uncommon for me to run `brew services restart bloop` to fix connection issues.

**Comment by propensive** [comment]
For the record, I can reproduce this. But I don't actually have to kill anything. I can just start four active `bloop bsp` commands on different ports, and the fifth will not work.

Is it likely that threads get assigned to BSP clients from a pool of 4, that killing `bloop bsp` doesn't release the thread, so we end up with thread starvation?

**Comment by jvican** [comment]
> Is it likely that threads get assigned to BSP clients from a pool of 4, that killing `bloop bsp` doesn't release the thread, so we end up with thread starvation?
  
Yes, that's exactly the case. Let me see how I can cut a hot fix for this bug.

**Comment by tpasternak** [comment]
By the way, if the session is not killed, but exits after client disconnection, the problem doesn't occur.

**Comment by jvican** [comment]
Aha, I figured this had to do with the proper resource releasing when the process exits unexpectedly.

**Comment by jvican** [comment]
A fix for this is coming.

**Comment by jvican** [comment]
Fixed in master

**Comment by chetankokil** [comment]
what is the fix for this, for me anything i do with bloop, it hangs , tries to start the server on 127.0.0.1:8212 and then fails with exit code 0

**Comment by tgodzik** [comment]
@chetankokil it's probably not related, best to raise a new issue. You can try running `bloop` with verbose flag to see what is happening. For example `bloop compile --verbose <project-name>`
