### ISSUE TITLE
Support shortened command line in Forker on Windows

### ISSUE THREAD

**Issue by kthompson** [scalacenter/bloop#831]
When I run `bloop test myproject --verbose` the `command` (33,666 characters long) that is output under `Fork options` exceeds the windows limit for processes (8,192) (see https://support.microsoft.com/en-us/help/830473/command-prompt-cmd-exe-command-line-string-limitation)

IntelliJ can get around this by making a classpath.jar file.

I cannot use bloop on windows unless this is resolve. If I can provide any additional informaiton please let me know.

Thanks

**Comment by kthompson** [comment]
Here is an example of a partial solution https://stackoverflow.com/questions/201816/how-to-set-a-long-java-classpath-in-windows

**Comment by jvican** [comment]
It would be great if we could do a better job here. @kthompson Could you send a patch to detect when there are more than 8192 entries in the classpath and, if that's the case, then synthesize a dummy jar with a manifest that includes all the entries coming from library dependencies? (Note that classes directories would not be there)

**Comment by jvican** [comment]
Actually, I worked around this issue in bloop with:
  
```scala
    val cmd = {
      if (!runWithInterpreter) cmd0
      else {
        if (Environment.isWindows) {
          // Avoid long classpath issues in Windows (e.g. https://github.com/sbt/sbt-native-packager/issues/72)
          if (cmd0.headOption.exists(_.startsWith("java"))) cmd0
          else List("cmd.exe", "/C") ++ cmd0
        } else {
          // If sh -c is used, wrap the whole command in single quotes
          List("sh", "-c", cmd0.mkString(" "))
        }
      }
    }
```
  
The trick is to use `java` directly instead of `cmd.exe`. We should be able to do the same in the bits that spawn a JVM for testing and running inside bloop.

**Comment by jvican** [comment]
This is a nice to have, let's reopen when there's someone who can implement a proper fix for this.

**Comment by kthompson** [comment]
Like I said this is a blocker for me to be able to use bloop but I guess I will check back in a few months.

**Comment by jvican** [comment]
Sure, it can be anybody's blocker, I'm not going to be working on this any time soon. If you're interested in using bloop and getting faster compiles, I've already given you some directions. Otherwise, yeah, check back in a few months and maybe someone has fixed it.

**Comment by kthompson** [comment]
Will do. Thanks 👍
