### ISSUE TITLE
Export environment variables from sbt

### ISSUE THREAD

**Issue by MasseGuillaume** [scalacenter/bloop#835]
We use the sbt setting `envVars` to set environment variables. I think those could be exported to the bloop config. This way, when I run `bloop test project-name`, those variable could be added automatically.

**Comment by jvican** [comment]
I understand where you're coming from, but supporting this feature would require changes in our bloop configuration format. Given that we're very conservative when it comes to adding fields there, I don't think this will ever be implemented. Environment variables are part of the environment bloop and sbt are run on and I think it's fair if we ask users to define them independently.
  
If you want to achieve more or less the same behavior, I suggest you replace environment variables with system properties. System properties are present in the `javaOptions` field for testing and running and those are indeed exported to bloop and present in our configuration file format.
