### ISSUE TITLE
Developer documentation is missing

### ISSUE THREAD

**Issue by odisseus** [scalacenter/bloop#846]
There is a link in [`build.sbt`](https://github.com/scalacenter/bloop/blob/master/project/build.sbt#L57) pointing to a page that doesn't exist anymore.

It looks like the page used to be there a year ago: https://web.archive.org/web/20180628094650/https://scalacenter.github.io/bloop/docs/developer-documentation/

**Comment by torkelrogstad** [comment]
This link is also used towards the end of the README

**Comment by jvican** [comment]
The documentation page wasn't migrated when the new website was published. I'll try to do so before the next release.
