### ISSUE TITLE
Replace `UUID.toString` with Base64 representations

### ISSUE THREAD

**Issue by odisseus** [scalacenter/bloop#848]
Random UUIDs are used to create a unique name for temporary directories, BSP client instances etc. Using a more compact representation of UUID will lead to shorter names and shorter debug logs.

Among different [widely known](https://blog.codinghorror.com/equipping-our-ascii-armor/) encodings, Base64 provides reasonable compression (32 hex characters to 22 Base64 characters) and is [safe](https://en.wikipedia.org/wiki/Base64#Filenames) to use in filenames.

**Comment by jvican** [comment]
> Using a more compact representation of UUID will lead to shorter names and shorter debug logs.
  
I like the end goal. Mind making a PR?

**Comment by odisseus** [comment]
Okay. Here's the implementation I'm going to use: https://scalafiddle.io/sf/cmu1FcG/0

**Comment by jvican** [comment]
Fixed in #851
