### ISSUE TITLE
Scoop fails after Bloop install due to SCOOP env variable

### ISSUE THREAD

**Issue by Arthurm1** [scalacenter/bloop#855]
Installing Bloop via Scoop on Windows sets the env variable `SCOOP=true`

AFAIK - Scoop expects that variable either to not exist or to point to the Scoop installation path. See...
[https://github.com/lukesampson/scoop/wiki/Quick-Start#installing-scoop-to-custom-directory](url)

Any subsequent calls to Scoop in new CMD shells fail because this setting means Scoop can't find the shims directory.

Using `set SCOOP=` fixes the issue

The variable seems to be set here but I can't understand why...
https://github.com/scalacenter/bloop/blob/8f0b0753dab127894d38240e49de9f6e2bc1d447/project/ReleaseUtils.scala#L193

**Comment by jvican** [comment]
Hey @Arthurm1, this is a great find... I don't understand why it's there either. Would you mind removing it and seeing if the package still works? You can run `install` to generate a new scoop formula that you can use to install bloop in your system.

**Comment by Arthurm1** [comment]
@jvican Looks like it's used here to help out the user...
https://github.com/scalacenter/bloop/blob/bc6233f45dfbcc3787c1aef529dc26392e587887/bin/install.py#L284-L286

We could change the variable name instead to `BloopUsesScoop` or somesuch?

**Comment by jvican** [comment]
Oh yeah, I remember now this was the reason why I did it. Completely forgot about checking for conflicts. Yeah, let's go for `BLOOP_IN_SCOOP`. Thank you @Arthurm1 :+1:

**Comment by jvican** [comment]
Fixed by https://github.com/scalacenter/bloop/pull/857
