### ISSUE TITLE
Using Ammonite REPL in Bloop projects

### ISSUE THREAD

**Issue by torkelrogstad** [scalacenter/bloop#877]
Depending on what's currently possible, this issue is either a feature request or a question.

In case you're not familiar with it, [Ammonite REPL](https://ammonite.io/#Ammonite-REPL) is an enhanced Scala REPL. During my development workflow I often want to jump into a console session, to experiment with or test certain features. I currently do this by opening up an sbt shell and starting ammonite from there, as described on the linked page above. After moving to bloop I'm getting spoiled by fast compilation and test times, and invoking `sbt` feels like stepping back into the dark ages. 

Is it possible to integrate Ammonite with Bloop? If not, that'd be an excellent edition to an already great tool.

**Comment by olafurpg** [comment]
You might be able to hack up a script to start ammonite with the classpath from bloop using command-line tools like `gron` and `jq`, example https://gist.github.com/olafurpg/7ba8e8af15206d7d2729e83f41fc9b8a

**Comment by torkelrogstad** [comment]
Thanks! I'll play around with that, and see if I can get something working.

**Comment by jvican** [comment]
> Is it possible to integrate Ammonite with Bloop? If not, that'd be an excellent edition to an already great tool.
  
I would love a better Ammonite integration! I've been considering replacing the default scala console with Ammonite by default as Ammonite now supports Windows (there are some thoughts on this in some issues discussing the current bugs of our console integration).
  
I haven't had the time to implement an Ammonite integration, but this would be a great contribution :smile: We could have bloop make `bloop console --ammonite` set up an ammonite command with the right classpath invocation and system process it. 
  
I posit that this is a better interface than redirecting people to an external script. Any thoughts?

**Comment by torkelrogstad** [comment]
I'd be happy to make a stab at implementing this. It'd be great to get some pointers. I haven't really looked much at the bloop codebase, so wouldn't know where to start.
