### ISSUE TITLE
Distinguish between pure Java/Scala BSP targets

### ISSUE THREAD

**Issue by olafurpg** [scalacenter/bloop#880]
Followup from https://github.com/scalameta/metals/pull/694#issuecomment-489164128

To reproduce:

- import apache/kafka repository with Bloop Gradle plugin
- open Metals and run doctor, which warns that many targets in the build are misconfigured
![](https://user-images.githubusercontent.com/1408093/57095217-9c433580-6d12-11e9-884f-5b28ab15db7c.png)
- I expected there to be no warning for the Java-only targets

The reason Metals warns about the Java-only targets is because `BuildTarget.languageIds=["scala","java"]` and `BuildTarget.data` includes Scala-specific information

```json
{
        "id": {
          "uri": "file:/Users/olafurpg/dev/kafka/clients/?id\u003dclients"
        },
        "displayName": "clients",
        "baseDirectory": "file:///Users/olafurpg/dev/kafka/clients/",
        "tags": [
          "library"
        ],
        "languageIds": [
          "scala",
          "java"
        ],
        "dependencies": [],
        "capabilities": {
          "canCompile": true,
          "canTest": true,
          "canRun": true
        },
        "data": {
          "scalaOrganization": "org.scala-lang",
          "scalaVersion": "2.12.8",
          "scalaBinaryVersion": "2.12",
          "platform": 1,
          "jars": [
            "file:///Users/olafurpg/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.8/scala-library-2.12.8.jar",
            "file:///Users/olafurpg/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.12.7/scala-reflect-2.12.7.jar",
            "file:///Users/olafurpg/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.12.7/scala-compiler-2.12.7.jar",
            "file:///Users/olafurpg/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.12/1.1.0/scala-xml_2.12-1.1.0.jar",
            "file:///Users/olafurpg/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/jline/jline/2.14.4/jline-2.14.4.jar"
          ]
        }
```

I expected the `languageIds` to be `["java"]` and the `data` field to be empty because the `.bloop/clients.json` file doesn't declare any `"scala"` field.

**Comment by jvican** [comment]
The fix for this is quite straight-forward :smile: When you're free, can you have a look at this @tgodzik ? I expect this can be fixed in half an hour; the only required change here would be to change `languageIds` in `BloopBspServices` to only include `Java` if `project.scalaInstance.isEmpty`.

**Comment by tgodzik** [comment]
@jvican It was somewhere on my list, I will take a stab at it sure.

**Comment by tgodzik** [comment]
I remember why I never finished it - project.scalaInstance is *never* empty - we have a default scala instance if one is not specified.
