### ISSUE TITLE
Remove unnecessary "didn't use pipelined compilation" log

### ISSUE THREAD

**Issue by jrudolph** [scalacenter/bloop#923]
I get "[W] The project ... didn't use pipelined compilation." message when project has no changes and `--pipeline` is enabled.
  
Purely cosmetical but it would be nice if that message could be suppressed if pipelined compilation was just not used because the sources didn't change and no recompilation was necessary.

**Comment by jvican** [comment]
@jrudolph Agreed! This log entry should go away. However note that build pipelining is yet not working fully for incremental scenarios, so it's an option that should be used for running full compiles locally or in the CI.
  
Next release v1.3.1 will make build pipelining the default mode and make it play nicely with incremental compilation (there are some technical challenges to solve there).

**Comment by jrudolph** [comment]
> @jrudolph Agreed! This log entry should go away. However note that build pipelining is yet not working fully for incremental scenarios, so it's an option that should be used for running full compiles locally or in the CI.

Aha, that's a good point that I didn't see from the documentation.

> Next release v1.3.1 will make build pipelining the default mode and make it play nicely with incremental compilation (there are some technical challenges to solve there).

Sounds good :+1:

**Comment by jvican** [comment]
> Aha, that's a good point that I didn't see from the documentation.
  
Yup, I'm writing right now docs for build pipelining :smile:

**Comment by jameskoch** [comment]
@jvican what's the best way to subscribe to those docs? I'm interested in following your progress to understand impact to some compiler plugin projects. Thanks!

**Comment by jvican** [comment]
@jameskoch Will let you know in this ticket when the docs are out :wink:

**Comment by tgodzik** [comment]
We disabled pipelining for now, so this will no longer show. We should enable it back at some point with the current Zinc mechanisms
