### ISSUE TITLE
Fix `ClassNotFoundException` in IntelliJ's test runner

### ISSUE THREAD

**Issue by ArturGajowy** [scalacenter/bloop#932]
Steps:

1. update to v1.3.0 or 1.3.2
2. sbt bloopInstall, reimport bsp project in intellij
3. Run any scalatest test
4. Observe a 'ClassNotFoundException' and a mention of possible wrong runpath.

Opening here (not in IntelliJ tracker), since it works with 1.2.5 :)

**Comment by jvican** [comment]
Hey @ArturGajowy Thanks for reporting! This ticket is most likely caused by the IntelliJ BSP integration, we did some changes between 1.2.5 and 1.3.0 which could require updates in IntelliJ. Would you mind opening a ticket over there? cc @jastice

**Comment by ArturGajowy** [comment]
Opened https://youtrack.jetbrains.com/issue/IDEA-216216, hope that's the right bug tracker? Couldn't find a scala subsystem. 

Having a link in issue_template.md to the right bug tracker for IntelliJ and other projects related to bloop would be helpful :)

**Comment by jvican** [comment]
Yup I think that's the one, thank you!

**Comment by jastice** [comment]
I looked into this and have to put the burden back on Bloop. Since 1.3, Bloop provides a different outputpath (`ScalacOptions.classDirectory`) for every bsp session. IntelliJ currently uses different sessions for loading the project and building, hence it will not find the classfile in the expected directory. 

Even if we used the same session, I would still expect problems: Any time the session needs to be restarted, for instance a client restart, this would require a refresh. For some projects and build systems, this can take minutes.

**Comment by jvican** [comment]
After an offline dicussion with @jastice, I have clarified that behavior is expected and clarified our positions. The fix to this is going to be mostly on the Bloop side while it'll require a small arrangement in the intellij-scala code. I'm re-opening.

**Comment by Igosuki** [comment]
Since using 1.3.2, I have to manually update the class paths of my modules after doing bloopInstall, it's pretty cumbersome

**Comment by Igosuki** [comment]
If this isn't going to be fixed soon, you should definitely patch the website and advise all intellij users not to update to 1.3.2

**Comment by fooblahblah** [comment]
Sorry to post to a closed issue, but I'm using Idea Ultimate 2019.2 and sbt-bloop to export. When I try and run tests I experience the issue with the classpath mentioned about. I was curious how #964 factors into this and if there's some option I need to pass to SBT?

**Comment by jvican** [comment]
The fix hasn’t yet been released, i recommend installing from master by following the docs in bloop or waiting until the next version is ready.
