### ISSUE TITLE
Don't require Java 8 on macOS

### ISSUE THREAD

**Issue by fredfp** [scalacenter/bloop#933]
Java 8 is still required when running on macOS (installed via brew)

**Comment by jvican** [comment]
Adding here an explanation of why this is not yet enabled in macOS from the release notes:

> Contributed by er1c, bloop v1.3.0 supports JDK 9 and JDK 11. If you run
bloop with these Java runtimes, it is recommended to enable the full parallel
GC with -XX:+UseParallelGC as compilation is faster.

> For this reason, Java 8 still remains the recommended runtime for the time
being and our installers might install it by default. In the future, we might
consider upgrading to a newer Java runtime.

**Comment by jvican** [comment]
Related https://github.com/scalacenter/bloop/issues/624

**Comment by jvican** [comment]
I'm closing this ticket because we will be removing this limitation soon, thanks for reporting @fredfp and following up with the PR.
