### ISSUE TITLE
Add --only-failures for test runs

### ISSUE THREAD

**Issue by matthughes** [scalacenter/bloop#936]
If you have lots of tests and only one of them fails, the default output hides the test failures.  While --watch is nice, if the failure happens among pages of output, the developer still needs to scroll up to see the failure.  Maybe we could have a different reporter or a shortcut for that reporter that reports # of successes (to ensure you're actually running something) and the details of each failure.

**Comment by matthughes** [comment]
Not sure if this is something that bloop can fix, but one thing that stinks about long test output is if you have to scroll up in your terminal, when you make a change to your code the normal behavior of `--watch` where it clears the terminal no longer works.

**Comment by jvican** [comment]
> Not sure if this is something that bloop can fix, but one thing that stinks about long test output is if you have to scroll up in your terminal, when you make a change to your code the normal behavior of --watch where it clears the terminal no longer works.

Completely agree with you! See this open pull request that will be opened soon and addresses exactly this issue by improving on the test report format https://github.com/scalacenter/bloop/pull/912
  
I'm closing this ticket so that all discussion moves to the PR instead
