### ISSUE TITLE
Unexpected error with `bloop console` in no project

### ISSUE THREAD

**Issue by cb372** [scalacenter/bloop#940]
Maybe I'm missing something, as I'm surprised nobody else has run into this, but ...

```
$ bloop console
Traceback (most recent call last):
  File "/usr/local/bin/bloop", line 1206, in <module>
    main()
  File "/usr/local/bin/bloop", line 1044, in main
    cmd_args = [cmd_args[0], "--out-file", out_file_path] + cmd_args[1:]
IndexError: list index out of range
```

This is with bloop v1.3.2 installed via Homebrew.

I think something may have gone awry during a spate of reverting and un-reverting in the nailgun fork?

* https://github.com/scalacenter/nailgun/commit/774bc6e3afea0ea6b581104bfe09ba14cdc2534e - Reduce verbosity of `bloop console`
* https://github.com/scalacenter/nailgun/commit/7dfdad8c730205d81ec52934155bc15002805a9a claims to revert the above commit but the diff also contains a bunch of other changes
* https://github.com/scalacenter/nailgun/commit/5d3bf3589a7d4b22e874fb103908699756692007 reverts the revert

**Comment by olafurpg** [comment]
What happens if you run `bloop console <project>`?

**Comment by cb372** [comment]
Ah, that works fine. PEBKAC 😄

**Comment by jvican** [comment]
@cb372 You caught a bug :smile: The syntax for console is always adding the project name after the command. We clearly didn't test what would happen if the user didn't pass anything.
