### ISSUE TITLE
Broken link to contributing guide in performance guide

### ISSUE THREAD

**Issue by jiminhsieh** [scalacenter/bloop#945]
* The link contains broken link - https://scalacenter.github.io/bloop/docs/performance-guide
* Here is the source of markdown - https://github.com/scalacenter/bloop/blame/master/docs/performance-guide.md#L279

I tried to follow [the instruction of **Updating documentation**](https://scalacenter.github.io/bloop/docs/contributing-guide#updating-documentation) to verify the result, but `yarn start` didn't work for me. So I have to post here instead of a PR.

**Comment by jvican** [comment]
Thank you for reporting, I've just fixed this! :pray:
