### ISSUE TITLE
Detect source-based plugins in buildpress

### ISSUE THREAD

**Issue by tkroman** [scalacenter/bloop#948]
Making an issue to bind a future PR to.
In short, we need to detect source-based sbt plugins so that changes to them are reflected in buildpress flows.

**Comment by tkroman** [comment]
@jvican in reply to your comment (https://github.com/scalacenter/bloop/issues/949#issuecomment-538697266) - yes, let me see if I can do this on my own, if not - I'll have to ask for your help.

**Comment by jvican** [comment]
Excellent, thanks @tkroman :smile:
