### ISSUE TITLE
`blp-server` send JVM options twice at macOS

### ISSUE THREAD

**Issue by jiminhsieh** [scalacenter/bloop#950]
When executing `bloop server` with JVM options, it will send twice of the same JVM options to JVM.

```bash
~ $ bloop server -J-Xms2g -J-Xmx2g
Defaulting on nailgun port 8212
There is no server running at port 8212
Starting the bloop server... this may take a few seconds
Running /usr/local/Cellar/bloop/1.3.2/bin/blp-server as a jar...
Shelling out with '['java', '-Xms2g', '-Xmx2g', '-jar', '/usr/local/Cellar/bloop/1.3.2/bin/blp-server']' ...
Error: Invalid or corrupt jarfile /usr/local/Cellar/bloop/1.3.2/bin/blp-server
Running /usr/local/Cellar/bloop/1.3.2/bin/blp-server as a script...
Shelling out in Unix system with ['sh', '/usr/local/Cellar/bloop/1.3.2/bin/blp-server', '-J-Xms2g', '-J-Xmx2g', '-J-Xms2g', '-J-Xmx2g']
Detected java options are '-Xms2g -Xmx2g -Xms2g -Xmx2g'
Unable to load nailgun-version.properties.
NGServer [UNKNOWN] started on address localhost/127.0.0.1 port 8212.
```

It doesn't have any impact of the running applicaiton, but it will be good to be fix though.

**Comment by jvican** [comment]
@jiminhsieh Can you look into this? The place to fix this is most likely `install.py`. If you can look into this, I'll assign this ticket to you.

**Comment by jiminhsieh** [comment]
@jvican Sure. It will be my pleasure. :) I will look into this issue this weekend.

**Comment by jvican** [comment]
Any progress with this @jiminhsieh :smile: ?

**Comment by jiminhsieh** [comment]
@jvican Here is my PR. https://github.com/scalacenter/nailgun/pull/13

**Comment by jvican** [comment]
Excellent! I'll merge it today and sync it up the version in this repo, thank you @jiminhsieh 👍

**Comment by jvican** [comment]
I'm closing this ticket as this issue is fixed in the next bloop release.
