### ISSUE TITLE
bloopInstall is slow - takes 16 minutes to export a gradle project to bloop

### ISSUE THREAD

**Issue by pkolaczk** [scalacenter/bloop#954]
Exporting the project takes much longer than building it fully.
CPU is mostly idle when bloopInstall is running. 
Any ideas? What should I check?

**Comment by marek1840** [comment]
Do you have a thread dumps or memory usage log by any chance? 
Also, can you share the project you are trying to export?

**Comment by pkolaczk** [comment]
I can't share a project, because it is proprietary. :(
What process should I collect thread-dumps of?

**Comment by plokhotnyuk** [comment]
@pkolaczk to see what is happening you can use [the wall-clock mode](https://github.com/jvm-profiling-tools/async-profiler#wall-clock-profiling) of async-profiler

**Comment by pkolaczk** [comment]
Interestingly I can't reproduce it now - this was only the first import that was slow. 
Resetting the project and erasing all the .bloop files and gradlew installBloop took ~1 minute this time.

**Comment by tkroman** [comment]
Probably dependency downloads?

**Comment by pkolaczk** [comment]
Probably. Dependency downloads are reported and I can see their progress when they are downloaded. However most of the time the message displayed by gradle was only "resolving files" and no download progress bar.

**Comment by plokhotnyuk** [comment]
It could be any networking issue like unexpected delays in DNS resolving, opening of connections to overloaded servers, etc.
