### ISSUE TITLE
Misuse of encoding set in Gradle causes compile error

### ISSUE THREAD

**Issue by pkolaczk** [scalacenter/bloop#955]
I exported projects to bloop. It went fine.
Then running `bloop compile <my_project>` issues the error:

```
Compiling xxxxx-util (5 Scala sources)
[E] bad option: '-encoding UTF-8'
Compiled xxxxx-util (11ms)
[E] Failed to compile 'xxxxx-common', 'xxxxxx-util' and 2 more projects
```

I've found this in some json files under `.bloop`:
```
"scala" : {
            "organization" : "org.scala-lang",
            "name" : "scala-compiler",
            "version" : "2.11.12",
            "options" : [
                "-deprecation",
                "-encoding UTF-8",
                "-feature",
                "-unchecked"
            ],
```

**Comment by pkolaczk** [comment]
Removing the line `"-encoding UTF-8",` helps.

**Comment by tkroman** [comment]
Those should be 2 separate options afaik.

**Comment by Arthurm1** [comment]
It looks like the Bloop doesn't cope with Gradle defining encoding using...
```
compileScala {
    scalaCompileOptions.encoding = 'UTF-8'
}
```

But as a workaround you can use...
```
compileScala {
    scalaCompileOptions.additionalParameters = ["-encoding", "UTF-8"]
}
```

**Comment by pkolaczk** [comment]
Thanks, that works!
But it would be nice to fix it anyway in bloop.

**Comment by jvican** [comment]
Thanks for reporting! Help fixing this is welcome, I'm not going to have a look at this any time soon.

I guess the encoding option is automatically added by Gradle as a one-line argument to the default Scala options. The bloop gradle plugin should most likely be splitting up all options that have white spaces (which is likely done internally by Gradle before using the internal compiler APIs).

**Comment by pkolaczk** [comment]
Please assign to me. I'll fix it. PR coming.
