### ISSUE TITLE
Unexpected error using a Java annotation processor

### ISSUE THREAD

**Issue by pkolaczk** [scalacenter/bloop#956]
```
[E] [E-1] Errors during annotation processing
[E] [E18] XXXX.java:17
[E]       Exception during annotation processing: java.lang.IllegalArgumentException: Not supported: sbt.internal.inc.javac.WriteReportingJavaFileObject@3e42b4ef

// last error repeats many times, followed by errors about missing symbols

[E] [E12] YYYYYY.java:41
[E]       cannot find symbol
[E]         symbol:   class .....
[E]         location: class ....
```

**Comment by tkroman** [comment]
Would be nice to have a minimized repro

**Comment by pkolaczk** [comment]
This is failing in a proprietary project, and not even maintained by my team. Where do I get more details about the exception? Maybe a stacktrace could tell us more?

**Comment by pkolaczk** [comment]
We've found something possibly related:
https://github.com/sbt/zinc/issues/185

**Comment by pkolaczk** [comment]
Minimized repro here: https://github.com/pkolaczk/bloop-annotation-processor-failure

**Comment by pkolaczk** [comment]
The problem is caused by the fact Bloop installs its own `ForwardingFileManager`:
https://github.com/scalacenter/bloop/blob/1fcd2e8359e9b54f896d919f6b19f04b427aff64/backend/src/main/scala/bloop/CompilerCache.scala#L267

I wonder if the `isSameFile` bug could be fixed simply by overriding it, and un-wrapping JavaObjects before passing to the underlying wrapped FileManager.

**Comment by pkolaczk** [comment]
Overriding isSameFile solves the problem. Unfortunately I can't unwrap WriteReportingFileObject, because the wrapped object is protected. 

Which one do you prefer:
1. Change code in sbt to make the nested file object a public field.
2. Use an ugly reflection hack.
3. Skip delegating to the nested FileManager and just use equals (my current hack that works).

?

**Comment by jvican** [comment]
Thanks for reporting and the investigation! @pkolaczk Please be more precise in the all titles of your issues and the descriptions, they are very useful but too vague for anyone to have a look and provide meaningful feedback.
  
Can you show me what your current "hack" is? What we could do here is to modify `BloopInvalidatingFileManager` to override or re-implement `isSameFile` so that we unwrap the java object before further processing. I don't grasp exactly what's happening here but provided that this is safe to do it's something we definitely can consider merging in bloop and publishing it asap, without any changes in sbt.

**Comment by pkolaczk** [comment]
Sorry for the titles, this is because when I reported them I had less context than later when I investigated. Thank you so much for updating. 

My current "hack" is this:

```scala
    final class BloopInvalidatingFileManager(
        fileManager: JavaFileManager,
        zincManager: ClassFileManager
    ) extends ForwardingJavaFileManager[JavaFileManager](fileManager) {
      import scala.collection.JavaConverters._
      override def getJavaFileForOutput(
          location: Location,
          className: String,
          kind: Kind,
          sibling: FileObject
      ): JavaFileObject = {
        val output = super.getJavaFileForOutput(location, className, kind, sibling)
        import sbt.internal.inc.javac.WriteReportingJavaFileObject
        new WriteReportingJavaFileObject(output, zincManager)
      }

      import java.{util => ju}
      override def list(
          location: Location,
          packageName: String,
          kinds: ju.Set[Kind],
          recurse: Boolean
      ): Iterable[JavaFileObject] = {
        val invalidated = zincManager.invalidatedClassFiles().map(_.getAbsolutePath()).toSet
        val ls = super.list(location, packageName, kinds, recurse)
        ls.asScala.filter { o =>
          !invalidated.exists { invalidatedPath =>
            o.getName().contains(invalidatedPath)
          }
        }.asJava
      }

     // added this:
      override def isSameFile(a: FileObject, b: FileObject): Boolean =
       a == b
   }
```

**Comment by jvican** [comment]
Thanks, a few questions given that you've already had a deep look at the problem:
  
1. Why is the original error happening? 
1. What are the implications of that change? Why does it work at all?
1. Is there any other change in the impl of the class manager that might be better?

**Comment by pkolaczk** [comment]
1. It is well explained in the sbt issue I linked. There is a hardcoded check in `ForwardingJavaFileManager` that checks if passed objects are of `BaseFileObject` class. If the arguments are not, and `WriteReportingJavaFileObject` is not, it throws this unsupported Exception I got. We obviously can't remove that check, because it is in JDK. So the only things that are left are: either not using customized JavaFileManager (which SBT decided to do - they just turned off that logic and made it opt-in), or overriding `isSameFile` in such a way that the original JDK code gets instances of `BaseFileObject`. 

2. It works, because in fact the code after the hardcoded assertion in JDK eventually does exactly that: `object1.equals(object2)`. So my hack is actually equivalent to the original code, but it skips the instanceof check.

3. I can't think of any now. But I'm not an expert on that.

**Comment by jvican** [comment]
> A proper change would be to unwrap the FileObject instances from the WriteReportingJavaFileObject instances and pass them to the wrapped file manager.
  
Can we do that? I'd merge such a PR right away.

**Comment by pkolaczk** [comment]
> Can we do that? I'd merge such a PR right away.

No, because this requires a tiny change in SBT to make the wrapped `FileObject` an accessible field.
Otherwise, you can't unwrap, because there is no access to the wrapped value.

I'll do a PR to the SBT project.

**Comment by jvican** [comment]
Let me know when the PR is up, I'll approve it in sbt/zinc and merge it right away in our fork (scalacenter/zinc) to release a new version that we can update to in bloop.

**Comment by pkolaczk** [comment]
The PR in sbt/zinc is up: https://github.com/sbt/zinc/pull/685

**Comment by jvican** [comment]
Will be syncing it up with the scalacenter/zinc repo today, thanks @pkolaczk 👍

**Comment by pkolaczk** [comment]
Sbt/zinc patch has been merged.
Can you sync bloop with it, so I can finalize the bloop side of the patch?
Thank you!

**Comment by jvican** [comment]
I'll take care of syncing this with latest zinc and also finishing the patch. Thanks for the investigation and all the follow-up work in the zinc repo.

**Comment by jvican** [comment]
https://github.com/scalacenter/bloop/pull/997 upgrades with latest zinc, I won't have time to finish this ticket, @pkolaczk could you send a PR to add a test case and finish the patch?

**Comment by pkolaczk** [comment]
Yes, I'll do it today. Thank you so much!

**Comment by pkolaczk** [comment]
I'm missing this change:

https://github.com/pkolaczk/zinc/blob/32d752cb3da0b8cf82635bf68187a92b08187d43/internal/zinc-compile-core/src/main/scala/sbt/internal/inc/javac/LocalJava.scala#L292

Have you applied that patch to bloop's zinc?
