### ISSUE TITLE
Support unit test arguments

### ISSUE THREAD

**Issue by pkolaczk** [scalacenter/bloop#959]
Can bloop use custom JVM parameters and test arguments for Junit and other test frameworks?
Are they imported from Gradle?

**Comment by tgodzik** [comment]
From what I see in the code they should be - is there any issue with that? Also it might be easier to ask questions on gitter: https://gitter.im/scalacenter/bloop 

You would get a much faster feedback there.

**Comment by pkolaczk** [comment]
So far it doesn't work for us, but I'm just investigating. If you say it should, then maybe there is a problem with our build. Thank you!

**Comment by jvican** [comment]
Yes, it should. You can see if they are correctly exported by peeking at the values of test options inside the bloop configuration files of the **test** build targets. An example of a build target with exported test arguments is https://gist.github.com/jvican/877fefbcbe31b0047c01053dc43e7135 You can also see how test arguments can either be universally applied to all test frameworks found in a project or only be framework-specific.
