### ISSUE TITLE
Respond with adequate test reports to BSP test

### ISSUE THREAD

**Issue by samvel1024** [scalacenter/bloop#960]
[Here](https://gist.github.com/samvel1024/c3a434a0ef6f3a555730d14ef9392166) is the structure of my project. Basically it's the hello world project from SBT examples. I have successfully exported it to bloop.

Now I am trying to run it with BSP buildTaregt/test. [Here](https://gist.github.com/samvel1024/9b582103df7d2003253efc97ee4e8af4) is the log of all JSON RPC messages. 

1. I successfully receive all the logs generated during testing. Pay attention to line 191, it says `1 tests, 1 failed`
2. Line 207 says `Missing configured test frameworks in root` which is probably why, on line 214 I get statusCode 1, which probably maps to ch.epfl.scala.bsp4j.StatusCode.OK (ordinal = 1). Seems like bloop is not able to understand the results generated by the test framework. 

However, when running from CLI I get information about failing tests (at least exit code is not 0), which means that behaviour of BSP server in Bloop is inconsistent with the CLI (if I don't miss some important configuration).

<img width="432" alt="Screen Shot 2019-07-12 at 15 17 16" src="https://user-images.githubusercontent.com/19408688/61124523-28fb3400-a4b8-11e9-98c5-05a8229a2246.png">

**Comment by jvican** [comment]
Bloop uses the same logic for both, the only difference here is in how the logs are reported to the client and, most importantly, the exit code, which is OK via BSP (a bug) but failed in the CLI. The `buildTarget/test` endpoint has not yet been completely finished and these are well-known issues. I'll have a look at fixing them soon.
