### ISSUE TITLE
Export javac fork options from Gradle

### ISSUE THREAD

**Issue by pkolaczk** [scalacenter/bloop#966]
Sometimes a project may want to use a different JDK than the default one.
In gradle this is accomplished by setting fork options:

```
javaCompile.options.fork = true 
javaCompile.options.forkOptions.javaHome = ...
javaCompile.options.forkOptions.memoryInitialSize = "2g"
javaCompile.options.forkOptions.memoryMaximumSize = "2g"
```

These should be exported from Gradle to .bloop/

**Comment by pkolaczk** [comment]
I'm working on this.

**Comment by jvican** [comment]
@pkolaczk Excellent, thanks!
