### ISSUE TITLE
`--help` instructions unclear for passing multiple arguments using `bloop run --args` 

### ISSUE THREAD

**Issue by ArturGajowy** [scalacenter/bloop#971]
There's no example in the `--help` text, and based on #253 I assume it'd have to be passed multiple times. Adding ```pass multiple times for each arg, or consider using `--` ``` would help

**Comment by jvican** [comment]
The syntax is `--args $FST_ARG`, `--args $SND_ARG`, etc. We cannot change this, these are the semantics of coursier. I would welcome a documentation change in our Quickstart guide to make it clear that you can run an application and pass arguments to it with `-- all your args`. We have an example to pass JVM arguments but not to pass normal arguments.
