### ISSUE TITLE
Unexpected compile dependency in sbt projects with configuration dependencies

### ISSUE THREAD

**Issue by zainab-ali** [scalacenter/bloop#976]
The bloop sbt plugin does not respect [per configuration classpath dependencies](https://www.scala-sbt.org/release/docs/Multi-Project.html#Per-configuration+classpath+dependencies).

The following `build.sbt` file
```scala
lazy val foo = project in file("foo")

lazy val bar = (project in file("bar"))
.dependsOn(foo % "test->test")
```
In this example, bar should have a test dependency on foo, but not a compile dependency. 
The `.bloop/bar.json` file should not contain a dependency on foo.
However, the `bar.json` contains:

```json
    "version" : "1.1.2",
    "project" : 
        "name" : "bar",
        ....
        "dependencies" : [
            "foo"
        ],
```

`bloop compile bar`compiles `foo` as well as `bar`.

**Comment by jvican** [comment]
Thanks for reporting @zainab-ali! This is a good catch 😊  `sbt-bloop` does support per configuration classpath dependencies but it looks like it's too conservative when pinning down normal compile dependencies between projects. `bar-test` correctly depends on `foo-test` but `bar` should, as you say, not depend on `foo`.
