### ISSUE TITLE
Direct jar dependencies not imported from Gradle

### ISSUE THREAD

**Issue by pkolaczk** [scalacenter/bloop#978]
Create a project with the following dependency:

```
dependencies {
    implementation(files(org.gradle.internal.jvm.Jvm.current().toolsJar))
}
```

Expected:
The tools.jar is included in the bloop project classpath.

Actual:
The tools.jar is missing from the bloop project classpath.

**Comment by jvican** [comment]
Thanks for reporting! I hope this dependency is not for compiling, but just for running/testing.

**Comment by pkolaczk** [comment]
Running/testing.
So far I've found the problem is caused by the fact that Gradle API doesn't include this dependency in the list of `ResolvedArtifact` objects. This comes as a `SelfResolvingDependency` and is returned by the `runtimeClassPathConfiguration.getResolvedConfiguration.getFiles`. Bloop is generating dependencies only from the resolved artifact list, and this way it skips these directly included jars outside of the project.

**Comment by pkolaczk** [comment]
Thank you! :)
