### ISSUE TITLE
Unexpected error when starting server via systemd

### ISSUE THREAD

**Issue by gervaisb** [scalacenter/bloop#990]
I have installed bloop 1.3.2 via curl, I can start it from the CLI and get an answer from `bloop about`.

    $ bloop server
> Defaulting on nailgun port 8212
> There is no server running at port 8212
> Starting the bloop server... this may take a few seconds
> Running /home/me/.bloop/blp-server as a jar...
> Shelling out with '['java', '-jar', '/home/me/.bloop/blp-server']' ...
> Unable to load nailgun-version.properties.
> NGServer [UNKNOWN] started on address localhost/127.0.0.1 port 8212.

    $ bloop about
> bloop v1.3.2
> 
> Using Scala v2.12.8 and Zinc v1.3.0-M4+22-4704d479
> Running on Java v1.8.0_212 (/home/me/.sdkman/candidates/java/8.0.212-zulu/jre)
> Maintained by the Scala Center (Martin Duhem, Jorge Vicente Cantero)

But trying to start it via systemcl fail.

    $ systemctl --user status bloop
> ● bloop.service - Bloop Scala build server
>    Loaded: loaded (/home/me/.bloop/systemd/bloop.service; enabled; vendor preset: enabled)
>    Active: failed (Result: exit-code) since Tue 2019-07-30 14:27:38 CEST; 4s ago
>   Process: 4038 ExecStart=/home/me/.bloop/bloop server (code=exited, status=1/FAILURE)
>  Main PID: 4038 (code=exited, status=1/FAILURE)
> 
> jui 30 14:27:38 me-laptop bloop[4038]:     retcode = call(*popenargs, **kwargs)
> jui 30 14:27:38 me-laptop bloop[4038]:   File "/usr/lib/python2.7/subprocess.py", line 172, in call
> jui 30 14:27:38 me-laptop bloop[4038]:     return Popen(*popenargs, **kwargs).wait()
> jui 30 14:27:38 me-laptop bloop[4038]:   File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
> jui 30 14:27:38 me-laptop bloop[4038]:     errread, errwrite)
> jui 30 14:27:38 me-laptop bloop[4038]:   File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
> jui 30 14:27:38 me-laptop bloop[4038]:     raise child_exception
> jui 30 14:27:38 me-laptop bloop[4038]: OSError: [Errno 2] No such file or directory
> jui 30 14:27:38 me-laptop systemd[1591]: bloop.service: Main process exited, code=exited, status=1/FAILURE
> jui 30 14:27:38 me-laptop systemd[1591]: bloop.service: Failed with result 'exit-code'.

    $ journalctl --user-unit bloop
> -- Logs begin at Fri 2019-05-24 17:55:45 CEST, end at Tue 2019-07-30 14:28:24 CEST. --
> jui 30 14:12:54 me-laptop systemd[1591]: Started Bloop Scala build server.
> jui 30 14:12:54 me-laptop bloop[656]: Defaulting on nailgun port 8212
> jui 30 14:12:54 me-laptop bloop[656]: There is no server running at port 8212
> jui 30 14:12:54 me-laptop bloop[656]: Starting the bloop server... this may take a few seconds
> jui 30 14:12:54 me-laptop bloop[656]: Running /home/me/.bloop/blp-server as a jar...
> jui 30 14:12:54 me-laptop bloop[656]: Shelling out with '['java', '-jar', '/home/me/.bloop/blp-server']' ...
> jui 30 14:12:54 me-laptop bloop[656]: Traceback (most recent call last):
> jui 30 14:12:54 me-laptop bloop[656]:   File "/home/me/.bloop/bloop", line 1206, in <module>
> jui 30 14:12:54 me-laptop bloop[656]:     main()
> jui 30 14:12:54 me-laptop bloop[656]:   File "/home/me/.bloop/bloop", line 1120, in main
> jui 30 14:12:54 me-laptop bloop[656]:     check_call(java_cmd)
> jui 30 14:12:54 me-laptop bloop[656]:   File "/usr/lib/python2.7/subprocess.py", line 185, in check_call
> jui 30 14:12:54 me-laptop bloop[656]:     retcode = call(*popenargs, **kwargs)
> jui 30 14:12:54 me-laptop bloop[656]:   File "/usr/lib/python2.7/subprocess.py", line 172, in call
> jui 30 14:12:54 me-laptop bloop[656]:     return Popen(*popenargs, **kwargs).wait()
> jui 30 14:12:54 me-laptop bloop[656]:   File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
> jui 30 14:12:54 me-laptop bloop[656]:     errread, errwrite)
> jui 30 14:12:54 me-laptop bloop[656]:   File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
> jui 30 14:12:54 me-laptop bloop[656]:     raise child_exception
> jui 30 14:12:54 me-laptop bloop[656]: OSError: [Errno 2] No such file or directory
> jui 30 14:12:54 me-laptop systemd[1591]: bloop.service: Main process exited, code=exited, status=1/FAILURE
> jui 30 14:12:54 me-laptop systemd[1591]: bloop.service: Failed with result 'exit-code'.

Since it start via the CLI I assume taht all depencies are met. So I don't have any idea on how to solve that issue.

**Comment by jvican** [comment]
Hey @gervaisb, this usually happens when you don't have `$PATH` correctly configured in your systemd. The system process API in bloop is failing because it most likely can't call `java` from there. You need to change your environment for the operation to work. As you see, `bloop server` works inside your terminal.
