### ISSUE TITLE
Incorrect compile order after exporting project from Gradle

### ISSUE THREAD

**Issue by pkolaczk** [scalacenter/bloop#992]
Gradle compile order semantics are different than Bloop's.
Consider the following config:
```
sourceSets {
    main {
        java {  srcDirs = ['src/java'] }
        scala {  srcDirs = ['src/scala'] }
    }
}
```

This means: compile `src/java` with the Java compiler first, then compile `src/scala` with the Scala compiler. For such config, we should set compile order to JavaThenScala.

However, it is possible to specify joint compilation in Gradle like this:

```
sourceSets {
    main {
        java {  srcDirs = [] }
        scala {  srcDirs = ['src/java', 'src/scala'] }
    }
}
```

This means, mixed compilation should be used.
You don't always want mixed compilation, because Java annotation processors don't work reliably if they generate classes that are used in the same project when mixed compilation is used (probably something that should be addressed by sbt/zinc anyway, but this is a different issue). 

Unfortunately I can see that Bloop's project model is not flexible enough to reflect Gradle model fully, because Bloop throws all sources into the same bin, and the only choice is compile order. 

For example this is impossible to model in Bloop now:

```
sourceSets {
    main {
        java {  srcDirs = ['src/java-that-must-be-compiled-first] }
        scala {  srcDirs = ['src/scala', 'src/java-that-should-be-mixed-with-scala] }
    }
}
```

I believe in this case we maybe could just generate 2 projects instead of one, similar way how we're doing with tests. But this looks like a complex change to BloopConverter.

For now I just do some simple hack to set compile order based on existence of non-empty java source set.

**Comment by jvican** [comment]
> I believe in this case we maybe could just generate 2 projects instead of one, similar way how we're doing with tests
  
I believe this should be the way we do it given that the compile order semantics are implicitly derived from the contents of the java and Scala configuration of a target.
  
Does #993 fix this?
